### PR TITLE
added channie farber advice

### PR DESCRIPTION
**Pull request by channiefarber**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @channiefarber !

This is a great start!! There are just a few things we need before we can merge this in.

1) There was an empty file called `advice/style.css` that was added to the pull request - we don't need that file so please delete it.

2) You are referencing a file called `channie-farber-style.css` in the head of your advice file - but no such file has been added to the `css` directory. Does it still need to be added and committed? A `git status` will help you confirm.

Once you have removed the empty file and added your css file, make sure to add your changes with `git add -A`, then commit as per usual and finally push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by channiefarber** [comment]
Hi,
I apologize, feeling a bit lost & confused :(
I tried removing that empty file, but it says it doesnt exist. I also tried
getting back into the repo through the Terminal and am not managing to even
do that! Attaching a screenshot of my attempts, hoping you can help me
understand what I am doing wrong. Thanks for your patience!

**Comment by redrambles** [comment]
Hey @channiefarber !

We didn't get your screenshot on our end - feel free to email us at questions@skillcrush.com - it's easier to send screenshots in regular emails. If you prefer - you can also just pull out your advice file from the project and stick it temporarily on your Desktop and then reset your advice branch to the tip of your upstream remote connection's main branch - which would bring it up to date. Then you can pop back in your advice file inside the 'advice' directory - add your link in the index.html file, add and commit your changes and push up your advice file, which will automatically update this pull request.

Do you want to give that a try?

If so - here are the steps:
1) Tuck away your advice file in a safe spot temporarily (i.e. - the Desktop)
2) Run `git fetch upstream`
3) Run `git reset --hard upstream/main` - now your advice branch is up to date with the upstream repository - yay!
4) Pop your advice file back inside the advice folder
5) Open up your index.html file and type in your link to your advice folder somewhere in that long list
6) Add and commit your changes 
7) Push up your advice branch
8) Dance!

Let us know what you decide to do!! :)

Cheers,
Ann :)

**Comment by channiefarber** [comment]
Hi,
I got stuck at step 5. Can you please remind me how to do that part?
Thank you!

**Comment by redrambles** [comment]
You'll want to open up the index.html file in your editor of choice, and then add your link to the list. You'll want to do something very similar to existing links - but just make sure it points to your advice file and that the text between the anchor tag is updated to include your name. :)

**Comment by channiefarber** [comment]
Ok, thanks! So I did that, and then when I restarted terminal and did the
hard reset again (step 3) i seem to be unable to access the advice folder
at all, (see screenshot) and so I'm unsure how to get my advice file back
into there...sorry for all this trouble, I know this step shouldnt be that
hard![image: Screen Shot 2021-07-11 at 10.39.04.png]

**Comment by channiefarber** [comment]
actually never mind that, figured that bit out :)
trying to do the push part and it keeps telling me fatal error :(
could you please remind me how to properly do that?

**Comment by redrambles** [comment]
@channiefarber 

You should be able to push up with the following syntax:
`git push <where> <which_branch>`

In this particular case, that would be:
`git push origin advice`

If you are getting an error when running the command above - make sure that you are inside the correct directory. If you are, then please take a screenshot of the error you are getting and send it in at `questions@skillcrush.com` and we will have a closer look. :)

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @channiefarber !

Ok - we're making progress! We've got the css file (yay!) - but now two things remain.

1) There is an empty file called `advice/style.css` in the pull request which we don't need, so please remove it. (Delete the file in any way you like, and then when you add and commit that change it will carry over to the pull request.)

2) We still need a link in the index.html that points to your advice file. Check out your index.html file with your editor of choice - you will see a long list of links. We want you to add your own link to the list, so that folks can find your words of wisdom once the pull request has been merged.

Once you have done this, add with `git add -A`, commit as per usual `git commit -m "Your message here"` and then push up your advice branch once more `git push origin advice` and we should be all set.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by channiefarber** [comment]
Hi,
Ok thanks! So I don't quite know how to find and delete that empty file,
since when I search the computer for it, it doesn't appear. Also, in the
terminal, it lists that file as already deleted. Is there another way to
accomplish removing it? Would I do it with git rm?

As far as adding my link to the index.html file, I did that in the past and
saved it. I'm wondering what I did wrong that makes it not visible to
you...?

Thank you!!!

**Comment by acodeinprogress** [comment]
Hi @channiefarber,

Can you send an email to questions@skillcrush.com with a screenshot of your terminal after you run the command `git status`?

xoxo,
Sharon

**Comment by channiefarber** [comment]
-- Please reply above this line --


            Hey there!

Thank you! Ok! So let's get rid of those '.DS_Store' files next:

rm advice/.DS_Store
rm .DS_Store
rm css/.DS_Store

And then let's add those changes:
git add -A

and commit them:
git commit -m "Removed unnecessary files"

Then push up:
git push origin advice

Now that this is done - the only thing that remains is for you to open
up your index.html file and add your link to your advice file
somewhere in that long list. Most students add theirs to the bottom of
the list, but you could add your link to the top or pop it in the
middle of the list, it doesn't matter.

Once you do this, add the change with `git add -A' - then commi as per
usual, and finally push up your advice branch again.

At this point we should have everything we need to merge in your code.
🎉

You got this - keep us posted!

Cheers,
Ann :)


--
Ann @skillcrush
Skillcrush

DID WE MAKE IT EASY FOR YOU TO GET THE HELP OR INFORMATION YOU NEEDED?

**Comment by acodeinprogress** [comment]
Hi @channiefarber,

I see that you replied to Ann's message but I don't see anything in your reply. Can you please try again or email us at questions@skillcrush.com?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @channiefarber !

Ok - we are getting closer! I now see that we have a `css/channie-farber-style.css` file with your styles in it - great!! What we now need is your advice file (which should be in your advice directory) and then a link to it from the index.html file.

Then go ahead and add and commit and push up your `advice` branch again to update this pull request.

Once we have both of those things that we still need, we will be all set to merge in your code. Keep us posted!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @channiefarber,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
