### PR TITLE
Added Patricia advice link

### PR DESCRIPTION
**Pull request by preich-work**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @preich-work,

This is a fantastic start! I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by preich-work** [comment]
I think I added the html page now....

**Comment by preich-work** [comment]
I was afraid you were going to say that. I have gone back and updated. I don't think I need to initiate another pull request.
     On Saturday, July 1, 2023 at 06:54:20 PM EDT, Lisa Savoie ***@***.***> wrote:  
 
 


Hey @preich-work,

This is a fantastic start! I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @preich-work,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
