### PR TITLE
Added Ai-Ling's advice

### PR DESCRIPTION
**Pull request by chocosqrl**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @chocosqrl,

This is great! The only thing we need is for you to add a `<br>` tag at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add and commit and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @chocosqrl,

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by chocosqrl** [comment]
> Hi @chocosqrl,
> 
> Just checking to see if you need any help with this pull request. Let us know if you have any questions!
> 
> Best, Lisa

Sorry for the delay! Pull request updated - Thanks! -ac

**Comment by twosavoie** [comment]
Hey @chocosqrl,

No worries! You did a great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
