### PR TITLE
Added mikayla-utley-advice.html and my own advice

### PR DESCRIPTION
**Pull request by utleym**
I added my own advice to the bottom of the advice page and added mikayla-utley-advice.html to the main page.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @utleym,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @utleym, 

Checking in to see if you need any help with this pull request. Reach out if you have any questions! 

Best,
Lisa

**Comment by utleym** [comment]
Hey @twosavoie!

I am just a little confused. I thought I did link the two files. Did I just forget to run the git push origin advice part? Let me know what can be done. It's probably something obvious. 

Best,
Mikayla

**Comment by utleym** [comment]
Good afternoon,

I think I fixed it! Hopefully.

Best,
Mikayla

**Comment by twosavoie** [comment]
Hey @utleym,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
