### PR TITLE
Added new entry to advice trail

### PR DESCRIPTION
**Pull request by aotech7**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @aotech7,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @aotech7,

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by aotech7** [comment]
Hi Lisa,

My bad, I thought I was finished: I will check it out and get back with
you. Thank you!

**Comment by aotech7** [comment]
Thank you Lisa! I saw your pull request.  It looks like I had another step to complete and I included the link to my pull request in my assignment on the Skillcrush platform.

**Comment by aotech7** [comment]
Hi Lisa, 
I just wanted to make sure I did not need to do anything else for this pull request.  

Thank you!

**Comment by twosavoie** [comment]
Hi @aotech7,

Great to hear from you! I don't see that a link has been added to the index.html file. Can you check to be sure that the link has been added while the **advice** branch is checked out (rather than the main branch.) Then be sure that the changes are saved in your text editor. In the command line, run `git status` to confirm you're on the advice branch and to see if there are any changes to be added and committed. If so, go ahead and then push the advice branch to GitHub. This will update your pull request automatically. 👍 

If you made the change on the main branch and all changes have been added and committed, can you also run `git log` and send us a screenshot of your command line? Also send a screenshot of the index.html file in your text editor. You can send these to questions@skillcrush.com and we'll go from there!

Let us know if there's anything we can clarify!

Best,
Lisa

**Comment by aotech7** [comment]
Hi Lisa,

Thanks for taking the time to send me this explanation. I am going to
review the exercise and try again. If it still doesn't work, I will reach
out again. Also, I liked the emoji for the gihub exercise!

Have a good rest of your day,

Amaka

**Comment by aotech7** [comment]
Hi Lisa,

Thanks for all your help with github. I am sending two screenshots: my
command line and the index.html file. My entry is at the bottom under
AngelaO.


Have a good day,

Amaka

**Comment by twosavoie** [comment]
Hi @aotech7,

Just checking in to see if you have any questions. 🙂 

Best,
Lisa

**Comment by aotech7** [comment]
Hi Lisa,
Thank you for reaching out. Tauri was able to help answer my questions.
Hope you have a good rest of your day🤗

**Comment by twosavoie** [comment]
Hi @aotech7,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Comment by aotech7** [comment]
Ah, thank you! I thought I was finished with the exercise and didn’t
realize there was an extra step. Will take a look again at the lesson.

**Pull request closed without merging**
