### PR TITLE
Vanessa's advice for coding newbies

### PR DESCRIPTION
**Pull request by blackmanvanessa**
Yikes! I took a couple of days off and am really not sure if this is working...

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @blackmanvanessa,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by blackmanvanessa** [comment]
Hi Sharon,

I think I correctly completed the steps you specified. Now there are conflicts. Is this because I didn't update the code on my local repo before pushing the changes? i.e. I need to make a connection to the upstream repo before this can be merged.

Thanks!

Vanessa

**Comment by redrambles** [comment]
Hey @blackmanvanessa !

Thanks for making that change! The conflicts are totally normal, given that all students are updating the index.html file with their own link - and so it's a matter of time before two links are added to the same line in the same file. No worries! We can address this on our end, but you can take a stab at it too if you like. The process is the same as what you have already completed - you'll want to check out your main branch, fetch from upstream, merge upstream/main into your main branch, then checkout your advice file, merge in your freshly updated main branch and fix the conflicts. 

Once you have, you can then add and commit your changes and push up your advice branch again.

There is one more thing that I would like to see here, though - I see that you are linking to a custom css file from your advice file, but no such file exists as part of your pull request. If you run `git status` - do you see it listed there? If so, you'll want to make sure to add it and commit it so that it can join your pull request. If you have decided to omit the css file, just remove the link that points to it from your advice file, and then add and commit that change - and we're good.

Let me know if you have any qs!

Cheers,
Ann :)

**Comment by blackmanvanessa** [comment]
Hi Ann,

Thanks so much for all the help! I had a go at connecting to the upstream repo and resolving the conflicts as well as adding the css and img file which appeared when I ran the git status command. Please let me know if there is anything else. I'm learning so much!

Take care,
Vanessa

**Comment by redrambles** [comment]
Hey @blackmanvanessa !

We are sooooo close! If you have a look at the index.html file, you'll see that there are a few conflict markers that remain , like `>>>>>>> main`, `===========` and `HEAD <<<<<<<<`. We don't want these to remain in the file, so let's delete them.

Once you have - add and commit your changes and push up your advice branch once more, and we should be all set!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by blackmanvanessa** [comment]
Hi, there!

I think I am lost now. I am getting an error message in my terminal that I can't resolve:

vanessablackman@Vanessas-MBP git-practice % git push origin advice
Enter passphrase for key '/Users/vanessablackman/.ssh/id_rsa': 
To github.com:blackmanvanessa/git-practice.git
 ! [rejected]        advice -> advice (fetch first)
error: failed to push some refs to 'git@github.com:blackmanvanessa/git-practice.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
vanessablackman@Vanessas-MBP git-practice % 

Any ideas?

**Comment by redrambles** [comment]
Hey @blackmanvanessa !

Ok! So this message usually means that either a change was made directly on GitHub - or you pushed to the same repo from another computer / location. Given that you are the only person working on this branch, if you are confident that your local version is where you'd like it to be, you can use a force push:

`git push --force-with-lease origin advice`

And that should go through. Keep us posted!

Cheers,
Ann :)

**Comment by blackmanvanessa** [comment]
Hi Ann,

I actually did delete the conflict markers directly on GitHub (I was just clicking around a doing a little exploring). But then I also changed them locally. 

Either way, I have tried the command listed above and still get the same error message. 

anessablackman@Vanessas-MBP git-practice % git checkout advice
D	advice/rachele-creedon-advice.html
Switched to branch 'advice'
vanessablackman@Vanessas-MBP git-practice % git push --force-with-lease origin advice
Enter passphrase for key '/Users/vanessablackman/.ssh/id_rsa': 
To github.com:blackmanvanessa/git-practice.git
 ! [rejected]        advice -> advice (stale info)
error: failed to push some refs to 'git@github.com:blackmanvanessa/git-practice.git'
vanessablackman@Vanessas-MBP git-practice % 

Any more ideas?

Thanks for your patience!

**Comment by redrambles** [comment]
Hey @blackmanvanessa !

We are getting really close here!! In fact, your pull request would be a-ok if it weren't for the image that it contains. Unfortunately we aren't able to accept any images as part of pull requests because our repo would soon get too large. You are more than welcome to link to an image hosted somewhere on the internet, though - of course! :)

So here's what I suggest:

1) Remove the `img` directory (either by using `rm -r img` in the Terminal or by dragging it to the Trash using the Finder)
2) Make the edit in your advice page so that you aren't linking to that image anymore (again - feel free to link to a hosted image if you like! :))


Once you have made these changes, you'll want to add your changes, commit as per usual and then let's try a 'real' force push with:

`git push -f origin advice`

That should work out - keep us posted!!

Cheers,
Ann :) :)

**Comment by blackmanvanessa** [comment]
Have a look please :-)

**Comment by redrambles** [comment]
Hello @blackmanvanessa !

Ok! So if you have a look a the contents of your pull request here: https://github.com/skillcrush/git-practice/pull/81/files


You will notice a few things:

1) There is no more img folder + file (yay!)
2) There was a student's advice file that was deleted (`advice/rachele-creedon-advice.html`) - oops
3) There is still a conflict marker present in the index.html file on line 93 (`>>>>>>>> main`)


No worries! Let's do the following:

1) Add the student's file back into the advice directory
2) Remove that tiny conflict marker


Once those changes are made, add with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by blackmanvanessa** [comment]
Ok, honestly not sure if I'm doing any of this right anymore, but certainly getting a lot of time practicing git commands in the terminal.

I tried to add the student's file back into the directory by using the git reset command. But I see now that it didn't work. I'm not quite sure how I deleted it in the first place. A search on my computer isn't showing the file anywhere - not even in the trash.

Any tips?

**Comment by redrambles** [comment]
Hey there!

Ok! So let's first begin by making sure that your code is up to date. Make sure you have nothing left to commit in your advice branch (run a 'git status') and when your working directory is clean, move over to the main branch - fetch from upstream, merge upstream/main into your main branch and then move back into your advice branch, and merge in your freshly updated main branch. 

You will have conflicts in the main index.html file - this is 100% normal - just remove the conflict markers, make sure to keep everyone's links, add your files back in `git add -A` - commit as per usual.

Once this is done - we'll pull out the file `advice/rachele-creedon-advice.html` that was accidentally deleted from the main branch: `git checkout main advice/rachele-creedon-advice.html`

Then if you run `git status` - you'll see that this file has been added - so you'll need to commit, and then push up the advice branch once more, which will update this pull request.


Then we should be alllll set!!!

Keep us posted!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @blackmanvanessa,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
