### PR TITLE
Added html advice link

### PR DESCRIPTION
**Pull request by tdw1186**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @tdw1186,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by tdw1186** [comment]
Hi Lisa,

Thanks for your reply.

I’ve gone back and combed through the lessons, specifically retraced my steps in lesson 4 of 6 and I’m completely lost and not quite sure what you mean by adding advice or CSS pages.  I thought I was following the instructions in lessons 4 and 5.

Regards,

T

**Comment by tdw1186** [comment]
Hi Lisa,

Sorry, I continued to work through it and I think I may have solved it.  Please let me know if I added the advice and css files and pushed it through.

Thanks!

T

**Comment by twosavoie** [comment]
Hey @tdw1186,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Comment by tdw1186** [comment]
Hi Lisa,

Brilliant, thanks for your help.


Regards,

T

**Pull request merged**
