### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by reedobrien937**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @reedobrien937,

Great job! We have one small request.

It looks like there's an extra advice.html file in the root of your project folder (in addition to the the one that's in the advice folder.) Once you delete it, you'll run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by reedobrien937** [comment]
Hey @twosavoie, 

Not entirely sure how that happened but I believe that should now be fixed! 

Cheers, 

Reed

**Comment by redrambles** [comment]
Hey @reedobrien937 !

We're getting close but we're not quite there yet. [Have a look at this quick screencast](https://www.loom.com/share/a353450a2a3b4906bf78e31748f14cea) which I hope will help clarify and let us know if you have any questions! :)

Cheers,
Ann :)

**Comment by reedobrien937** [comment]
@redrambles I figured out my issue! When I pushed the file originally I used git push origin "main" instead of "advice. I know it's kind of basic but figuring out even little things like that feels great! I double checked the files changed location and it looks like we should actually be good this time. lol

**Comment by redrambles** [comment]
@reedobrien937,

Beautiful!!



Great work - your code is merge in! 🎉

**Pull request merged**
