### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by AvrgJ0e**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @AvrgJ0e,

This is great! Well done!

We have one small request. There's an extra advice file in the root of your project folder. Can you remove it and then run a slightly different git command (`git add -A`), commit, then push? Your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by AvrgJ0e** [comment]
Good Evening Lisa!
So sorry about that. I am a little lost with this project. I thought it
worked but i had no idea of the extra advice file. Could you help me please
as to correct it? I am trying to get better at github.
Thank you and have a great night!
Joe

**Comment by twosavoie** [comment]
Hi @AvrgJ0e,

Happy to help! Start by checking to see if you're on the **advice** branch by running **git status**. If you control-click or right-click on the extra advice file in the root of the project (not the one in the advice folder), you'll see an option to move it to trash. 

Once the extra file is gone, you can add the changes to staging by running **git add -A** (the capital **A** is important.) Then commit the change by running **git commit -m "your commit message** and push the changes to GitHub. Your push will update your pull request and we'll be able to take a look. 

How does that sound? If you get stuck, can you run **ls** in the command line and send us a screenshot where you ran all of these commands to questions@skillcrush.com? We'll be able to go from there!

Hang in there Joe! You've got this!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @AvrgJ0e,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
