### PR TITLE
added new file, and added link to new file

### PR DESCRIPTION
**Pull request by susankim-art**
Wow, this was hard. This Git class has been the hardest yet.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @susankim-art !

Congrats for working through the class - it's going to be extremely useful to you as a developer, I promise!! And you may learn to love Git with a little time ( I know I did! :) ).

Everything here is looking good except that we need your `susan-kimble-advice2021.html` file to be inside the `advice` directory. Right now it is in the root of the project folder.

Once you move your file inside the advice directory, add your changes with `git add -A` - commit as per usual `git commit -m "Your message here"` and then push up your advice branch once more: `git push origin advice`

This will automatically update this pull request - and then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by susankim-art** [comment]
Good Morning Ann,
Yes, I need help.
The file is in the Advice directory on my computer. It is also in the git-practice directory.
So, I am not sure what to do ?
Thank you 
Susan

**Comment by redrambles** [comment]
Hey @susankim-art !

Ok! I see the file is in the advice directory - but there is a copy of the same file that is in the root of the project folder. Have a look in the root folder - you will see the css directory, the advice directory, the index.html file - the .gitignore file and also a copy of your advice file. Remove the copy of your advice file inside the root of the project directory, and then add and commit the change.

Then push up your `advice` branch and we should be all set! 

Keep us posted!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @susankim-art !

Thanks for making that change, your code is merged in! Yay!!

**Pull request merged**
