### PR TITLE
Added Ashley Hurd advice

### PR DESCRIPTION
**Pull request by ashleyhurd**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ashleyhurd !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by ashleyhurd** [comment]
Hi Ann,

I believe I fixed this issue but I'm not sure. I seem to be having an issue
merging my advice and main branch. But I think I fixed this issue. Can you
check for me or let me know what I'm doing wrong? I'm having a difficulty
learning this part of git. I loved learning HTML and CSS but Git is
something that has been more difficult to wrap my head around.


Thank you!

Ashley Hurd

**Comment by redrambles** [comment]
Hey there!

Ok so we don't have any updated on our end, so there is at least one step that still needs to happen.

Can you try pushing up your advice branch with `git push origin advice` ? Let's go from there!

And no worries, Git takes some getting used to, but with time and practice you will be a pro!! :)

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @ashleyhurd,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
