### PR TITLE
Added link to my advice page

### PR DESCRIPTION
**Pull request by PriyaHaran**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @PriyaHaran,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by PriyaHaran** [comment]
Hi @twosavoie, 

I am a little confused as to what I have done.😅

I have added my advice page, committed and pushed it, however, I think I am having issues with merging the branches... 

I did try several times to add and commit my files but I think I may have too many commits?? In my git log, I have 2 commits that are the same. I tried using the git reset --hard command but for some reason, it won't work. 

On my main branch, it says 'Your branch is ahead of 'origin/main' by 4 commits.' 

I try to use the 'git merge main' command, but a message appears saying 'Found a swap file by the name "~/Documents/my-third-repo/git-practice/.git/.MERGE_MSG.swp".'

I think I have made quite a mess of everything but I am not too sure, I definitely need your help!😫

Thanks a lot,
Priya

**Comment by twosavoie** [comment]
Hi @PriyaHaran,

Thanks for reaching out! Let's move this to questions@skillcrush.com so we can easily exchange screenshots. Can you send us a screenshot of what you see in the command line currently? A swap file is sometimes created when a merge is in process and the Terminal quit accidentally. It's an attempt by Git to preserve what it can. 

By any chance do you have another Terminal window open in your git-practice directory? Are you using the Git integration in VSCode? If so, try quitting those processes. 

Once we're sure where we are in the process, we can remove the swap file and continue with the merge. 

Let us know if you have any questions! 

Best,
Lisa

**Comment by PriyaHaran** [comment]
Hi Lisa,

This is what my command line currently looks like...

I deleted all of my commits to try and start again. I have added and committed my changes but when I try to push it, the message on the bottom shows up. I appreciate all the help!

Priya


________________________________

**Comment by PriyaHaran** [comment]
Also, this is on the main branch, saying I am 3 commits behind...

Thanks,

Priya
________________________________

**Comment by PriyaHaran** [comment]
Hi Lisa,

This is what my command line currently looks like...

I deleted all of my commits to try and start again. I have added and committed my changes but when I try to push it, the message on the bottom shows up. I appreciate all the help!

Priya
________________________________

**Comment by twosavoie** [comment]
Hi @PriyaHaran,

Unfortunately, the images aren't coming through. Could you email them to us at questions@skillcrush.com? We can go from there. 🙂 

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @PriyaHaran,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
