### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by oluchinwigwe**

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @oluchinwigwe !

This is great - there is just a little something we are going to need you to fix before we can merge this in.

If you have a look at your change set here: https://github.com/skillcrush/git-practice/pull/409/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R343 - when you scroll down to the index.html file, you will notice some conflict markers (`>>>>>>> upstream/main`, `=======`, `<<<<<<< HEAD`).

Once those are gone, save the file, add and commit the change and then push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by oluchinwigwe** [comment]
I corrected the conflict in the index.html file. I pushed the changes to github.

**Comment by redrambles** [comment]
Hello @oluchinwigwe !

Hmm I'm not seeing any changes on our end. Are you sure you added and committed first? Running `git status` will help you determine this. Also - remember that you are pushing up your advice branch, so when you're sure everything has been added and committed, you'll want to run `git push origin advice`. 

Let us know how it goes!

Cheers,
Ann :)

**Comment by oluchinwigwe** [comment]
Hi,
I think i fixed it now.
Oluchi.
    On Wednesday, December 1, 2021, 02:05:26 PM CST, Ann Cascarano ***@***.***> wrote:  
 
 


Hello @oluchinwigwe !

Hmm I'm not seeing any changes on our end. Are you sure you added and committed first? Running git status will help you determine this. Also - remember that you are pushing up your advice branch, so when you're sure everything has been added and committed, you'll want to run git push origin advice.

Let us know how it goes!

Cheers,
Ann :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by acodeinprogress** [comment]
Hey @oluchinwigwe,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
