### PR TITLE
Added Eric's advice

### PR DESCRIPTION
**Pull request by eburnett3**
Added Eric's advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @eburnett3 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by eburnett3** [comment]
I went back through the process and I think I might have done it correctly this time. I'm not sure if I'm supposed to merge or have a new pull request.

**Comment by redrambles** [comment]
Hey @eburnett3 ! No need to open up a new pull request, we can keep working with this one. It is tied to your `advice` branch, so any changes you make to that branch and you push up to GitHub will show up here. We're not seeing any changes right now, so did you:
1) Make the change on your advice branch?
2) Push your advice branch up to GitHub? `git push origin advice`

Keep us posted!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @eburnett3 ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
