### PR TITLE
Merged advice branch

### PR DESCRIPTION
**Pull request by cappy1099**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @cappy1099,

This is a great start! 

Just a couple of small changes to make. Could you add your advice file to the advice folder?  And then add a link to the file in the index.html file. Once you've made those changes, save the file, add it with **git add -A**, make your commit as usual, and push up your advice branch once more, which will automatically update this pull request.

Then we'll be all set to merge in your code! Let us know if you have any questions!

Best,
Lisa

**Comment by cappy1099** [comment]
Hi Lisa, I've gone through everything again. I've attached pictures of my
terminal and VS code and the advice folder. I admit I have felt very lost
while learning Git/Github. It's like I'm barely getting through it just to
pass the lessons but I don't completely understand it. I don't want to give
up, however I do feel I could use some live one on one help.
I put the Terminal screen shots in order from top to bottom. I don't know
if they will make sense but please let me know if you have any questions.

Thanks,

Mindy Capanna

**Comment by twosavoie** [comment]
Hi @cappy1099,

Unfortunately the screenshots didn't come through on GitHub. Can you send them to questions@skillcrush.com? We can pick this up there.

You're not alone! Git and GitHub can take some getting used to. The command line just doesn't give us the feedback we're used to from our computers. Have you been to a [Live Q&A](https://learn.skillcrush.com/events/) before? It's a great way to meet with an instructor and other Skillcrushers to talk over any issues you're having in the lesson. You could share your screen and we could dig in to find out what changes could be made. 

I hope that helps. Looking forward to hearing from you. 

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @cappy1099,

Great job! Your advice file is inside of the advice folder - well done! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
