### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by KellyBosman**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @KellyBosman !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by KellyBosman** [comment]
Hi, I tried pushing this again but forgot to update first and now there are conflicts to resolve. I don't want to delete someone else's commits...should i just delete my own and try again later?

**Comment by KellyBosman** [comment]
I tried resolving the conflict but am not sure if I did it correctly and/or if there are additional steps.

**Comment by redrambles** [comment]
Hey @KellyBosman !

Thanks for making those changes, your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
