### PR TITLE
erin cooper advice add

### PR DESCRIPTION
**Pull request by erinncooper**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @erinncooper,

Looks great! I only have 1 tiny request for you.

We would like your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by erinncooper** [comment]
Lisa, 
I think I completed most of the steps and yet do not see the changes here. Please let me know what you think I am doing wrong. Thank you so much! 

Erin Cooper

**Comment by twosavoie** [comment]
Hi @erinncooper!

Great to hear from you! Currently, the advice file is in the root of your project folder. Can you drag and drop it into the advice folder so that it's with the other advice files? (see attached)

Once you've added the file to the advice folder, please add the change with `git add -A` (the capital A is important), commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa
Screenshot 2023-03-22 at 6 09 21 PM (2)

**Review by erinncooper — COMMENTED** [review]
erin cooper advice

**Comment by twosavoie** [comment]
Hi @erinncooper,

Just checking to see if you need any help with this pull request. If you do, let us know!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @erinncooper,

We've all been there! To start over, you'll want to delete the GitHub repo and your local repo. To delete the GitHub repo, go to the repo's Settings and scroll all the way to the bottom to see the delete the repo option. 

Once both are deleted, you can go back to [this lesson](https://learn.skillcrush.com/module-10/start-the-forking-workflow/) and start again. I know it can be frustrating sometimes to start again, but keep going - you've got this!

If you have any questions, let us know! You can email us at questions@skillcrush.com

Best,
Lisa

**Pull request closed without merging**
