### PR TITLE
Added Amber's Advice in index.html

### PR DESCRIPTION
**Pull request by amberlj**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @amberlj !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/amber-leigh-advice.html` file exists as part of this pull request. Perhaps it still need to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by amberlj** [comment]
Hi Ann!

I am trying to add and commit my advice page but it keeps saying that there is nothing to commit, working clean tree. I type git status and it says the same thing. Not sure what I need to put to resolve this. Please let me know when you can. Thank you!!

**Comment by redrambles** [comment]
Hey @amberlj !

Can you show us the result of 'git status'? You can attach an image here if you like. We'll go from there!

**Comment by amberlj** [comment]
Hi Ann!

Here is the image:

Git status

Let me know if you need anything else! Thank you!

**Comment by redrambles** [comment]
Hey @amberlj !

Ok - thanks for that screenshot! Can you try pushing up your branch once more? `git push origin advice` - perhaps the commit just didn't make it over to our side yet. :)

We'll go from there!

Cheers,
Ann :)

**Comment by amberlj** [comment]
Hi Ann!

I put git push origin advice into my command line and this is what my screen shows:

Command line

Not sure if I didn't add something properly or I missed a step? Please let me know when you can. Thank you so much for all of your help thus far!

**Comment by redrambles** [comment]
Hey there! This usually happens as a result of having made a change directly on GitHub (which creates a commit which you then don't have locally) - or if you push to the same branch from another repo on another computer, for example. Given that you are the only person working on this branch, it is safe to force push if you want your local repo to be the definitive history for this branch: `git push -f origin advice` - that should push through your changes.

Keep us posted!

Cheers,
Ann :)

**Comment by amberlj** [comment]
Hi Ann!

I put git push -f origin advice into my command line and I think it went through. I posted a screenshot below. Please let me know if there is anything else I need to do. 

git push -f origin

Thank you for all of your help :)
Amber

**Comment by acodeinprogress** [comment]
Hi @amberlj,

Great! Looks like those changes came through.

Unfortunately, it looks like some merge conflict markers were included in the index.html file. You can see them by looking at the [Files Changed tab](https://github.com/skillcrush/git-practice/pull/53/files) near the top. You'll need to remove the conflict markers before we can get this merged in.

Once you make those changes, you'll need to add, commit and push your work up to GitHub. Your updates will join your pull request here and then we can merge it in.

xoxo,
Sharon

**Comment by amberlj** [comment]
Hi! 

I removed the conflict markers in my index.html. When I go to add, commit and push my work to Github, I'm getting errors again. Not sure what I'm missing. I have a screenshot below of my screen. 

Conflict

Thank you for all of your help so far. :)
Amber

**Comment by amberlj** [comment]
Hi!

I put git push origin advice into my command line and this is what I received: 

git push origin advice

Please let me know when you can. Thank you for all of your help! :)
Amber

**Comment by redrambles** [comment]
Hey @amberlj !

Thanks for the screenshot! Do you remember if you made an edit directly via the GitHub interface? If so - you will need to merge in those changes before you can push up. The steps would be:

`git fetch origin`
`git merge origin/advice`

if any conflicts arise, make sure to fix those up

Then you can add with `git add -A` - commit as per usual and push up your advice branch once more, and you shouldn't have any issues.

Keep us posted!

Cheers,
Ann :)

**Comment by amberlj** [comment]
Hi!

I completed those steps and this is what my screen looks like:
git fetch origin
git merge

I'm not sure if it worked but please let me know if there is anything else that needs to be completed. 

Thank you for all the help! :)
Amber

**Comment by redrambles** [comment]
Perfection!!

Your code is merged in! Yay! :)

Cheers,
Ann :)

**Pull request merged**
