### PR TITLE
Advice Completed

### PR DESCRIPTION
**Pull request by KatherineMarlo**
Hopefully made all the necessary changes!

### CODE REVIEW

**Comment by KatherineMarlo** [comment]
Awesome! Thank you so much! I will get that done now!

**Comment by twosavoie** [comment]
Hi @KatherineMarlo,

Well done removing the link to the image in your CSS file! 

We can still see the img folder with the image. Did you already delete it from your local project folder? If so, when you added the change to staging, did you run **git add -A** ?

If you're not sure, can you run **git add -A** (the capital A is important) again? And then commit the change and push the advice branch to GitHub which will update your pull request.

Let us know if you have any questions!

Best,
Lisa

**Comment by KatherineMarlo** [comment]
Oh, I did not delete the image folder the first time through. Should be deleted and up to date now!

Thank you!

**Comment by redrambles** [comment]
Hey @KatherineMarlo ,

Thanks for making those changes! You did a great job and your code is all merged in! Yay! 🎉

Cheers,
Ann :)

**Pull request merged**
