### PR TITLE
adding advice and main html plus css amanda laughlin

### PR DESCRIPTION
**Pull request by amanda-laughlin**
Adding git-practice files

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @amanda-laughlin,

Looks great! I only have 1 tiny request for you.

We would like for your advice and css files to be in the advice and css folders. If you could move them, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by amanda-laughlin** [comment]
Hi Lisa, when I went to move things around, update, merge, etc I ended up with a conflict I had to fix. I’m not sure why but I had to pick my link or another person’s on the main html index in order to resolve it. I ended up deleting Jenny B’s link and then added and committed. I then pushed that. I didn’t open a new request but I also didn’t end up using the command you told me to. Please let me know if I’ve messed something up that needs to be changed, should submit another pull request, or if you have any idea why adding my link into the list of hundreds at the top would have created a conflict. Thank you so much! -AmandaSent from my iPhoneOn Jan 14, 2023, at 4:50 PM, Lisa Savoie ***@***.***> wrote:﻿
Hey @amanda-laughlin,
Looks great! I only have 1 tiny request for you.
We would like for your advice and css files to be in the advice and css folders. If you could move them, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.
Let us know if you need any help!
xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @amanda-laughlin,

You're super close! Can you add Jenny Buck's link to her advice file in the index.html file? Here's the link you would add: <a href=”advice/jenny-buck-advice.html”>Jenny B’s Advice!</a><br>

The next step would be to move your advice file into the advice folder and your css file into the css folder. 
Screenshot 2023-01-16 at 1 27 44 PM (2)

Once you're finished, can you please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by amanda-laughlin** [comment]
Dear God, Lisa. I don’t know why this has been so problematic. I tried it again but I’m worried. Believe it or not I had actually moved both of those files into their correct folders both times before trying to commit and push but then, after I hear from you, I go back into the directory on my computer and they’re back out again!!!!🫣 I have no idea what’s going on…so many sighs. Thanks for wading through my mess, AmandaSent from my iPhoneOn Jan 16, 2023, at 12:29 PM, Lisa Savoie ***@***.***> wrote:﻿
Hi @amanda-laughlin,
You're super close! Can you add Jenny Buck's link to her advice file in the index.html file? Here's the link you would add: Jenny B’s Advice!
The next step would be to move your advice file into the advice folder and your css file into the css folder.

Once you're finished, can you please add the change with git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.
Then we should be all set to merge in your code. Let us know if you have any questions!
xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @amanda-laughlin,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

If you like, you can send a screenshot of your command line to questions@skillcrush.com and we'll see if we can tell what happened. I wonder if perhaps the change was made and then, before the change was added to staging, if the main branch was checked out? If so, the update could have been lost. It could also be that the main branch was pushed to GitHub instead of the advice branch. 

Either way, you did an excellent job working through the issue. The ability to stay with a problem until it is resolved is super important for a developer. You should feel very proud of yourself! 🙂

xoxo,
Lisa

**Pull request merged**
