### PR TITLE
Added my advice

### PR DESCRIPTION
**Pull request by BossLadyMsTee**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @BossLadyMsTee,

Looks great! I only have 1 tiny request for you.

We would like your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push your advice branch to GitHub. Your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by BossLadyMsTee** [comment]
Hi @twosavoie! Thank you for your feedback. I wanted to provide you with a few screenshots to better understand why my advice will not stay in the advice folder. When I move it to the folder it becomes hidden. 

Screenshot 2024-08-14 122558
Screenshot 2024-08-14 122737
Screenshot 2024-08-14 123231

**Comment by twosavoie** [comment]
Hi @BossLadyMsTee,

Thanks for the screenshots! They are very helpful.

We would like all student advice files to be in the same folder. The second screenshot where your advice file joined the other advice files from other Skillcrush students is what we're looking for. Someone looking for your advice will be able to click on the link you added to the index.html file: `<a href="advice/toncia-c-advice.html">Toncia C's Advice</a><br>`

Does that help? If there's anything we can clarify, let us know! 🙂 

Best,
Lisa

**Comment by BossLadyMsTee** [comment]
Hi @twosavoie. it does clarify things, but I'm not sure what my issue is because I did that step as well. 

Could you explain why my webpage is crossed out next to it, please?
Screenshot 2024-08-14 162214

**Comment by BossLadyMsTee** [comment]
Hi again @twosavoie sorry to bombard you with screenshots, but I noticed my last name did not match the name of my advice file. I updated it, but it's not working.
Screenshot 2024-08-14 220311
Screenshot 2024-08-14 220513

**Comment by twosavoie** [comment]
Hi @BossLadyMsTee,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

When you see a file crossed out in the top part of your text editor it's usually because the file has been moved or renamed. In this case, likely because you moved the file from the root of the project to the advice file. 

Everything looks great in the screenshot of your command line. I wonder if you didn't see changes before because you weren't on the advice branch or if you were and the changes hadn't been added and committed yet. Only committed changes are pushed when you run the `git push` command.

I hope that helps! Let us know if there's anything we can clarify. Congrats again on your first pull request! You did great!

Best,
Lisa

**Pull request merged**
