### PR TITLE
Added Daniel's Advice page as well as a link to view the page 

### PR DESCRIPTION
**Pull request by Dandaman1719**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Dandaman1719 !

This is great - we just need two things before we can go ahead and merge this in.

1) Your `dan-crowe-advice.html` file is in the root of the project folder, but we need it to be inside the `advice` directory. Please move it in there.

2) We need a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you make these updates, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Dandaman1719** [comment]
I'm fairly certain my link to the advice page is at the bottom of the looooooooong list of links. And I will get to moving the file into the correct spot asap
________________________________

**Comment by Dandaman1719** [comment]
I believe I made the necessary changes! Let me know if not! I followed the steps provided from the previous email.

Thanks!
________________________________

**Comment by Dandaman1719** [comment]
Screen Shot 2021-11-18 at 12 19 28 PM

**Comment by redrambles** [comment]
Hey @Dandaman1719 !

Thanks for moving your file into the advice directory - we got that on our end! 

We still don't have the link to your file in the index.html file, however. I see that you have made the change locally - but looks like it still needs to be added and committed and then pushed up. If you run `git status`, do you see your index.html file listed there?

Cheers,
Ann :)

**Comment by Dandaman1719** [comment]
Try it now. I just followed those steps from previous message
________________________________

**Comment by redrambles** [comment]
Hey @Dandaman1719 !

Awesome! Thanks for making that change, your code is merged in! 🎉

**Pull request merged**
