### PR TITLE
Added my name and change file name

### PR DESCRIPTION
**Pull request by Jenn-toribio**
Add to main page

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Jenn-toribio !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Jenn-toribio** [comment]
Which lesson would that be?

**Comment by twosavoie** [comment]
Hi @Jenn-toribio,

Take a look at step 13 of this lesson: https://learn.skillcrush.com/module-10/start-the-forking-workflow/ where you add a link in the index.html, while on the advice branch. 

I hope that helps! Let us know if you have any questions!

xoxo,
Lisa

**Comment by Jenn-toribio** [comment]
https://github.com/skillcrush/git-practice/compare/main...Jenn-toribio:advice
 Is this the link that I am supposed to be using?

**Comment by twosavoie** [comment]
Hi @Jenn-toribio,

In the index.hmtl file, you'll write a link to your advice file that's in the advice folder. You can add it to the other links, writing it the same except using your file name. When you do, just be sure that you're on your advice branch (instead of the main branch.) 

Once you've made that change, add and commit the changes and push to GitHub. It will update the pull request.

Let us know if you have any questions! 

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @Jenn-toribio,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
