### PR TITLE
Added my advice to html doc

### PR DESCRIPTION
**Pull request by JasminRob**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @JasminRob,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by JasminRob** [comment]
Oh bummer. Something went wrong. I have it changed locally. I will try and push it here. I so thought it worked.

**Comment by twosavoie** [comment]
Hi @JasminRob,

You might check to be sure the changes are on the advice branch and that all changes have been saved in your text editor. Next, you can run **git status** to see if there are any changes that need to be added or committed. If so, go ahead and then push your advice branch to GitHub. It will automatically update the Pull Request. 👍 

Let us know if you have any questions! You've got this!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @JasminRob,

Fantastic! We can now see your advice file in the advice folder. The next step would be to remove the extra advice file that's in the root of the directory. 


Once you've made that change, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by JasminRob** [comment]
I THINK that one should be the one that works out. I may have ran my commands in a backward order but we'll see! Thank you for your help

**Comment by twosavoie** [comment]
Hey @JasminRob,

Great job - it's perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
