### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by FatherOSin**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @FatherOSin,

Well done! Your advice file is in the right place and you've linked to it in the index.html file. Perfect!!

It looks like some changes were made to the main.css file. Since this is the same file all students use, we would like you to return the file to the original version. If you would like to write your own CSS for your advice page, that's perfectly fine! You can create your own named css file and link to it in the <head> of your advice file. 

Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @FatherOSin,

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by FatherOSin** [comment]
> Hi @FatherOSin,
> 
> Well done! Your advice file is in the right place and you've linked to it in the index.html file. Perfect!!
> 
> It looks like some changes were made to the main.css file. Since this is the same file all students use, we would like you to return the file to the original version. If you would like to write your own CSS for your advice page, that's perfectly fine! You can create your own named css file and link to it in the of your advice file.
> 
> Let us know if you have any questions!
> 
> Best, Lisa

Apologies for the late reply! I'm not sure how to revert the changes back but I will give it a shot.

**Comment by twosavoie** [comment]
Sounds great @FatherOSin!

You can see the changes to the main.css file [here](https://github.com/skillcrush/git-practice/pull/1316/files#diff-f131fc9dca7d0116bd2258c95e127905bb0db3b922c83db9c7648b32770fc532). 

You have a few different options (first be sure you're on the advice branch):
- Since the file is small, you could make the changes by hand. Have a look at the git diff linked above and change the code back to the red version.
- If you are using VS Code as your text editor, you can use the keyboard shortcut shift + option + f on a Mac or shift + alt + f on Windows to automatically format your code. And VS Code extensions like Prettier will format your code when you save it. Be sure to change the color value in addition to the formatting.
- You could fetch the code from the Skillcrush repo and merge it into your local project (repeating the steps in this lesson.) The formatting and color would be updated. 
- Or you can use the developer tried and true a copy the code from the main.css file in the Skillcrush repo and paste it into your main.css file. 

How does that sound? Once you've made the changes, add and commit them. Then push the advice branch to GitHub. Your pull request will updated automatically. 

And reach out for help if you have any questions! You've got this!!

Best,
Lisa

**Comment by FatherOSin** [comment]
I believe that fixed it!

**Comment by twosavoie** [comment]
Hi @FatherOSin,

Unfortunately, I don't see the update to the main.css file in your pull request or in [your GitHub repo on the advice branch](https://github.com/FatherOSin/git-practice/blob/advice/css/main.css). Can you run `git branch` to be sure you're on the advice branch? Then check to be sure that the changes you've made have been saved in your text editor. In the command line, run `git status` to be sure all changes have been added and committed. If they haven't, go ahead and then push the advice branch to GitHub to update your pull request.

Just in case it helps,[ here's link](https://github.com/skillcrush/git-practice/blob/main/css/main.css) to what the file should look like. The indention is 4 spaces and the background colors are different. If you want to change the colors for your advice page - that's perfectly fine! You can create an additional css file and choose the colors, fonts, etc. you prefer. Then add a link to the file in the <head> of your advice.html file beneath the current link to the main.css file.

I hope that helps! Let us know if there's anything we can clarify!

Best,
Lisa

**Comment by FatherOSin** [comment]
Sorry for the issues with this. I hope that resolved the issue!

**Comment by twosavoie** [comment]
Hi @FatherOSin,

Great job! Well done sticking with it to resolve any issues!! 🙌

Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by FatherOSin** [comment]
Thank you! I feel fairly confident using github but there's definitely some
things I need to review. :)

**Pull request merged**
