### PR TITLE
I added my files! crissy-carlson's.html.advice.html/crissy-carlsons.css

### PR DESCRIPTION
**Pull request by crissynparker**
I hope it looks good! thanks a bunch

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @crissynparker !

This is coming along really nicely! We just have a few requests before we can merge this in.

1) Your advice file is called `crissy-carlson-advice.html.html` - but we only want one `.html` extension. Please rename your file  to `crissy-carlson-advice.html`

2) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you make these changes, add with `git add -A`, commit as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by crissynparker** [comment]
Hello Ann!

Thanks for catching that. I was able to correct those errors!

Sincerely,
Crissy Carlson

**Comment by redrambles** [comment]
Hey Crissy! This is good, but now we have both your correctly named file (yay) AND your incorrectly named file (oops) in the advice directory. Can you delete the `advice/crissy-carlson-advice.html.html` file, then add that change with 
`git add -A` - then commit as per usual and then push up your advice branch once more? That should do it!! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by crissynparker** [comment]
Hello Ann

 ok, ! Its's done! thank you

sincerely,
Crissy Carlson

**Comment by crissynparker** [comment]
Hello Ann

Is there anything else that needs to be done before merging?  

thanks!
Christina Carlson

**Comment by crissynparker** [comment]
thanks, for catching that!

**Comment by redrambles** [comment]
Hey @crissynparker ,

Thanks for making that change, your code is merged in!

Cheers,
Ann :)

**Pull request merged**
