### PR TITLE
Change name

### PR DESCRIPTION
**Pull request by mjlemus6045**
Change name in html file

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @mjlemus6045 !

This is a good start! We need two more things before we can merge this in.

1) Your `manuel-lemus-advice.html` advice file is in the root of the project folder, but we need it to be inside the `advice` folder. Please move it in there.
2) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you make those changes, add them with `git add -A` - commit them as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code! 🎉 

Let us know if you have any questions!

Cheers,
Ann

**Comment by mjlemus6045** [comment]
Here is a screenshot of my advice html inside the Advice folder and the link to the main index.html page. I followed the link directly to the index.html and back again.
<a href="advice/manuel-lemus-advice.html" target="_blank">Manuel L's Advice</a><br>



Sent from Mail for Windows 10

**Comment by mjlemus6045** [comment]
Do I need to make a new pull request or is it just added to the one I made last week?


Sent from Mail for Windows 10

**Comment by redrambles** [comment]
Hey @mjlemus6045 !

Thanks for making those changes - your code is merged in! 🎉

**Comment by mjlemus6045** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Wed, Jul 7, 2021 at 9:36 AM, Ann ***@***.***> wrote:   


Hey @mjlemus6045 !

Thanks for making those changes - your code is merged in! 🎉

**Pull request merged**
