### PR TITLE
Added Alex-N40-advice

### PR DESCRIPTION
**Pull request by Alex-N40**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Alex-N40,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by Alex-N40** [comment]
Hi, thank you! I did add a link in the index.html file to my advice file. It's Alex's Advice, right under Jessica Daniels' Advice. It shows fine when I open the file in browser and the link works as well. Is there anything else I need to do? Thank you!

**Comment by twosavoie** [comment]
Hi @Alex-N40,

Thanks for getting back to us! Unfortunately, I don't see the link to your file in the index.html file on the advice branch. Let's take a closer look!

Can you check to be sure that the change was made on the advice branch? Also, that your code has been saved? Then, in the command line, can you run **git status**? Are there any changes to be added and committed? If so, go ahead and then push as you normally would. Your pull request will update.

If you like, feel free to send us screenshots of your command line after running **git status** and of your text editor to questions@skillcrush.com. We're happy to take a closer look!

xoxo,
Lisa

**Comment by Alex-N40** [comment]
Thank you, Lisa! I sent an email with some screenshots.

**Comment by redrambles** [comment]
Hey @Alex-N40,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by Alex-N40** [comment]
Awesome! Thank you for letting me know!

**Pull request merged**
