### PR TITLE
Added advice in html

### PR DESCRIPTION
**Pull request by jnsteph**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @jnsteph,

Looks great! I only have 1 tiny request for you.

We would like for your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by jnsteph** [comment]
Hi there Lisa,
 Thank you for your email and request.  I feel like this-
[image: image.png]
I am not sure of the advice file & folder that you mean.  Could you help me
out ?
Thanks!
Stephanie

**Comment by jnsteph** [comment]
Hello again,

I have a separate question.  My original desire was to become a UX designer
when I signed up for the courses.  I assumed that I needed to take all of
the development classes before doing the UX unit that I purchased.  Is that
true or can I do the UX classes now?

Thank you!
Stephanie

**Comment by twosavoie** [comment]
Hi @jnsteph,

Sure! You'll want to move the steph-jenson-advice.html file into the advice folder. It will join the other Skillcrushers' advice files. Does that help? 

You can switch to the UX classes whenever you like! And when you're ready, you can switch back.

Let us know if you have any questions!

Best,
Lisa

**Comment by redrambles** [comment]
Hey @jnsteph,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
