### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by shemoy-s**
Added advice link

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @shemoy-s,

Looks great! I only have a couple of tiny requests for you.

We would like for you to include a link to your advice page in the index.html file.  Also, it looks like there are two advice files. One is in the advice folder - which is perfect! The other advice file is in the root of your project. You can go ahead and delete the advice file in the root of your project. After you make those changes, run a slightly different git command (`git add -A`), commit, then push and your changes will join your pull request here.

Let us know if you need any help!

🙂
Lisa

**Comment by shemoy-s** [comment]
Umm how do I do that?

**Comment by twosavoie** [comment]
Hi @shemoy-s,

To delete the extra advice file in the root of your project folder, you can drag it out of the project folder and send it to trash. 

In the index.html file, at the bottom of the file, you would add an anchor tag with the link to your advice page in the href attribute. You can follow the example of the other links in the file. 👍 

When you're finished making these changes, you'll add them to staging by running git add -A, commit the changes and then push and your changes will join your pull request here.

Let us know if you need any help!

🙂
Lisa

**Comment by shemoy-s** [comment]
Okay did I do it right?

**Comment by shemoy-s** [comment]
Done! I think

**Comment by shemoy-s** [comment]
I made the changes and pushed and it says everything is up to date

**Comment by twosavoie** [comment]
Hey @shemoy-s,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
