### PR TITLE
Added Cooper's Advice to file

### PR DESCRIPTION
**Pull request by cooperpulkrabek**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @cooperpulkrabek !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/cooper-pulkrabek-advice.html` file exists as part of this pull request. Perhaps it still need to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by cooperpulkrabek** [comment]
Hello Ann,

Thank you so much. I thought something was off. Added, merged and pushed.
Thanks so much!

**Comment by redrambles** [comment]
Hey @cooperpulkrabek !

Thanks for making those changes, your code is merged in!

Cheers,
Ann :)

**Comment by cooperpulkrabek** [comment]
Hooray! Thank you so much Ann!

**Pull request merged**
