### PR TITLE
Added my advice and name

### PR DESCRIPTION
**Pull request by tiffanymcepeda**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @tiffanymcepeda !

This is a great start! We just need a few more things before we can go ahead and merge this in.

1) Your `tiffany-cepeda-advice.html` file is currently in the root of the project directory - we need it to be in the `advice` directory. Please move it in there.

2) We are missing the link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you move your advice file and add your link in the index.html file, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by tiffanymcepeda** [comment]
Okay, I moved it to the advice root folder instead. I think I fixed it.

**Comment by tiffanymcepeda** [comment]
Hi Ann,

I just fixed the root issue and put it in the advice folder. I am not sure
if the merge worked correctly.

**Comment by redrambles** [comment]
Hello @tiffanymcepeda !

Hmm - the good news is that your advice file isn't in the root of the project folder anymore! 🎉 

The not so great news is that the advice file just isn't in the project at all at the moment. 😅

Do you still see your file locally? Does it show up if you run 'git status' ?

**Comment by twosavoie** [comment]
Hey @tiffanymcepeda,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by tiffanymcepeda** [comment]
Hi Lisa!

I’m sorry this got burried. I don’t recall what lesson this is from. Can
you please let me know what lesson or section this is so I can go back to
work on it?


Thanks,
Tiffany

**Comment by twosavoie** [comment]
Hi @tiffanymceped,

Sure! This is [the lesson](https://learn.skillcrush.com/module-10/finishing-the-forking-workflow/). In case you no longer have the previous email, I'm copying it below. Let us know if you have any questions! 

Best,
Lisa

You wrote:
I just fixed the root issue and put it in the advice folder. I am not sure
if the merge worked correctly.

Ann wrote:
Hmm - the good news is that your advice file isn't in the root of the project folder anymore! 🎉
The not so great news is that the advice file just isn't in the project at all at the moment. 😅
Do you still see your file locally? Does it show up if you run 'git status' ?

**Comment by tiffanymcepeda** [comment]
Thank you!

**Comment by twosavoie** [comment]
Hey @tiffanymcepeda,

Just checking to see if you have any questions. Since we haven't received an updated pull request from you we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
