### PR TITLE
Added Tomi's personal advice

### PR DESCRIPTION
**Pull request by tomie-s**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @tomie-s !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/tomi-salami-advice.html` file exists as part of this pull request. Perhaps it still need to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by tomie-s** [comment]
Hi Ann,

I think I got it right, please can you check to see if you can see my html
file now?
Thanks!

**Comment by redrambles** [comment]
Hey @tomie-s !

We don't have your advice file on our end. Did you push up your advice branch after adding and committing your changes?
`git push origin advice` 

Cheers,
Ann :)

**Comment by tomie-s** [comment]
I merged the advice branch into the main. I can see my advice html on the
repo. Showing the commit as of 1 hour ago.
Do I have to create another 'pull request'?

**Comment by acodeinprogress** [comment]
Hey @tomie-s,

A pull request is specific to the branch that you made it for. In this case, you made a pull request to add your changes from your advice branch to Skillcrush's main branch. Since you made your changes on the main branch of your repo, you have a couple options:

1. You can push up the changes from your advice branch on your computer to the advice branch on GitHub. Those changes will automatically join your pull request here.
2. Or, you can close this pull request and open a new one for your main branch.

xoxo,
Sharon

**Pull request merged**
