### PR TITLE
Added Alana's page of advice

### PR DESCRIPTION
**Pull request by alana-nanz**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @alana-nanz!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by alana-nanz** [comment]
Hi,

I followed all of the steps again. Can you check my pull request again? When I ran through the steps again, I saw my advice page already in the index.html file, so I’m not sure what I’m doing wrong.

Alana

**Comment by twosavoie** [comment]
Hi Alana!

Great to hear from you! We have the advice.html file. The next step would be to add a link to your advice in the index.html file. 👍 

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Lisa

**Comment by alana-nanz** [comment]
I’m not sure what I’m doing wrong. I already did add my link in the index.html file. I’m second from the bottom.

**Comment by redrambles** [comment]
Hello @alana-nanz !

Ok! So it's probably that your index.html file wasn't added and committed - and/or that the commit wasn't pushed up. What is the result of `git status` ? Are you seeing your index.html file listed there?

**Comment by twosavoie** [comment]
Hey @alana-nanz,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
