### PR TITLE
Added Shellies advice

### PR DESCRIPTION
**Pull request by gothkitteh**
And a sparkling STNG quote

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @gothkitteh !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by gothkitteh** [comment]
I am still struggling with this final project.  I am going back through the course to see if I can figure out what I missed first.

Thanks!
Shellie Meeks

**Comment by gothkitteh** [comment]
Hi Ann,
I am trying to get the advice branch to merge and I keep getting this:

***@***.*** git-practice % git remote -v
origin	***@***.***:gothkitteh/git-practice.git (fetch)
origin	***@***.***:gothkitteh/git-practice.git (push)
upstream	***@***.***:skillcrush/git-practice.git (fetch)
upstream	***@***.***:skillcrush/git-practice.git (push)
***@***.*** git-practice % git branch -a
  advice
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/advice
  remotes/origin/main
  remotes/upstream/main
***@***.*** git-practice % git checkout advice
error: Your local changes to the following files would be overwritten by checkout:
	index.html
Please commit your changes or stash them before you switch branches.
Aborting
***@***.*** git-practice %

I am basically stuck at step 8-  on step 7 I keep getting “Already up to date” .  I have saved these files like a million times so I’m not sure what I am doing wrong.

Thanks!
Shellie Meeks

**Comment by redrambles** [comment]
Hello @gothkitteh !

Ok! So this means that there has been a change to the index.html file that was done in the main branch (most likely accidentally - you probably meant to make the change in the advice branch). No worries!

Let's stash those changes for now:

`git stash`

And then try `git status` again - you should see that your working directory is clean. If so, then move over to your advice branch, which should now work without any issues: `git checkout advice`

And then finally pop the stash `git stash pop`. This will put the index.html changes back on your advice branch, which is what we want. Then add the change with `git add -A`, commit `git commit -m "Your message here"` and then push up your advice branch once more `git push origin advice` - and now we should get the update on our end.

Keep us posted!

Cheers,
Ann :)

**Comment by gothkitteh** [comment]
Okay Ann....  I think I did it!!  Please let me know :)
Can you tell me where I can go to learn more about git stash and git stash pop?

Thanks!
Shellie Meeks

**Comment by redrambles** [comment]
Hey @gothkitteh !

Thanks for making those changes!! There were a few remaining merge conflicts in the index.html file (mainly a few duplicate lines of code and some conflict markings, like '>>>>>>' and such) - which can happen easily when doing the sort of maneuvering that we needed to do here - so I resolved them. :) Your code is merged in! 🎉

You can learn more about git stash (and 'git stash pop') here: https://www.atlassian.com/git/tutorials/saving-changes/git-stash

Hope this is helpful, and happy Git-ing!!! :)

**Pull request merged**
