### PR TITLE
Added link

### PR DESCRIPTION
**Pull request by krizelled**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @krizelled,

This is a great start! There are two small changes to make and then we'll be able to merge in your code.

- Could you move the advice.html file into the advice folder?
- Add a link to your advice folder to the index.html file.

Once you fix that up, you can add, commit, and push, and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by krizelled** [comment]
Good morning Lisa,

I may need some help. I don't know why, but it seems to think my advice is
already in the folder? I tried restarting from scratch but I keep getting
prompts that all the things I'm trying to redo already exist. I really
don't know where I went wrong so any points would be greatly appreciated! :)

[image: Screen Shot 2023-06-07 at 8.01.31 AM.png]
[image: Screen Shot 2023-06-07 at 8.02.20 AM.png]
[image: Screen Shot 2023-06-07 at 8.00.44 AM.png]
[image: Screen Shot 2023-06-07 at 8.04.55 AM.png]

Best,
Krizelle

**Comment by twosavoie** [comment]
Hi @krizelled,

Great to hear from you! Unfortunately, you aren't able to upload images in GitHub pull request comments. Could you send those screenshots to questions@skillcrush.com? We'll be able to go from there!

Best,
Lisa

**Comment by krizelled** [comment]
Thank you very much! I was able to get help and I believe it's been updated. I can see it on my end when I look at the advice branch :) Please let me know if you can see the change too!

**Comment by redrambles** [comment]
Hey @krizelled ,

You did a great job and your code is all merged in! Yay! 😎

Cheers,
Ann :)

**Pull request merged**
