### PR TITLE
Added Jess BS Advice

### PR DESCRIPTION
**Pull request by Jlbellsull**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Jlbellsull !

This is amazing, we are nearly ready to go!! We just need to address a few things:

1) Your `jess-bs-advice.html` file is in the root of the project directory, but it should be inside the `advice` directory - please move it in there. :)

2) Once you do, you'll need to fix up the relative link to your css file to reflect the change in location of your HTML file.

Once this is done, add your changes with `git add -A`, the commit as per usual and finally push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. :)

Let us know if you have any questions!


Cheers,
Ann :)

**Comment by Jlbellsull** [comment]
Hi, I've made these corrections but when I go to merge it's saying Everything is up to date.

**Comment by redrambles** [comment]
Hello there!

Ok - no worries - if you added and committed your changes and then fetched from upstream and merged into main and you are getting 'Everything is up to date' - that just means that there haven't been any new merges on the upstream/main branch. That's ok! Just pop back into your advice branch and push up: `git push origin advice` - and your PR will be updated. We can go from there!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hey @Jlbellsull,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
