### PR TITLE
Created Personal Advice Html and CSS

### PR DESCRIPTION
**Pull request by mbarnstien**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @mbarnstien !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by mbarnstien** [comment]
Okay I think I properly added my personal link this time. Please let me know if I did it correctly.

**Comment by redrambles** [comment]
Hey @mbarnstien !

Awesome - we are nearly there! Just two more little details:

1) You are using curly quotes instead of straight quotes around your link in the index.html file. You'll spot the difference if you look closely at your double quotes and the double quotes around the links from the students above you. It's important to use straight quotes as most browsers and computer programs do not properly interpret curly quotes - which ends up breaking things - sigh. :) 

2) Don't forget to add your `target="_blank"` to your link as well, so that it opens up in a new page.

Once these little details are taken care of, save the file, add and commit the change and then push up your `advice` branch once more, which will update your pull request. Then we should be all set.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by mbarnstien** [comment]
Okay I think I corrected everything you listed. Please let me know how it is.

**Comment by redrambles** [comment]
Hey @mbarnstien !

Thanks for making those changes, your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
