### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by learningcoding2022**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @learningcoding2022,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Be sure to spell the file's name in the link precisely the same as the advice file, including capitalization. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by learningcoding2022** [comment]
Okay- I made these changes! Does it look okay to you?

Thanks!!
Molly

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Well done adding a link to your advice file! That's awesome!

One tiny detail to take care of. The name of your advice file is Molly-brown-advice.html (with a capital "M") And the name of the advice file in the link is molly-brown-advice.html (with a lowercase "m")

Can you rename the advice file so it also has a lowercase "m"? 

Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by redrambles** [comment]
Hey @learningcoding2022 !

Just want to hop in here to mention that sometimes it takes a little extra work to make sure Git notices the change in the name of a file - IF the change only involves casing. If you had named it something different, or added a letter or something like this - Git would have noticed right away. But just changing the name from upper to lower case sometimes escapes Git's notice.

What I suggest that you do is use the following (while you are in the root of your project directory, on the command line):

`git mv advice/Molly-brown-advice.html advice/molly-brown-advice.html`

This will make sure that Git notices that a file has been renamed. When you run `git status` afterwards, you will see that the file has been renamed and added - and you just have to proceed to a commit. Once you make your commit, you'll be able to push up this change.

Keep us posted!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @learningcoding2022 !

How are things going? Do you need a hand with this? Let us know!!

Cheers,
Ann :)

**Comment by learningcoding2022** [comment]
Thanks for reaching out! I'm a bit of a gitbash dropout lol 😂 I kept
getting stuck on this and then avoid going back to it! I'll try it again
this week and reach out if I get stuck again.

**Pull request closed without merging**
