### PR TITLE
Added Melissa R's advice

### PR DESCRIPTION
**Pull request by melissariska**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @melissariska,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by melissariska** [comment]
Okay, I tried again. If that didn't work I'm not sure what I'm doing wrong!

**Comment by twosavoie** [comment]
Hi @melissariska,

Let's take a closer look to make sure all of the boxes have been checked. While on the advice branch, can you check that there's a melissa-riska-advice.html in the advice folder? In the command line, run `git status`. Add and commit any changes that are mentioned. Then push the advice branch up to your remote GitHub repo. 

If you have any questions let us know!

🙂
Lisa

**Comment by melissariska** [comment]
Okay, I hope I figured it out...

**Comment by redrambles** [comment]
Hey @melissariska !

Thanks for making those changes! Everything is looking good - your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
