### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by abbeymcmillan**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @abbeymcmillan,

Great job adding your advice and css files! Well done!

It looks like the index.html file is missing from your repo. Could you run `git status` to see if it still needs to be added to staging, committed, and pushed? When you look at your project folder while on the advice branch, do you see an index.html file in the root of the project folder?

If you need any help, let us know! 

Best,
Lisa

**Comment by abbeymcmillan** [comment]
Hi Lisa,

This particular lesson has been so difficult for me. I deleted the index.html file from the git-practice folder because I was having merge issues and some other issues that I thought the index.html was causing. I thought that they files I renamed replaced the index.html and so it wasn’t needed. :(. I really don’t know where to go from here so help is appreciated. I’ve been bugging the Slack group like crazy with this. 

Thank you
Abbey

**Comment by abbeymcmillan** [comment]
To update, I have added the index.html file back from the recycle bin. I have added, committed, and pushed the file in the advice branch. Is the merge step required or the fetch upstream? Also what else do I do at this point?

**Comment by twosavoie** [comment]
Hey @abbeymcmillan,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Just in case it helps, another option would have been to fetch from the upstream Skillcrush repo and merge it into your main branch and then merge main into your advice branch. Or, if the main branch still had the index.html file, you could have merged main into advice without fetching. You would have wanted to be sure your link to your advice file was in the index.html file in the advice branch before pushing to GitHub.

I hope that helps!

Best,
Lisa

**Pull request merged**
