### PR TITLE
Added dianne-c at the bottom of the names

### PR DESCRIPTION
**Pull request by decooper19**
Added my name to the bottom of the branch.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @decooper19,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by decooper19** [comment]
I did add the advice page and did a pull request a few days ago. Not sure
what’s going on with it.

Dianne

**Comment by redrambles** [comment]
Hey @decooper19 !

Ok! So chances are that there is one of two things going on.

1) Perhaps your advice file still needs to be added and committed? Checking git status will help you confirm. 
2) If it has been committed, then we just need to push up again `git push origin advice` - which will have it join your current pull request.

Once we have the file on our end, we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by decooper19** [comment]
Hi, I believe I've done everything correctly. See attached git page and
terminal page.

Thanks!
Dianne

**Comment by decooper19** [comment]
Hi, I wanted to follow up on this.

Thank you,
Dianne

**Comment by acodeinprogress** [comment]
Hi there,

Thanks for following up!

I don't see any files attached to your other message. Will you please email them to questions@skillcrush.com so that we can take a look?

xoxo,
Sharon

**Comment by decooper19** [comment]
Revisited how I added and merged the commits. Hopefully this is correct.

**Comment by redrambles** [comment]
Hey @decooper19 !

Thanks for those changes - your code is merged in!!! 🎉 ✨

**Pull request merged**
