### PR TITLE
Added Natalia advice

### PR DESCRIPTION
**Pull request by nanab210**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @nanab210 !

This is great - the only thing we need is for you to move your `natalia-baptista-advice.html` inside the advice directory (right now it is in the root of the project). When you make that change, you'll want to add it with `git add -A`, then commit as per usual, and finally push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by nanab210** [comment]
Hi @redrambles
I think moved the file to the advice directory now.

**Comment by redrambles** [comment]
Hey @nanab210 !

Hmm - I'm not seeing that change on my end. You made this change on your `advice` branch, correct? Did you remember to add `git add -A`, commit `git commit -m "Your message here"` and then push up the advice branch `git push origin advice` ?

Let us know how that goes!!

Cheers,
Ann :)

**Comment by nanab210** [comment]
Yes @redrambles, that's what I did :/

**Comment by redrambles** [comment]
Hey @nanab210 !

Yay -we are getting closer!!! There are two more things to address and then we'll be good to go.

If you look here, you will see the changes for your PR:
[https://github.com/skillcrush/git-practice/pull/596/files](https://github.com/skillcrush/git-practice/pull/596/files)

1) You'll notice that though your advice file is indeed in the advice folder now (yay!) we still have a copy in the root of the project (oops) - so we'll need to delete that. Make sure that you are inside your `advice` branch when you do this (`git checkout advice`)

2) The index.html file still has some conflict markers that need to be removed. Please remove them and save the file.



Once you have made both of those changes, add them with `git add -A`, commit as per usual `git commit -m "Your message here"` and finally push up your `advice` branch once more: `git push origin advice`

That should do it! Keep us posted!

Cheers,
Ann :)

**Comment by nanab210** [comment]
I don't know what to do with the conflicts 😰, I'm afraid I'm not supposed to delete other people's names from the index file right?

But the copy of my file in the root of the project I was able to remove.

________________________________

**Comment by redrambles** [comment]
Hey @nanab210 !

No worries - we took care of the conflict. Thanks for removing the duplicate file - your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
