### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by bananaroo**
Anna Kongs/bananaroo advice pull request

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @bananaroo,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by bananaroo** [comment]
Alright, Lisa. I believe I've completed another pull request. I am having
the hardest time with this lesson. I think I'll try to jump on a live
meeting some time this week so I can get a little clarity on the merging
process. Hopefully I somehow stumbled into doing it right this time. If
not, I will carry on!

Anna

**Comment by bananaroo** [comment]
Ok, Lisa. I now see my latest commits and my advice and css files. I don't see the conflicts anymore that the bot sees. Do I still need to resolve?

**Comment by twosavoie** [comment]
Hey @bananaroo,

It was great seeing you in the Dev Q&A. The update is perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
