### PR TITLE
I tried to do this a while ago, but it didn't work

### PR DESCRIPTION
**Pull request by Matthias-Snell**
I think it worked this time! If there's something else that I have to do, I'll be happy to make those changes.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Matthias-Snell,

This is great! It looks like you're much more comfortable in the command line! The only thing we need is for you to add a `<br>` tag at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add and commit and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by Matthias-Snell** [comment]
Roger that Lisa! I added the <br> line, so I think we're good to go now.

**Comment by twosavoie** [comment]
Hi @Matthias-Snell,

That's great! 

So sorry I missed this when I reviewed it. This pull request is from your **main** branch, instead of your **advice** branch. If you haven't already, can you merge the main branch into the advice branch? And then push the advice branch to GitHub.

Once the advice branch on GitHub has been updated, you can create a pull request from your advice branch to Skillcrush's main branch. 

Let us know if you have any questions!

Best,
Lisa

**Comment by Matthias-Snell** [comment]
I'm trying; I had an old advice branch that I ended up having to delete, so my current advice branch isn't connected to any remote repos. Let me see if I can find a work-around.

**Comment by Matthias-Snell** [comment]
Oh wait, I think I see what you mean. I think I can figure that out, but it'll probably take a while--for whatever reason, my push/pulls in the command line only seem to be working with the Main GitHub branch.

**Pull request merged**
