### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by PeggyJMatthews**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @PeggyJMatthews !

Ok - so we need to make a few changes to this PR before we can go ahead. You have a `css/peggy-matthews.css` file and a `advice/peggy-matthews-advice.html` in there that we definitely want to keep - but everything else we are going to discard. Many of those changes involve changes to the file permissions, which is unusual (but does sometimes happen in a pull request from a student) - but I'm curious to know what might have let to those changes. If you remember what commands you might have run to make those changes, please let me know - I'm very curious. :)

So! Here's how we are going to fix this up.

First - make sure that you are in your git-practice repository and that you are on your `advice` branch.

Next, let's rewind back in time a few commits. We aren't going to use the '--hard' flag this time because we want to keep some of those changed files.

`git reset 0cd372b`

This is going to take us back to that commit - but leave all the changed files in your working directory. If you run `git status` you will see them all.

Next, we are going to add the files that we want to keep:

`git add advice/peggy-matthews-advice.html`

and

`git add css/peggy-matthews.css`


Now we are going to restore all the remaining file to their previous state, which will fix the permission changes:

`git restore -- .` (There is a space between 'restore' and '--' and again between '--' and '.' )

Once we are good there, if you run `git status` - you should only see a few files that remain, which we don't need at all. Let's go ahead and remove them with this command:

`git clean -f`

Now we are ready to commit:

`git commit -m "Your message here"`

Then please push up your advice branch - it will need to be a force push because we changed history:

`git push -f origin advice`

Let's go from there - and if everything worked out well we can go ahead and wrap this up by adding a line in the main index.html file that will link to your advice file - and we are all done.

Let us know how it goes!

Cheers,
Ann :)

**Comment by PeggyJMatthews** [comment]
So I probably messed this up even more because instead of carefully reading
all of the steps first, I did 2 commits and then later on your instructions
said "we are now ready to commit", So, I have attached a screenshot of
GitBash and hope you can figure out what I need to do. I will be waiting to
hear from you.

**Comment by redrambles** [comment]
Hey @PeggyJMatthews !

This is great, actually - exactly what we need! ✨ 

So now all we need is to add your name to the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by PeggyJMatthews** [comment]
I've attached another screenshot. Is this correct? I will be in your Q&A
meeting today.

**Comment by redrambles** [comment]
Hey @PeggyJMatthews !

Yes - this is 100% perfect!!! Your code is merged in, time to celebrate!

**Comment by PeggyJMatthews** [comment]
Well hallelujah!!! 🎉🎉🎉

**Pull request merged**
