### PR TITLE
Added my own advice page, and a link in the main page

### PR DESCRIPTION
**Pull request by RingyDingy**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @RingyDingy !

Do you need a hand with this?

Cheers,
Ann :)

**Comment by RingyDingy** [comment]
Just pushed the correction, sorry, edited my GitHub notification settings to make it a little more obvious

**Comment by twosavoie** [comment]
Hi @RingyDingy,

Just checking in. It looks like the colin-r-advice.html file isn't inside of the advice directory. Instead, it's in the root of the project folder.

Once you moved it into the advice folder, add the change with git add -A, then commit with git commit -m "Your message here" and finally push up your branch once more git push origin advice which will automatically update this pull request.

Then we should be all set to merge in your code.

Let us know if you have any questions!

xoxo,
Lisa

**Comment by RingyDingy** [comment]
I don't understand, on my end it says I'm up to date so it should have
updated

**Comment by redrambles** [comment]
Hey @RingyDingy !

Ok! A few things might be happening here if you already made the change locally.

1) If you run `git status` - do you see that you have any pending changes? If so, these will need to be added and committed.
2) Are you on the `advice` branch? `git status` would also have confirmed that. If you accidentally made the change on the main branch, let us know and we can walk you through how to change that.
3) Did you push up your advice branch? We are used to pushing up our main branch, but in this case, it's the advice branch that we want to push up: `git push origin advice`

Let us know how this goes!

Cheers,
Ann :)

**Comment by RingyDingy** [comment]
Didn't realize the image I attached to my emailed reply didn't show up here, but I took a screenshot of my git prompt, though your reply headed it off- I did push to the main branch instead of advice (like a dolt)

**Comment by redrambles** [comment]
Hey @RingyDingy !

Ok! So if you like, we can keep corresponding via email at questions@skillcrush.com - where it is easier to share screenshots. I would love to see the following:
`git status`
`git log --oneline -5 main`
`git log --oneline -5 advice`

We'll go from there! :)

Cheers,
Ann :)

**Comment by RingyDingy** [comment]
I was able to remind myself how to roll the main branch back so I've
removed my changes there, I apologize for the headache!

**Comment by redrambles** [comment]
Hey @RingyDingy !

Ok! So if you look at your change set here: https://github.com/skillcrush/git-practice/pull/601/files#diff-4300fe20e0dbac64530e828bb11ff595a260a79b3073bda7478c14f5668b35bd

You'll notice that your advice file is still in the root of the project. 

Let's make sure that we are still in the advice branch first: `git checkout advice`

Move your advice file into the advice directory, add the changes with `git add -A`, commit as per usual, and then push up your advice branch `git push origin advice`

That should do it! Keep us posted.

**Comment by twosavoie** [comment]
Hey @RingyDingy,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
