### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Tyler-Zorb**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Tyler-Zorb!

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/tyler-morton-advice.html` file exists as part of this pull request. Perhaps it still needs to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Tyler-Zorb** [comment]
Hi Ann,

Yes, you were correct and I need to add and commit it first. I tried this
but it doesn't seem to be working? Here's a screenshot to show you what I'm
seeing.
[image: image.png]
Thanks,
Tyler

**Comment by Tyler-Zorb** [comment]
Hi,

I wasn't sure if my last email would get to you with the screenshot or not
so I thought I would forward the email chain you.

Thanks,
Tyler

**Comment by Tyler-Zorb** [comment]
Hi, @redrambles 

I have fixed it and pushed it again so we should be all set this time.

Thanks,
Tyler

**Comment by redrambles** [comment]
Hey @Tyler-Zorb !

We are all set - your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
