### PR TITLE
Kylar's advice added

### PR DESCRIPTION
**Pull request by Kylar-V**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Kylar-V,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by Kylar-V** [comment]
Hey Lisa.

I hope you are well.

Thank you for your feedback.

I thought I had already added the link in the index file, did it not come through ??

All the best
Kylar

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by twosavoie** [comment]
Hi @Kylar-V,

We don't see a link to your advice file yet. (You can see what we see [here](https://github.com/skillcrush/git-practice/pull/1180/files).)

Can you check to be sure you're on the advice branch by running `git branch`? Then that your code is saved. When you open the project in the browser, are you able to click on the link to your advice file and the page comes up. If so - it's looking great! 

In the command line, run `git status`. Are there any changes to be added and committed? If so, go ahead and add, commit, and then push your advice branch to GitHub. Your pull request will be updated automatically. 

Let us know if you have any questions!

Best,
Lisa

**Comment by Kylar-V** [comment]
Hey Lisa.

Thank you for letting me know 😃 I shall get onto fixing that right away thank you.

All the best

Kai

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Kylar-V** [comment]
Hey Lisa. It took a bit of doing but I think I managed to do it I added and commit the change to GitHub so I think it worked is there anything else I needed to do.

Kind regards

Kai

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by twosavoie** [comment]
Hi @Kylar-V,

I'm closing this out for now. Let us know if you have any questions as you reset!

Best,
Lisa

**Pull request closed without merging**
