### PR TITLE
added my name to advice page

### PR DESCRIPTION
**Pull request by Elenakath**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Elenakath !

This is great - we only need two little things before we can merge this in.

1) Your advice file, `elena-ecklund-advice.html` is in the root of the project folder right now - but we want it to be inside of the `advice` folder, with all the other advice files. Please move it in there. :)

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you make those changes, add and commit them and then push your `advice` branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Elenakath** [comment]
Hello,

I believe I have my advice file in the correct folder. I added my link to
the advice list, I can open my advice page and go back to the list but I
can't go from the list to my advice page. I'm not sure why it's not working
in that way.

**Comment by Elenakath** [comment]
I figured it out. It was a written error.

**Comment by twosavoie** [comment]
Hi @Elenakath,

Great job moving your advice file into the advice folder!

You're almost there. Can you:

- Remove the advice file that's in the root of the project folder (not the one in the advice folder)
- Add a link to your advice file to the index.html file

That's it! Once you've made those changes, please add the change with `git add -A`, commit as usual, and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @Elenakath,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
