### PR TITLE
Created new page for Sarah G advice

### PR DESCRIPTION
**Pull request by sarahg714**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @sarahg714,

Looks great! I only have a few tiny requests for you.

Unfortunately, we aren't able to merge in images. The repository would become too large since it's added to by so many students. If you would like to link to an image hosted elsewhere, that's perfectly fine!

Take a look at the path to your css file in your advice file. Can you spot what could be changed about this relative link?

Next, we would like for your advice file to be in the advice folder. When you move it, what change would be made to the link in the index.html file? Also, could you add a <br> tag to the end of the link?

Once you've moved the advice file to the advice folder, run a slightly different git command (`git add -A`), commit, then push; your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by sarahg714** [comment]
Hi Skillcrush,
So I followed Lisa's instructions and deleted the images from my advice file. I then moved my advice file into the advice folder, but I was unclear about adding a link and subsequently a tag to the end of that link? Thanks!

**Comment by twosavoie** [comment]
Hi @sarahg714,

Great question! Once your advice file is in the advice folder, you'll want to update the file path to it in the index.html file to include the advice folder, then the advice file's name. Then, at the end of the link, add a <br> tag. You can use other students' links as a template for how to write the file path and add the <br> tag. But if you have any questions, let us know! 

xoxo,
Lisa

**Comment by sarahg714** [comment]
Hi again!
OK I think I fixed the issue. However I did come across a weird error message in my command line when I tried to sync the updated code from the main branch with my topic branch (see commit 431b12e). I don't quite know what happened there, so hopefully I didn't make things worse!

**Comment by twosavoie** [comment]
Hi @sarahg714,

That's great! It looks like a commit from another student has been merged in since you started, which is perfectly fine. 

The next step would be to make sure the changes have been made locally (removing the images and extra advice file (that's in the root), and updating the link in the index.html file to your advice file in the advice folder.

Once those are complete, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request. (Using **git add -A** will also add that files were deleted to staging.)

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @sarahg714,

Excellent update! You're super close!

Take a look at the index.html file that's in the root of the project folder. To update the link to your advice file, you'll want to add advice/ to the front of the file path. This will tell the server to look for your advice file in the advice folder. 👍 Then add a <br> tag to the end of your link to keep the same formatting as the other links. You can take a look at this page: https://github.com/skillcrush/git-practice/pull/792/files (scroll to the bottom) to compare your link with other students.

Then add, commit, and push your advice branch to GitHub to update this pull request.

Let us know if you have any questions! You've got this!

xoxo,
Lisa

**Comment by sarahg714** [comment]
Thank you Lisa! I see what you mean now. I still need practice on understanding how file paths are inputted when in a different folder. Will keep at it!

**Comment by twosavoie** [comment]
Hey @sarahg714,

Great job! You did fantastic working through the issues until your code was perfect. And your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
