### PR TITLE
Add joy hancock advice and css

### PR DESCRIPTION
**Pull request by joy-hancock**

### CODE REVIEW

**Comment by redrambles** [comment]
@joy-hancock !!!

You have SUCH an amazing thing going on here but we unfortunately cannot accept  images as part of the pull request, as the repo would soon get too large (if all students added images, I mean). :( :( 

Are you able to find these images online and link to their hosted versions instead??

**Comment by joy-hancock** [comment]
Oh no!!!! LOL I've been awol due to work and am just now seeing this.  I made my site into a page here on github, so I'll see if I can figure out how to link it.  I'll try my best!

As you might be able to tell, I got a little carried away...

**Comment by redrambles** [comment]
I love it tho - it's amazing <3

**Comment by redrambles** [comment]
Hey there!

I see you opened up a new pull request - which  I just accepted - so I'm going to close this one. :) Happy coding!

**Pull request closed without merging**
