### PR TITLE
Added abd advice file

### PR DESCRIPTION
**Pull request by Amanda-Deen**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Amanda-Deen,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by Amanda-Deen** [comment]
Thank you I have gone in and fixed the issue. Thank you for bring it to my attention. Amanda Deen

**Comment by twosavoie** [comment]
Hi @Amanda-Deen,

You're super close! It looks like you added a link to your advice file. But removed the link to advice/allison-higa-howerton-advice.html. Once you've added it back in, you can add, commit and push the change which will update your pull request.

Let us know if you have any questions! 

xoxo,
Lisa

**Comment by Amanda-Deen** [comment]
I believe I have fixed the conflict, I am not sure how Allison's file disappeared form my index.html but I think I have fixed the issue. Thanks and please let me know if I still don't have it.
Amanda

**Comment by twosavoie** [comment]
Hi @Amanda-Deen,

Hmmm, I'm not seeing the update. Could you be sure to make the change on the advice branch, add and commit the changes and then push the advice branch to GitHub? Your pull request should be updated automatically.

Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @Amanda-Deen,

Hmmm, I'm not seeing the update. Could you be sure to make the change on the advice branch, add and commit the changes and then push the advice branch to GitHub? Your pull request should be updated automatically.

Let us know if you have any questions!

xoxo,
Lisa

**Comment by Amanda-Deen** [comment]
I just commited and merged the file again

**Comment by Amanda-Deen** [comment]
Lisa,
I have gone in again and fixed the conflicts in GitHub. On Git Bash I show
nothing else that needs to be done for this file. Below are the
screenshots. Please let me know if I'm missing something. Because nothing
is updating automatically and then other people are submitting their advice
and causing me to have a conflict after I have submitted mine. I couldn't
tell you what I'm doing wrong.

Amanda Deen

[image: image.png]
[image: image.png]

**Comment by Amanda-Deen** [comment]
I also just did a git fetch upstream and my advice file showed up on the index.html on line 535 and my abd-advice.html file showed up in the advice folder for the first time. So is this issue fixed???
image
image
image

**Comment by Amanda-Deen** [comment]
I just check the index.html file on github and it is showing different names then the index.html file I just pulled using the git fetch upstream. Why is that??? To be honest I am so sick of this lesson. I don't know why it hasn't gone through the last two times I've tried to merge it.
image

**Pull request closed without merging**
