### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by dreanna-sw**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @dreanna-sw !

This is great - the only thing we need is for you to move your `adreanna-wp-advice.html` file inside the `advice` directory - right now it is in the root of the project.


Once you make that change, add with `git add -A`, commit as per usual and finally push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by dreanna-sw** [comment]
Hello Ann, 

For some reason I had two files, one inside of the advice directory and one in the root directory. I deleted the one in the root directory and added and committed the change. Please let me know if this was done correctly.

Sincerely,

Adreanna

**Comment by redrambles** [comment]
Hey there!

Yes! We are nearly there. We have what we need, but there is another `__MACOSX/._your-name-advice.html` item that joined the pull request which we don't need. Please remove it - then add that change with `git add -A` - then commit as per usual and push up the `advice` branch once more, and we should be all set!


Let us know if you have any questions!

Cheers,
Ann :)

**Comment by dreanna-sw** [comment]
Hello,

I have removed the MacOSX file. 

Sincerely,

Adreanna

**Comment by redrambles** [comment]
Hey @dreanna-sw !

Excellent - thank you for making that change, your code is merged in! :)

Cheers,
Ann :)

**Pull request merged**
