### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Madjidiaw**
Can you please review my pull request when you get a chance. I had to do a hard reset to resent the request as I missed a step the first time around.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Madjidiaw !

Everything looks good here except for one little thing - you are missing a `<br>` tag after your link in the main index.html file. This is necessary so that all links stack vertically. Once you have added that little bit of code, add and commit as per usual and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Madjidiaw** [comment]
Hi Ann,
Thank you, I will update the code by the end of the day.

Best,

Madji

**Comment by redrambles** [comment]
Hey @Madjidiaw !

Thanks so much for making that change, your code is merged in! 🎉

Cheers,
Ann :)

**Comment by Madjidiaw** [comment]
Thank you for letting me know...
Best,
Madji

**Pull request merged**
