### PR TITLE
Edited advice.html content

### PR DESCRIPTION
**Pull request by Dsmndcrry**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Dsmndcrry !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Dsmndcrry** [comment]
Hi Ann,

I was looking for the list and couldn't seem to find it, so I was confused on that part.

Thank you,
Desmond Curry

**Comment by redrambles** [comment]
Hey @Dsmndcrry !

You'll find the list of student links in the index.html file that is in the root of the project folder. This is where you will want to add your own link - and then add and commit your changes, and finally push up your advice branch once more so that we can get your changes on our end.

Let us know if you have any questions!


Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @Dsmndcrry !

Thanks for making those changes, your code is merged in!


Cheers,
Ann :)

**Pull request merged**
