### PR TITLE
Did I do this correctly?

### PR DESCRIPTION
**Pull request by Carbur3**

### CODE REVIEW

**Comment by redrambles** [comment]
Hello there @Carbur3 !

This is great!! We're nearly ready to pull this in - the only thing is that the closing body tag was accidentally removed in the index.html file. You'll see what I mean if you check the changes view: https://github.com/skillcrush/git-practice/pull/943/files

Please pop in that closing body tag, save the file, add add and commit and then push up the branch once more. That will automatically update this pull request and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Carbur3** [comment]
Hi Ann! Thanks for the help!
I made the changes. What is the next step I should take?
Thanks!

**Comment by twosavoie** [comment]
Hey @Carbur3,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by Carbur3** [comment]
Yay! Thanks very much!

**Pull request merged**
