### PR TITLE
Added Tracy's advice link

### PR DESCRIPTION
**Pull request by TracyTuhakaraina**
Added Tracy's advice link

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @TracyTuhakaraina,

Congratulations on making your first pull request!

This is a great start! I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great! Once you do, you can add, commit, and push your code to GitHub. It will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by TracyTuhakaraina** [comment]
Hi @twosavoie, 

Thanks for the feedback. I realised I hadn't pushed the advice branch to GitHub. I think I have resolved that now. Am I on the right track?

Thanks for your help.

Regards,
Tracy

**Comment by twosavoie** [comment]
Hi @TracyTuhakaraina,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

It looks like you created a css file. If you wanted to, you could add a link inside of _your_ advice file, under the link to the main.css file. Then the styles you wrote would take effect. Once the link is added, add and commit the change as you normally would and push your advice branch to GitHub. You would need to issue a new pull request; it would be a good idea to include a short message so that we see that you're updating file that's already been merged in.

Let us know if you have any questions! Congrats again!!

Best,
Lisa

**Comment by TracyTuhakaraina** [comment]
Hi Lisa, 

Yay! My first merge. Feels goooood hehe

I created the CSS file but later decided not to make any changes after all. I'm happy to stick with the default main.css file. Do I have to delete the CSS file and add/commit/push the changes from my advice branch to the hub or can I just delete it on my local?

Cheers,
Tracy

**Comment by twosavoie** [comment]
Hi @TracyTuhakaraina,

Got it! You don't need to make any changes. Leaving your css file in the folder is perfectly fine. 👍 

If you needed to make a change like this in the future on a different project, you would delete your css file locally while on the advice branch. Then add the changes by running `git add -A` (the capital A is important.) Commit as you normally would and push the advice branch to GitHub. Then issue a pull request.

I hope that helps. Congrats again on completing this exercise - it's known to be a challenging one! Keep going - you're doing a great job. 🙂 

Best,
Lisa

**Pull request merged**
