### PR TITLE
Added Hanna P's advice

### PR DESCRIPTION
**Pull request by HannaKP**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @HannaKP,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by HannaKP** [comment]
Hi Lisa,

I am thinking that I may need some help...

I think I was able to add the advice page and css but I am having
trouble merging the branches in order to add, commit, and push them to the
repo.

I am stuck on the STEP 5 OF 6, Finishing the Forking Workflow, step number
9. 9. Merge the freshly updated main branch into the advice branch.

I am not sure what this is asking.  I put in my terminal "git merge
main/advice" and it says that is not something it can merge.

Can you help me understand what command I am supposed to be putting in to
merge the freshly updated main branch into the advice branch? I was able to
merge the upstream branch into the main branch as outlined in step 6 and I
did move over into the advice branch after that to try to merge the main
branch into the advice branch.

Thank you!

-Hanna

**Comment by redrambles** [comment]
Hey there @HannaKP !

This is looking great!!! I see your advice page, your CSS and the link to your advice file in the index.html file, which is exactly what we expect. Looks like you were able to finish this task successfully! :)

To clarify - there are two separate merging steps you take when you are working with this particular Git workflow.

The first is when you want to bring your 'main' branch up to date with the 'main' branch on the upstream repo. In order to do that, you will first move over to your main branch:
`git checkout main` (make sure that you have added and committed any outstanding changes on your advice branch before moving to another branch)
Then you will fetch to get the latest from the upstream remote repository:
`git fetch upstream`
And then merge the main branch from the upstream repo into your local main branch:
`git merge upstream/main`

The reason we need to add the '/' here is because we are merging the main branch from the upstream repo into our current branch (upstream/main) (<remote_repo_name>/<remote_branch_name>)

The second merge operation happens when you then want to merge any changes from your freshly updated local main branch into your topic branch (which we have called 'advice'). In order to do that, you will first move to the advice branch:
`git checkout advice`
Then merge in your local main branch:
`git merge main`

Notice how we don't need a '/' here - we are merging in our main branch from our local repo into our local advice branch, we don't need to specify a remote repo. Does that help clarify?

Keep up the great work - your branch is merged!!! 🎉

**Comment by HannaKP** [comment]
Hi YES! This makes sense!

Thank you!

And just to clarify, was my pull request approved?  Or do i need to open
another one?

Thank you!

**Pull request merged**
