### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by millead**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @millead,

Congratulations on making your first pull request!

This is a great start! I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great! 

Also, take a look at the file path to your advice file. Currently it goes through your computer (Users\happy\Documents) and can't be accessed by a web server. Thanks goodness! You'll want the file path to go directly to the css folder to find the css file. Try comparing your file path with other student's in the index.html file. What change can you make? 

Btw, this comparison is a CS principle called "pattern recognition". As developers, it helps us to build the skill of noticing patterns that we can use in multiple ways. 👍 

Once you make the changes, you can add, commit, and push your advice branch to GitHub. It will join your pull request here and we'll be able to see them.

Let us know if you need any help!

Best,
Lisa

**Comment by millead** [comment]
Thank you for the feedback Lisa.   A. Miller iPhoneOn May 1, 2024, at 10:54 AM, Lisa Savoie ***@***.***> wrote:﻿
Hi @millead,
Congratulations on making your first pull request!
This is a great start! I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great!
Also, take a look at the file path to your advice file. Currently it goes through your computer (Users\happy\Documents) and can't be accessed by a web server. Thanks goodness! You'll want the file path to go directly to the css folder to find the css file. Try comparing your file path with other student's in the index.html file. What change can you make?
Btw, this comparison is a CS principle called "pattern recognition". As developers, it helps us to build the skill of noticing patterns that we can use in multiple ways. 👍
Once you make the changes, you can add, commit, and push your advice branch to GitHub. It will join your pull request here and we'll be able to see them.
Let us know if you need any help!
Best,
Lisa

**Comment by twosavoie** [comment]
Hi @millead,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by millead** [comment]
Hi Lisa,Good morning.  Just wanted to see if you all can now see my advice.html file and the  in GitHub? I attempted to redo the lesson as I think I may have slipped a step previously.  Thank you. A. Miller iPhoneOn May 1, 2024, at 11:52 PM, Lisa Savoie ***@***.***> wrote:﻿
Hi @millead,
Great job! Your code is all merged in.
Best,
Lisa

**Pull request merged**
