### PR TITLE
Changed name on advice page

### PR DESCRIPTION
**Pull request by AirelleM**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @AirelleM !

This is a good start! We just need a few things before we can go ahead and merge this in.

1) Your advice file is named `airelle-mora-advice.html.html` - let's remove the second `.html`. :)
2) In the main index.html file, let's make sure the `href` attribute now points to `airelle-mora-advice.html`, and let's also remove the words `main` and `advice` (conflict markers) that snuck in there - see screenshot:

CleanShot 2023-04-14 at 17 12 43

Once these changes are complete, add them with `git add -A` - commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by AirelleM** [comment]
hey @redrambles, thanks for catching that. I was able to fix the file name, however, I do not see the "+Advice" or "+Main" in my code. Take a look...  
Screenshot 2023-04-18 143802
"
image

**Comment by AirelleM** [comment]
I was able to make the changes. Thaks for the help!

**Comment by twosavoie** [comment]
Hi @AirelleM,

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @AirelleM,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
