### PR TITLE
Abby Mill's advice

### PR DESCRIPTION
**Pull request by Abby-Mill**
Added a page and advice

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Abby-Mill,

This is a great start! There are a couple of quick changes we would like you to make. 

Start by checking to be sure you're on the advice branch by running **git status**. This command will tell you which branch you're on and if there are any changes to be added and committed before moving forward. If you aren't on the advice branch, go ahead and check it out. 

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes to GitHub. 

One other note - this pull request is from your main branch. Could you instead issue a pull request from your advice branch? Once we receive it, we'll review the updates. 👍 

Reach out if you have any questions! You've got this!

Best,
Lisa

**Comment by Abby-Mill** [comment]
I think I was able to move that to the advice branch. Thank you for your help

**Comment by twosavoie** [comment]
Hi @Abby-Mill,

That's great! The next step would be to issue a pull request from the advice branch (this pull request is from the main branch.) 

Just in case it helps, after clicking on "Pull Request", click on "New Pull Request" and you'll see the option to compare branches. New to the repo's name, you'll see a dropdown that shows "compare: main". If you click on the dropdown, you can choose "advice" instead. 

Let us know if you have any questions! 

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Abby-Mill,

Hope you're doing well. Since this pull request is from the main branch, I'm going to go ahead and close it. When you're ready you can create a pull request from your advice branch and we'll take a look. 

If you have any questions, let us know!

Best,
Lisa

**Pull request closed without merging**
