### PR TITLE
some init msg

### PR DESCRIPTION
**Pull request by carocancode**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @carocancode !

This is good! The only thing we need to change is the placement of your advice file. Right now it is at `advice/Carolina-Rodriguez-advice.html/Carolina-Rodriguez-advice.html` - which means your `Carolina-Rodriguez-advice.html` file is inside another directory called `Carolina-Rodriguez-advice.html`, which is inside the `advice` directory. We need it to be directly inside the advice directory. 

Once you have moved your file into `advice/` and deleted the nested `Carolina-Rodriguez-advice.html` directory - add your changes with `git add -A`, commit as per usual and push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by carocancode** [comment]
Hi,

I moved the file to the advice folder but I cannot update it on the command
line. I attached my changes. I guess I was trying to do the upstream but I
received a merging conflict error. I went back to the index.html and
updated the file. I am lost on what to do next.

**Comment by redrambles** [comment]
Hey there! 

So in your latest update, we no longer have a file path issue (yay!) but we also no longer have your advice page (oh no). Do you still have it locally? What is the result of `git status` ?

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @carocancode ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
