### PR TITLE
 Added link to advice page for Michael Gaymon

### PR DESCRIPTION
**Pull request by djzsmk**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @djzsmk,

Looks great! I only have 1 tiny request for you.

We would like your advice file to be in the advice folder. Also, could you rename the file leaving off the your-name-advice.html? If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by djzsmk** [comment]
Okay, should be updated

**Comment by twosavoie** [comment]
Hi @djzsmk,

This is a great update! Only one small change to make. Now that your advice file has been added to the advice folder, could you delete the advice file that's in the root of the project? 

Once the file has been deleted, please add the change with `git add -A`, commit as per usual, and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @djzsmk, 

It looks like the index.html file has been deleted. Could you restore it and instead delete the michael-gaymon-advice.html/michael-gaymon-advice.html file that is in the root of your project folder (keeping the file that is in the advice folder.)

Once the index file has been restored and the extra advice file has been deleted, please add the change with git add -A, commit as per usual, and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by djzsmk** [comment]
should be updated. Just for my general knowldege, does having the file on my end cause an error of some sort

**Comment by twosavoie** [comment]
Hey @djzsmk,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Excellent question! It's perfectly fine to have any extra files in a branch you aren't using for a pull request. Having extra files in the branch you're issuing the pull request from means that, when it's merged, it becomes part of the Skillcrush repo. And in this project, we have all the advice files in the advice folder. Does that answer your question? 

xoxo,
Lisa

**Pull request merged**
