### PR TITLE
Added Simi's advice

### PR DESCRIPTION
**Pull request by simisinghsmith**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey  @simisinghsmith,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by simisinghsmith** [comment]
Hi @twosavoie 

I thought I did add the advice page and css but apparently I didn't but I'm unsure where I went wrong. Could I have some help with that?

Thank you,
Simi

**Comment by twosavoie** [comment]
Hi @simisinghsmith,

Let's take a closer look. Do you see you advice file inside of the advice folder (while on the advice branch)? Can you check to be sure your code is saved? Then run **git status** which will show if there are any changes that need to be added and committed. If so, go ahead and add, commit and push your changes to GitHub. Your pull request will be updated automatically. 🙂 

Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @simisinghsmith,

Just checking in to see if you have any questions or need help with the lesson. Just let us know!

🙂
Lisa

**Comment by twosavoie** [comment]
Hey @simisinghsmith,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
