### PR TITLE
Ariel's Advice

### PR DESCRIPTION
**Pull request by ArielSchwalb**
Hi I think this was moved or deleted. Can we add it back in? Thanks!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ArielSchwalb !

This is great - we just need two more things before we can go ahead and merge this in.

1) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

2) Your advice file, `ariel-schwalb-advice.html` - is in the root of the project folder, but we need it to be inside the `advice` folder. Please move it in there. 

Once you have made these changes, add with `git add -A`,  commit as per usual  and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by ArielSchwalb** [comment]
Hi Ann,

Thank you so much! I fixed those mistakes and also styled the css. :)

So I tried to push it but I wasn't able to push it up. It said that the
remote repository was not found. Can you take a look at my
screenshot below? I know that I know my password, so I think that there is
probably a different issue.

Thank you,

Ariel

**Comment by ArielSchwalb** [comment]
-- Please reply above this line --


            Hi Ariel!

I hope it's ok for me to jump in here! Could you try running GIT PUSH
ORIGIN MAIN if you're pushing to the main branch or GIT PUSH ORIGIN
ADVICE if you're pushing to the advice branch? If you still aren't
able to push, can you run GIT REMOTE -V (which lists all of the remote
repos linked to your directory) and send us a screenshot of the
result? 

🙂
Lisa
--
Lisa Savoie
Skillcrush

DID WE MAKE IT EASY FOR YOU TO GET THE HELP OR INFORMATION YOU NEEDED?

**Comment by ArielSchwalb** [comment]
Sure! Here is a screenshot. Thanks. :)

**Comment by ArielSchwalb** [comment]
-- Please reply above this line --


            Hey there!

Ok - thanks for the screenshot! So it seems as though the forked copy
of Skillcrush's repo no longer exists on your GitHub profile, which is
why you are getting the 'repository not found' feedback in the
Terminal. I would recommend that you fork it again by visiting it
here: https://github.com/skillcrush/git-practice [1] and then hitting
that 'fork' button on the top right hand side. Once you do, you will
be brought back to your GitHub profile where you will now have a
forked copy of the git-practice repository. The address that you have
mapped to the 'origin' remote name (which we could see when you ran
'git remote -v') - should still be good. Try pushing up again, 'git
push origin main' - and see if you are successful.

Keep us posted!

Cheers,
Ann :)



Links:
------
[1] https://github.com/skillcrush/git-practice

--
Ann @skillcrush
Skillcrush

DID WE MAKE IT EASY FOR YOU TO GET THE HELP OR INFORMATION YOU NEEDED?

**Comment by acodeinprogress** [comment]
Hi @ArielSchwalb,

I see that you've been emailing about this pull request.

Ann suggested closing this pull request and creating a new one. Would you like me to go ahead and close this one for you?

xoxo,
Sharon

**Comment by ArielSchwalb** [comment]
Hi! I think I managed to do the pull request on my own. It looks like it is
up and running. Here it is:
https://github.com/ArielSchwalb/git-practice

Thank you so much for your help!!!

**Pull request closed without merging**
