### PR TITLE
Advice Page - Requesting Pull Request

### PR DESCRIPTION
**Pull request by Cascades451**
Earlier this week I was having some difficulty with this step and reached out to the instructor team. Sharon Siegel wrote back saying it didn't look like I had made any changes, which was a great tip.  Oopsy!  Sharon - you were 100% correct. I had forgotten to add and commit the changes, which I have now done and can make this pull request.
Thanks again SkillCrushing Team - you all are the best!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Cascades451,

Congratulations on making your first pull request!

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Cascades451** [comment]
Hi Sharon,

Thanks again.  I guess I need more practice in remembering to add and
commit changes!  Thank you.  I've titled my file on the index.html as 'C
Forest's Do As I Say, Not As I Do Advice respectively'!. I've also changed
the css a little bit too.

thank you!

**Comment by redrambles** [comment]
Hey @Cascades451 !

Awesome!! We didn't get any changes on our end - so do you still need to push up those changes? Don't forget you'll want to push up to your advice branch: `git push origin advice`

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Cascades451** [comment]
Hi Ann,

Thanks for helping me out with this one.  Did you get those changes?  if
not, I must be doing something wrong and will need to start from scratch :(
to pinpoint where I'm messing up.  boo.

Have a nice weekend either way -

Best,
Verite

**Comment by redrambles** [comment]
Hey @Cascades451 !

We didn't get any changes on our end, but no need to start over! What is the result of `git status`?

Cheers,
Ann :)

**Comment by Cascades451** [comment]
Hello Ann,
I am so confused now :(. This is what it says for git status. Also I understand that there is a conflict but how do I resolve it without deleting someone else's work?

thepentacle@Verites-iMac git-practice % git status
On branch main
Your branch is ahead of 'origin/main' by 218 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    css/aileen-cm.css
	deleted:    css/main.css

no changes added to commit (use "git add" and/or "git commit -a")
thepentacle@Verites-iMac git-practice %

**Comment by redrambles** [comment]
Hey @Cascades451 !

Ok - given that it's been a little while and this your code is behind quite a few commits - this is what I suggest that we do.

1) Open up your Finder and locate your advice file from inside this folder and then pull it over to the Desktop temporarily.
2) It doesn't look as though you have created a custom css file (which is fine ) but if you have, make sure to pull that one over to the Desktop too.
3) In the Terminal, update your upstream remove by running:
`git fetch upstream`
4) Still in your advice branch, let's move our branch to the same commit that is the most recent one on the upstream branch: `git reset --hard upstream/main`
5) Now your code is totally up to date! Move your advice file from the desktop back into your project - and make sure to put it inside the advice folder. 
6) If you had a custom css file - move it into the css folder.
7) Open up the index.html file and add a link to your advice file at the bottom of the list (you had added it before, but when we ran the reset, that would have removed your line).
8) Add everything with `git add -A` - and then commit as per usual `git commit -m "Your message here"` and then finally push up your advice branch once more `git push origin advice`


Now we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Cascades451** [comment]
Hello Ann,

Ok - I've followed this step by step and fingers crossed it works.
I added a css style sheet (admittedly copied from another student! !- not
plagiarism.  It is for lack of time).

Thank you so much for your help and please let me know if we're good to go?

Best.Verite

**Comment by Cascades451** [comment]
PS: only *partially* copied from another student - not fully. I did do my
own work too!

**Comment by acodeinprogress** [comment]
Hey @Cascades451,

You're almost there!

It looks like you deleted a few CSS files in the process. You can see them in red by looking at the [Files Changed tab](https://github.com/skillcrush/git-practice/pull/105/files) near the top of the page.

You'll need to restore those files, then run `git add -A`, commit, and push.

Then we should be able to get this merged in.

xoxo,
Sharon

**Comment by Cascades451** [comment]
Thank you Sharon -

But how do I restore those files? Also, this is exactly what I was
concerned about in the first place, deleting those files to resolve the
merge conflict.

I'm really confused as to what in the heck has gone so wrong here...?
Please advise on how I proceed.

thank you
Verite

**Comment by redrambles** [comment]
Hey there @Cascades451 !

Ok so first - no worries about borrowing some CSS from another student - that is 100% ok! You don't even need to add your own CSS to this project if you don't want to.

As for how to proceed at this point - can you try pushing up with this command: `git push -f origin advice`

And then letting us know how that went? We'll go from there!

I'm also happy to walk through this with you Friday during Q&A if you would like us to do this 'live'. You can register by hitting the 'Live Q&A Sessions' item in the left sidebar on your Skillcrush dashboard, and choosing development q&a sessions.

**Comment by Cascades451** [comment]
hi ann,

Thanks so much for getting back to me. I hope to pick this up as soon as
possible. I won't be able to make the live Q&A today because we are
euthanizing our dog :(
When is the next available session please- I would like to attend.

Thankyou
Verite (@Cascades451)

**Comment by redrambles** [comment]
Hey @Cascades451 !

Oh no, I am so sorry to hear that. :( :( :( 

You can pop in on any of the dev Q&A events that you can find under the 'Live Q&A sessions' tab in the left sidebar of your Skillcrush dashboard. Just make sure to choose 'Development Q&A' and then if you select 'Any available' you'll be presented with the most options to choose from, in terms of day / time.

Hope this helps and see you then.

Cheers,
Ann :)

**Comment by Cascades451** [comment]
Yes, that’s great, I’ll check it out. I hope to get some more modules done over the summer. Looking forward to getting back in the saddle. 

Thanks Ann.

**Comment by redrambles** [comment]
Hey @Cascades451 ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
