### PR TITLE
Added advice link to index.html

### PR DESCRIPTION
**Pull request by marina-111**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @marina-111,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by marina-111** [comment]
Hi Lisa, 

Many thanks for your email. 

On which repo, please? I can see the css folder for Rogue Pickings, but not sure if that is the one you are refering to. 

Thank you,
Marina 


    On Monday, 30 January 2023 at 06:04:45 GMT, Lisa Savoie ***@***.***> wrote:  
 
 


Hey @marina-111,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @marina-111,

Great to hear from you! this is for the git-practice repo from this lesson: https://learn.skillcrush.com/module-10/finishing-the-forking-workflow/

I hope that helps. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @marina-111,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
