### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by rob17204**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @rob17204,

Great job! The advice file is just where it should be. And well done adding your own CSS!

Next, take a look at the index.html file. It looks like there are some conflict markers remaining. Once you remove them, you can add, commit, and push your work and it will join your pull request here. If you would like, take a look at the index.html file on this page: https://github.com/skillcrush/git-practice/pull/800/files.

Let us know if you need any help!

xoxo,
Lisa

**Comment by rob17204** [comment]
Hi Lisa. Thanks for pointing out the conflicts. 
Do I resubmit the pull request at this point again? 
Thanks, Rob

**Comment by rob17204** [comment]
Hi Ann, 
Red and green challenged, I’m not sure what I am looking at on the side bar at some points, is there a way for me to change those color markers?  Yellow and red? Or something?  Thanks in advance,
Rob

**Comment by twosavoie** [comment]
Hi @rob17204,

Unfortunately, GitHub has chosen red and green. In your text editor, I don't know whether this will help, but there is a theme for color blind people you might try: https://marketplace.visualstudio.com/items?itemName=PedroFonsecaDEV.dark-plus-colorblind. 

In the meantime, the arrows point one way for your existing code and the other way for the incoming code. You might take a look back at the video Ann created for the Merge Conflict lesson: https://learn.skillcrush.com/module-8/tackling-merge-conflicts/. There may be some other visual clues that would help.

It looks like you were able to remove the conflict markers which is great! One small change to make, check that the opening <section> tag is before the list of links (and after the <header> tag) and the closing </section> tag is after all of the links (and before the closing </body> tag). You can check the Skillcrush repo your code would be merged into to see if you have everything in the right place: https://github.com/skillcrush/git-practice/blob/main/index.html

Let us know if you have any questions! You've got this! 

xoxo,
Lisa

**Comment by rob17204** [comment]
Thanks for the hints. Much appreciated.  I typically find ways to adapt, but this part is stumping me,  only because it’s been a while since I have used it.  Haha.  
Rob

**Review by rob17204 — COMMENTED** [review]
It appears that I have all the conflicts resolved, and now I have done so many things trying to resolve, confusion is really set in.  Do I push again?  When i push from the desktop, it states there are conflicts, I pull on desktop and it says it is current.  I think I am going to put it up for the day and try another time.  Thanks Lisa !  :)

**Comment by twosavoie** [comment]
Hi @rob17204,

Let's take a closer look! Can you send a screenshot of what you see in the command line to questions@skillcrush.com? (It will make it easier to exchange screenshots if we need to.) 

We'll be able to go from there!

xoxo,
Lisa

**Review by rob17204 — COMMENTED** [review]
It appears that I have the issues corrected at this point and my branch is ready to merge

**Comment by rob17204** [comment]
At this point i really have no idea what I am doing.  I have fetched, pulled and changed, pushed and merged and I still recieve that I have conflicts.  The changes that I make locally never show up in git even after pushing.  Now Git say's no conflicts, but I really dont have any idea.  Is this how real dev's have to deal with all this?  It seems like devs spend all their time trying to push their updates and continually have to pull and edit and submit with never getting their changes merged. hmmm.

**Comment by twosavoie** [comment]
Hey @rob17204,

Great job! Well done moving the <section></section> tags. Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

I hope you were able to find a theme that works for you!

xoxo,
Lisa

**Comment by rob17204** [comment]
Thanks Lisa, 

I was getting stumped.  Whew!! That was a lot more complex than i recall from when I started it fresh 3 years ago. Could it be, that it was a bit more challenging because I used the repo I branched 3 years ago?  I am sort of wishing that I had deleted it and started fresh, but I have to figure, that in the real world, my recent experience would probably apply more similar to real life experience. 

As per the color blind themes, I am trying a different theme.  We had to have discovered them at the same time. Haha.  

This morning, I was considering not using the dark mode to see if it helps me delineate between the colors if I still have a hard time, since I see that they are not 100% opaque, the black coming through may be hindering my ability to distinguish.

All the help and patience is much appreciated Lisa.  I look forward to the Mentor meeting with you on this upcoming Saturday.  

Rob Schuster.

**Pull request merged**
