### PR TITLE
Added new background color and a new image.

### PR DESCRIPTION
**Pull request by Samantha-N**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Samantha-N !

This is a great start! There are just a few things we need to address before we can merge this in.


1) The link to your CSS file needs to be relative, so that it can work on any environment, as opposed to just on your computer. By linking your file this way `C:\Users\saman\OneDrive\Documents\git-practice\css\samantha-n.css` - it will only work on your computer. By using a relative link, your file path will be this: `../css/samantha-n.css` - and that will work anywhere. Have a look at how your peers linked to their css files by sneaking a peak at their advice files - and also check out this [FAQ](https://faqs.skillcrush.com/article/238-relative-vs-absolute-urls) for more info.

2) We still need a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you have made the change to your advice file's css link and have added your link to the index.html file, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Samantha-N** [comment]
Hello Ann,

I made the recommended changes; however, I'm having some issues that I don't know how to fix. Here is the message I am receiving when I try to push the advice branch to my repo. 

 ! [rejected]        advice -> advice (non-fast-forward)
error: failed to push some refs to 'github.com:Samantha-N/git-practice.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Any help would be greatly appreciated,

Samantha

**Comment by redrambles** [comment]
Hey @Samantha-N !

This means that something was edited on the advice branch on GitHub which isn't present on your local copy of the branch. Usually this happens because an edit was made directly on GitHub. Because you are the only person working on your advice branch, you can do a force push without having to worry that you are going to mess with history for any other developers:

`git push -f origin advice`

And that should go through and update your pull request. Keep us posted!


Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @Samantha-N !

I accepted your other pull request, so I'm going to close this one. :)

**Pull request closed without merging**
