### PR TITLE
Made changes 

### PR DESCRIPTION
**Pull request by Samantha-N**
Hello!

I changed the link to my css file to be a relative link as well as added my advice link to the index.html.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Samantha-N !

Everything is looking good here except that the `.gitignore` file was accidentally deleted. Oops! Let's add that file back. You can either copy the contents from GitHub, create a new .gitignore file locally and paste in the contents - or you can grab it from the upstream repository:

`git checkout upstream/main .gitignore`

That will pop the .gitignore file as it is on the upstream repo back into your local repository, and then you can add it back in, commit and push once more. 


Then we should be all set to merge in your code. Let us know how it goes!


Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Samantha-N,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by redrambles** [comment]
Reopening this after chatting with Samantha! ❤️

**Comment by redrambles** [comment]
Hey @Samantha-N ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
