### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Matt29999**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Matt29999, 

Looks great! I only have a couple of tiny requests for you.

For the link to your advice file, can you change the file name from mat-lamb-advice.html to matt-lamb-advice.html?

Next, we would like your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Matt29999!

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Matt29999,

Happy to help! 

There's a small typo in the advice file. Can you change the file name from **mat-lamb-advice.html** to **matt-lamb-advice.html**?

Next, we would like your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

How does that sound? Let us know if you have any questions!

Best,
Lisa

**Comment by Matt29999** [comment]
I don’t think this went through properly, what did I do wrong.
***@***.***
***@***.***


















From: Lisa Savoie ***@***.***>
Date: Wednesday, March 8, 2023 at 10:58 PM
To: skillcrush/git-practice ***@***.***>
Cc: Matt Lamb ***@***.***>, Mention ***@***.***>
Subject: Re: [skillcrush/git-practice] Advice (PR #939)

Hi @Matt29999<https://github.com/Matt29999>,

Happy to help!

There's a small typo in the advice file. Can you change the file name from mat-lamb-advice.html to matt-lamb-advice.html?

Next, we would like your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (git add -A), commit, then push, your changes will join your pull request here.

How does that sound? Let us know if you have any questions!

Best,
Lisa

**Comment by Matt29999** [comment]
Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by twosavoie** [comment]
Hey @Matt29999,

It has been a while since we've heard from you, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
