### PR TITLE
Added Judy's advice

### PR DESCRIPTION
**Pull request by judy-b**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @judy-b,

This is great! The only thing we need is for you to add a <br> at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add and commit and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @judy-b,

It looks like the tag isn't showing up in the message. Could you add a `<br>` tag at the end of your link in the index.html file?  

If you have any questions, let us know!

Best,
Lisa

**Comment by judy-b** [comment]
Hi @twosavoie,

Thanks for your help. I added the <br> tag. Let me know if there's anything else I need to do.

Thanks,
Judy

**Comment by twosavoie** [comment]
Hey @judy-b,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
