### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by lesliemariemac**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @lesliemariemac,

Great job! You're super close!

The spelling of your advice file's name in the index.html file doesn't match the file's name. This wouldn't have caused an issue locally because our local environments are much more forgiving than a web server is. On a live site, the link would break.

Can you change the link in the index.html file to read **advice/Leslie-MacNabb-advice.html** (with capital letters L, M, and N)? Once you've made that change,  and added and committed the change, you can push your advice branch to GitHub. Your pull request will automatically update. 

Let us know if you have any questions. You're doing great and you're almost there!

Best,
Lisa

**Comment by lesliemariemac** [comment]
Am I changing this in VSCode, on the command line or somewhere else? I'm
not seeing it listed lowercase anywhere.
[image: Screen Shot 2023-07-18 at 5.24.20 PM.png]
[image: Screen Shot 2023-07-18 at 5.24.43 PM.png]

**Comment by lesliemariemac** [comment]
I may have figured it out, but I don't see it updated in my GitHub yet
[image: Screen Shot 2023-07-18 at 5.39.45 PM.png]
[image: Screen Shot 2023-07-18 at 5.37.48 PM.png]

**Comment by lesliemariemac** [comment]
[image: Screen Shot 2023-07-18 at 5.51.59 PM.png]

Success!!! I think!!!!!

**Comment by twosavoie** [comment]
Hi @lesliemariemac,

Perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
