### PR TITLE
added my advice file

### PR DESCRIPTION
**Pull request by bobbyc123x**
added advice file

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @bobbyc123x,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by bobbyc123x** [comment]
Hi, yes I did add it and did my QA on it..its getting over to github on the
final steps that are giving me problems..I  have experience writing tech
doc..that needs work! Thnx

**Comment by twosavoie** [comment]
Hi @bobbyc123x, 

Let's take a closer look! 

While in the advice branch, can you run **git status** to be sure that all changes have been added and committed? If there's anything that hasn't been added and committed, go ahead. 

Then take a look at the advice folder. Do you see your file listed? 

If the file is in the advice folder and all changes have been added and committed, you can run **git push origin advice** and the pull request will be updated. 

If you could send us a screenshot of your command line where you ran the commands and one of where you see your file in the advice folder to questions@skillcrush.com, we can help you troubleshoot. 

Let us know if you have any questions!

🙂
Lisa

**Comment by bobbyc123x** [comment]
Hi Lisa,
trying to fully understand the team workflow because I feel this piece is
crucial to working with others.
First I made another change to the index html file adding thd  color red. I
want  to make sure it went over to github properly. So basically I am
repeating the last two steps in the start the forking workflow process.
 Would you please make sure that is the case.  THNX

On steps 4 of 6 ----  starting workflow ------ with regard to the following
statements


   1. Navigate back to your command line to add and commit your changes.  *Does
   this step need to be done within the advice branch or master branch???*
   2. Push the changes on your branch to your repo: git push origin advice.
   *Does this step need to be done within the advice branch or master
   branch?? Further, does this push move it to the origin(main) I forked or
   does it move it to the advice branch I created.  I am getting confused with
   what branch things are going to when doing a push       **Once this is
   reviewed I will continue on to the finishing workflow.  thnx!*

**Comment by twosavoie** [comment]
Hi @bobbyc123x,

Great to hear from you! 

- You'll want all changes on both branches to be added and committed. You can check by running **git status**. 
- Once all of the changes on both branches have been added and committed, make sure you're on the advice branch. You can check by running **git branch**.
- While on the advice branch, merge the main branch into the advice branch by running **git merge main** (If your branch is named **master**, use **master** instead.)
- While on the advice branch, push your advice branch to GitHub by running **git push origin advice**. This will push all changes to the GitHub advice branch. You could also push your main branch if you like by running **git push origin main**.

How does that sound? Let us know if you have any questions. You've got this!

Best,
Lisa

**Comment by bobbyc123x** [comment]
Hi Lisa..I made a change to add a color and my remote branches(main/advice}
looked fine but when I go the finishing steps I am again running into
issues.  Very frustrating!   now it appears my advice branch no longer has
my changes but my main branch does..... i am not in sync with the
skillcrush repo because of the following    This branch is 3 commits ahead
<https://github.com/bobbyc123x/git-practice/compare/skillcrush:git-practice:main...advice>
, 58 commits behind
<https://github.com/bobbyc123x/git-practice/compare/advice...skillcrush:git-practice:main>
 skillcrush:main.  How can I fix this mess.   I want to understand this
completely before moving forward.  thnx!


***@***.*** MINGW64 /c/users/marya/git-practice (advice)
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

***@***.*** MINGW64 /c/users/marya/git-practice (main)
$ git merge upstream/main
Auto-merging index.html
CONFLICT (content): Merge conflict in index.html
Automatic merge failed; fix conflicts and then commit the result.

***@***.*** MINGW64 /c/users/marya/git-practice (main|MERGING)
$ git merge upstream/main
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.


***@***.*** MINGW64 /c/users/marya/git-practice (main|MERGING)
$

***@***.*** MINGW64 /c/users/marya/git-practice (main|MERGING)

**Comment by bobbyc123x** [comment]
Hi Lisa, you can ignore the previous note.  I started the process from the
beginning. I'm looking for answers to some of the instructions below from
the finishing forking workflow steps. Sorry to keep bothering you with this
but I really need to be clear on this. THANKS!!!   PLEASE SEE MY QUESTIONS
IN YELLOW BELOW.   AT WHAT POINT DOES MY MAIN BRANCH GET UPDATED...EVEN
WHEN I CREATE THE PULL REQUEST MY MAIN BRANCH DOES NOT HAVE THE CHANGES IN
THE ADVICE BRANCH.  I FOLLOWED ALL THE STEPS AND I NEVER SEE THE MAIN
CONTAINING MY ADVICE BRANCH CODE.

   1. Make sure you’re in the git-practice repo from the Start the Forking
   Workflow
   <https://learn.skillcrush.com/module-10/start-the-forking-workflow/> step.
   MY ADVICE BRANCH OR MAIN BRANCH???
   2. To make sure you’re still in sync with the source code, you’ll
   connect to the upstream: git remote add upstream
***@***.***:skillcrush/git-prPactice.git
      THIS ONE COMMAND AND WHAT IS IT ADDING OR DOING????
   3. Run the git remote -v command to see which repos you’re connected to.
   You should see your forked version of the repo (origin) and the source code
   repo (upstream).  DOES UPSTREAM MEAN MY MAIN OR SKILLCRUSH MAIN??
   4. Use the git fetch command to update your upstream remote branches: git
   fetch upstream.  WHAT IS THE UPSTREAM REMOTE BRANCH???
   5. Run the git branch -a command to view your local and remote branches.
   In the list of branches, you should see upstream/main, which is the branch
   you’ll use to stay in sync with the source code.  IS THIS TAKING THE
   SKILLCRUSH REPO AND UPDATING MY MAIN BRANCH  IS UPSTREAM MAIN A COPY OF MY
   MAIN BRANCH DON'T SEE ANYTHING IN GITHUB AFTER THIS COMMAND..
   6.   Take a look at the message after you merged. If you see “Already up
   to date,” that means the upstream code hasn’t changed since you originally
   forked your repo. Or, you might see a list of files that were added or
   updated since you forked the repo or synced your local code. Either way,
   you’ll now ensure your local code is in sync with the source code!  WHAT
   MERGE???
   7. To incorporate the updates from the upstream into your advice branch,
   you’ll move back over to the advice branch.
   8. Merge the freshly updated main branch into the advice branch.  WHAT
   IS THE ACTUAL COMMAND???
   9. Push the advice branch up to your repo: git push origin advice.
   10. Go to your forked copy of the git-practice repo on GitHub.
   11. In the Branch drop-down menu, select the advice branch. Then, click
   the Pull Request button. I ASSUME YOU CHANGE TO THE ADVICE BRANCH
   BECAUSE THERE ARE NO CHANGES IN IT.
   12. On the Open a Pull Request page, click the Create Pull Request
   button.
   13. We’ll respond directly on your Pull Request page by letting you know
   if we’ve accepted your pull request, or if we require any changes to your
   code.
   14. Once your pull request has been accepted, click on your request on
   the Pull Requests page. Copy the pull request URL in the browser.

**Comment by twosavoie** [comment]
Hi @bobbyc123x,

You did an awesome job! The other pull request you sent has been merged, so I'm going to close this one out. 

Unfortunately, formatting doesn't come through in the message you sent so I'm not sure what parts of your message was meant to be yellow so I hope I'm responding to your questions. If not, just let us know! You can send a message to the Student Slack Channel or to questions@skillcrush.com

1. You can be in either branch at this point. When you're ready to merge the upstream branch, you'll checkout the main branch.
2. This adds the upstream branch as one of the branches you can fetch code from.
3. The upstream branch is the Skillcrush main branch. You'll see the "Skillcrush" username in the url.
4. This is the Skillcrush main branch.
5. This is the Skillcrush main branch that you've now added to your local repo so you can fetch code from it.
6. The merge in this step. You checkout the main branch and merge in the upstream branch by running **git merge upstream/main**.
7. No question
8. The command is **git merge main**.
9. No question
10. No question
11. The advice branch has both your local changes - your new advice file in the advice folder and a link to it in the index.html file. And it has any changes that occurred to the Skillcrush main branch that came after you originally forked the code.

I hope that helps! 

xoxo,
Lisa

**Comment by bobbyc123x** [comment]
Hi Lisa, thanks so much for your help/patience and very thorough response
to all my questions!
Maryann Cavanaugh

**Pull request closed without merging**
