### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by kasturdevant**
added my own advice, took so long had to add a few new files before merging.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @kasturdevant,

Great start here! 

Checking the index.html file, there are conflict markers in your code. They may be left over from resolving a merge conflict (you can see them here: https://github.com/skillcrush/git-practice/pull/1028/files) Can you check to be sure the merge conflict was resolved without deleting or duplicating any links? And then remove the conflict markers

That's it!! Once you've made those changes, save the file, add it with git add -A or git add index.html, make your commit as per usual and finally push up your advice branch once more, which will automatically update this pull request.

Then we'll be all set to merge in your code! Let us know if you have any questions!

Best,
Lisa

**Comment by kasturdevant** [comment]
Hello Lisa,
    So i fixed it on my computer, there are not conflicts is vs code. I am
not sure whats going wrong because looking on github the problem
still exists. I already finished this front development track, but i was
doing some work on the side and found that I wasnt understanding things. I
am retaking this class and redoing everything from scratch and I just don't
get what is going on. It looks like the problem is still persisting here on
github.

-Kimberly

**Comment by kasturdevant** [comment]
Okay,
 I did all that. I updated the advice line, looking at the pull request it
is full of red and green. I don't know if it is supposed to look like that,
but my link is there now.

**Comment by kasturdevant** [comment]
Thank you so much! Sent from my iPhoneOn May 23, 2023, at 03:02, Lisa Savoie ***@***.***> wrote:﻿
Hey @kasturdevant,
Great job! The red you see is your previous code in the index.html file and the green is the code from the upstream repo. If you would like to see the current diff, have a look here.
Your code is all merged in.
Best,
Lisa

**Pull request merged**
