### PR TITLE
Added Brittany advice page and link to index.html

### PR DESCRIPTION
**Pull request by brittanymia**
I merged my advice branch to my main branch after some confusion, so now it looks as If I've made no changes to the advice index.html. Out of frustration and confusion, I am moving along.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @brittanymia!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by brittanymia** [comment]
How do I push my advice branch up once more once I've committed the
changes? Do I use git merge, and merge the advice branch with the main
branch?

**Comment by brittanymia** [comment]
I did git push origin, and I believe I that worked. How will I know if my
pull request has been updated?

**Comment by redrambles** [comment]
Hello there! 

So we didn't get any changes on our end quite yet. You'll want to use `git push origin advice` in order to push up your advice branch, which is what this pull request is built off of. If you run `git status`, do you see a clean working directory?

**Comment by brittanymia** [comment]
Yes, I see a clean working directory.

**Comment by redrambles** [comment]
Ok that's good! So let's run `git push origin advice`. Given that you have updated your advice branch since you last pushed it up, we should see an update on our end.

Keep us posted!

Cheers,
Ann :)

**Comment by brittanymia** [comment]
Roger that, done!

**Comment by redrambles** [comment]
All good!

Your code is merged in! ✨

Cheers,
Ann :)

**Pull request merged**
