### PR TITLE
Added Christina H's advice

### PR DESCRIPTION
**Pull request by chawki20**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @chawki20 !

This is really great! We just need a few things before we are ready to merge this in.

1) Your advice file, `christina-hawkins-advice.html`, is in the root of the project folder. We need it to be inside the `advice` directory, so please move it in there.

2) Your link in the index.html file is using curly quotes instead of straight quotes. The difference is hard to see unless you have learned to spot it over time. Compare your quotes with those of the link above. Curly quotes unfortunately aren't well interpreted by computers and tend to break things, so I strongly suggest that you change your curly quotes over to straight quotes.

3) While you are there, pop a `<br>` tag after your link, so that the next one can start on its own line. 

Once you have made these changes, add them all with `git add -A`, then commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by chawki20** [comment]
Hi Ann, 

Thanks for the detailed instructions. I made the changes below, but as this is still far from second nature let me know if further changes are needed! 


***@***.***  |  404-538-5026 |  christinaehawkins.com <http://www.christinaehawkins.com/> | LinkedIn <https://www.linkedin.com/pub/christina-hawkins/21/785/272>

**Comment by redrambles** [comment]
Hello @chawki20 !

Hmm - I'm not seeing the changes on our end. Can you make sure that you have added and committed your files? A `git status` will help you determine this. If so - remember that it is your advice branch that is tied to this pull request, so you'll want to push up that particular branch in order to update it: `git push origin advice`

Keep us posted!

Cheers,
Ann :)

**Comment by chawki20** [comment]
Hi Ann, 

I ran git status on the advice branch and it says there’s nothing to commit. My main branch was ahead by 2 commits so I pushed those. 

I looked into starting over from the beginning (as I clearly missed something…) but how can I do that with this forked and cloned repo? 

I went ahead to Step 5 Finishing Workflow and all looks good there too (fixed conflicts with 3 new files added since my attempts last week)...





***@***.***  |  404-538-5026

**Comment by acodeinprogress** [comment]
Hi @chawki20,

It looks like you made your changes on the main branch rather than the advice branch. Since pull requests are branch-specific, your changes won't show up here.

If you'd like to move forward, you can close this pull request or let us know and we can close it. Or if you'd like to try to fix it, you can either create a new pull request for your main branch or you can make your changes on the advice branch and push to the advice branch.

Let us know what you'd like to do!

xoxo,
Sharon

**Comment by chawki20** [comment]
I'll close this Pull request and retry. Thanks!

**Pull request closed without merging**
