### PR TITLE
Added advice Sarah Heinzkyll

### PR DESCRIPTION
**Pull request by SarahHeinz**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @SarahHeinz !

This is fantastic - very well done!! The only thing we need is a tiny break tag `<br>` after your link in the index.html file, so that we can make sure that every link occupies its own line.

Once you add that in, please add and commit this change and then push up your `advice` branch once more, which will automatically update your pull request. Then we should be all set to merge in your code!

Let us know if you have any questions! 

Cheers,
Ann :)

P.S - I like your advice! ❤️

**Comment by SarahHeinz** [comment]
Hi Ann, 

thanks a lot for your kind feedback and advice!!! <3 I added the break and pushed it and I hope it worked. :)

Have a great day, 
Sarah

**Comment by SarahHeinz** [comment]
Screenshot (86)

Hi Ann, 
thanks a lot for letting me know! I added the screenshot of what I did, as it seems to me that I did exactly what you described to me. I was not sure that I understood one hundred percent where to put the break. Did you mean here: 
 <iframe src="https://giphy.com/embed/QXIlzWgsDfovPCcn59" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><br>
                 <p><a href="https://giphy.com/gifs/PumpkinPetcare-QXIlzWgsDfovPCcn59">Can't stop!</a></p>

I put a break there. If you meant somewhere else it won't appear as I understood you wrong. :) Please let me know if we are on the same page of where to put the break and if you see any other mistake that I did in adding, commiting etc. Thank you so much for your help. 
Best, 
Sarah

**Comment by SarahHeinz** [comment]
it translated the link to a link and took away the break sign. :D Good to know. I will try again. 
 iframe src="https://giphy.com/embed/QXIlzWgsDfovPCcn59" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen -iframe - **br**-
                 p - a href="https://giphy.com/gifs/PumpkinPetcare-QXIlzWgsDfovPCcn59">Can't stop!/a- /p
now it looks like very bad code but i had to prevent github from turning it into the link. Sorry. I put the break in bold.

**Comment by redrambles** [comment]
Hello @SarahHeinz !

Ahhh -thank you for that extra context - it appears I wasn't clear in where I was asking for the breakpoint to be added!!

In the main index.html file (in the root of the project directory):
CleanShot 2023-02-10 at 10 02 30

Does this help clarify? Nearly there!!! 🎉

**Comment by SarahHeinz** [comment]
thanks so much! great, now I understood and added the break. I really hope I managed this time. :) thanks a lot for letting me know if it worked out. 
best, 
sarah

**Comment by redrambles** [comment]
Hey @SarahHeinz !

Yes!! Well done, your code is merged in!! 🎉

Cheers,
Ann :)

**Pull request merged**
