### PR TITLE
Added Paul Dennis Advice html

### PR DESCRIPTION
**Pull request by Genxertechie**
I'm working through the Finishing the Forking Workflow. Hope I'm doing this right.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Genxertechie !

Congrats on your first pull request! The index.html file is great -but we have some things to address in the advice directory - namely that the files inside it were deleted. :D No worries - this is why we use version control - we can recover from this! 

Here are the steps:

1) Make sure you are on your advice branch `git checkout advice`

2) Run the following:
`git checkout upstream/main advice/`

This will update your `advice` directory to contain whatever that directory contains in the upstream (Skillcrush) repo - so that it is up to date. You should see that this added nearly 800 files when you run `git status`

3) Then let's restore your file, which we should also have seen listed (in red) in the `git status` output:
`git restore advice/Paul-Dennis-advice.html`

4) Then go ahead and commit `git commit -m "Your message here`

That should do it! You should now have all the files in the advice directory back as well as your own advice file.

Let's push up your advice branch, which will automatically update this pull request:

`git push origin advice`

And then I'll circle back and check on the status of your PR. :) Let us know if you have any qs!

Cheers,
Ann :)

**Comment by Genxertechie** [comment]
@redrambles I'm getting frustrated (sad face).
I'm not sure I am doing things right.
I've attached a screenshot of walking through the instructions and I'm getting messages that make me think I'm missing something. 
Screenshot (51)

**Comment by twosavoie** [comment]
Hi @Genxertechie,

I wanted to be sure you received the response to the email we sent. If you need any help with this, let us know! 

Best,
Lisa

**Comment by Genxertechie** [comment]
Hey Lisa
Yes I did get a reply. I haven't had a chance to work on it yet. Hoping to
do that shortly and let you guys know how it goes.

Thanks for checking back with me.

Paul Dennis

**Comment by twosavoie** [comment]
Hi @Genxertechie,

Checking to see if you have any questions or need any help. Let us know!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @Genxertechie,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Just in case you would like a fresh start, you can delete your GitHub repo by going to the repo's Settings and scrolling to the bottom of the page. Then delete your local git-practice directory. Once both are deleted, you're all set to re-fork the project. 

I hope that helps! 

Best,
Lisa

**Pull request closed without merging**
