### PR TITLE
Added L's Advice

### PR DESCRIPTION
**Pull request by laurelco**
Practicing leaving a comment. Oof. Git Hub works very differently than my brain wants to work.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @laurelco,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by laurelco** [comment]
Hmm. I did add some advice,  but who knows what happened. Well, back to the
drawing board.
Thanks for letting me know.

**Comment by twosavoie** [comment]
Hi @laurelco,

While on the advice branch, check to see if the advice file is in the advice folder. If so, can you run **git status** to be sure all of your changes have been added and committed? Once all changes have been added and committed, you could push your advice branch to GitHub and it will updated this pull request. 

If you have any questions, let us know! You've got this!

🙂
Lisa

**Comment by laurelco** [comment]
Did it work this time? I didn't change any CSS but there should be advice.

**Comment by twosavoie** [comment]
Hi @laurelco,

The advice file and the link to it look great! Well done!

It looks like there are some conflict markers that could be removed. When you do, take a look at the links to students' advice files. While keeping your own, check to be sure no one else's is deleted. 

Also, since the index.html file is for the repo that holds the links for all students, can you change the text in the <title></title> and <h1></h1> to what it was before? 

Then you'll be ready to add, commit, and push to GitHub. Your pull request will be automatically updated!

Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @laurelco,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by laurelco** [comment]
Well, shit. I thought I did. Wonder what I'm doing wrong? I'll make a new
pull request. Back to the drawing board!

**Comment by twosavoie** [comment]
Hi @laurelco,

I wonder if the changes were made on the main branch instead of the advice branch? If so, you could merge the main branch into the advice branch and push the advice branch to GitHub. 

If you'd like to take a look at the changes to your file (including the conflict markers and change to the text in the <title> tag), you can view them here: https://github.com/skillcrush/git-practice/pull/750/files

Let us know if you have any questions!

xoxo,
Lisa

**Comment by laurelco** [comment]
Will look into it today or tomorrow. Who knows what I did wrong. The
merging piece is a totally grey area for me and I think it shows.

**Comment by twosavoie** [comment]
Hey @laurelco,

Checking to see if you have any questions that we can help you with. 😀 

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @laurelco,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by laurelco** [comment]
Thanks. Forgot about it. I will go back and get this lesson at a later
date.

**Pull request closed without merging**
