### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by janenag**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @janenag,

This is a great start! Well done! And what excellent advice! 

Just a few small changes to make before we can merge your code into the Skillcrush repo:

- We would like your advice file to be in the advice folder. 
- So that the CSS styles you've written take effect, add a link to the css/janena-reynolds-advice.css stylesheet in the <head> of the  janena-reynolds-advice.html file
- Add a link in the index.html file to your janena-reynolds-advice.html advice file. 
- And, unfortunately, remove the image. (Though I love the beach pic!) Since so many students contribute to this repository we can't merge in images or the repository would become too large. You could link to an image that's hosted on the web though. 🙂 

How does that sound? When you're finished, add by running `git add -A`, and commit by running `git commit -m "Your message"`. Then push up your advice branch once more with `git push origin advice`. This will automatically update your pull request and we should be all set to merge in your code.

Let us know if you have any questions!

Best,
Lisa

**Comment by redrambles** [comment]
Hey @janenag !

You did great!!! There is just one tiny thing left to do - there is a duplicate of your advice file in the root of the project folder - see here:

delete

Please delete this file (you can just drag it over to the trash, or right click on it and delete it). Then add that change by running `git add -A`, commit as per usual `git commit -m "Your message here"` and finally push up your advice branch once more `git push origin advice`. That should take care it it!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hi @janenag,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by janenag** [comment]
Yehaw!


Sent from Yahoo Mail for iPhone


On Saturday, October 28, 2023, 12:34 PM, Lisa Savoie ***@***.***> wrote:




Hi @janenag,

Great job! Your code is all merged in.

Best,
Lisa

**Pull request merged**
