### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by learningcoding2022**
Changes to advice

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

You've done a fantastic job and you're super close! You'll want the name of your advice file to exactly match the link in the index.html (including capitalization.) Try changing the file name so that it is all lowercase letters to match the link. 

Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by learningcoding2022** [comment]
Okay- sounds good! Where should I change the name of the advice file to
exactly match the link in the index.html (Is the file name you are
referring to, "Molly-brown-advice"?)? I'm a little confused about this. I
moved to the next section so I'm having trouble recalling or seeing where
I've put the specific file name in gitbash.

Thanks for your help Lisa!!

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Happy to help! Start by navigating to the git-practice directory and run **git status** so you can check to be sure you're on the advice branch. (If you aren't, go ahead and check out the advice branch.)

Next, look at the name of your advice file within the advice folder. The name of the file begins with a capital "M". Then take a look at the link to the file in the index.html file which has a lowercase "m". Change the name of the file in the advice folder so that it also has a lowercase "m" and the two will match. (The link would have likely worked locally because our local environments are much more forgiving of case mismatches.)

If you like, you can also see the difference here: https://github.com/skillcrush/git-practice/pull/856/files

Does that help? Once you've made the change, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by learningcoding2022** [comment]
Hi Lisa,

I just made the corrections requested. Does everything look okay?

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

I don't see the change to the file name. Could you make sure the changes were made on the advice branch? And then run **git status** to check that all changes have been added and committed? If there are changes to be added (you'll see any written in red) try adding them by running **git add -A** (with a capital A). Then commit as you normally would and push your code to GitHub to update your pull request.

If you're unsure, can you email us screenshots of your local file structure and your command line to questions@skillcrush.com? We're happy to take a look!

Best,
Lisa

**Comment by learningcoding2022** [comment]
Hi Lisa,

I'm really struggling with this last step. When I tried going through this
exercise again, I am getting this message that comes up in github asking me
to explain why I am making a merge, but when I enter the message...I can't
get out of this. I'm getting a little confused with this exercise because I
am making changes and then for some reason the commit for the change isn't
going through and then when I try the exercise again the changes are no
longer new. I attached the message I am getting in gitbash and can't get
out of. I would send the rest of my code, but it no longer shows when this
message comes through. I may need someone to walk me through this one- I
just am getting really confused.

Thanks!
Molly

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Thanks for reaching out! Unfortunately, the attachment didn't come through. Could you instead send us screenshots of what you see to questions@skillcrush.com? We'll be able to exchange messages much more easily. 🙂 

Thanks!
Lisa

**Comment by learningcoding2022** [comment]
Sure! Just sent it!

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Checking in to see if you have any questions or need any help with this pull request. If you do, let us know. 😀 

Best,
Lisa

**Comment by learningcoding2022** [comment]
Thanks for reaching out Lisa! When I went back to the advice branch- it isn't showing anything in red that hasn't been committed already, so I'm not really sure why the change isn't coming through. I did change the file name to a lowercase m in my name to match, I saved this file, and I then I went to the advice branch to commit, but it isn't showing any new changes (and technically this is no longer a new change).

**Comment by learningcoding2022** [comment]
Thanks for reaching out Lisa! When I went back to the advice branch- it
isn't showing anything in red that hasn't been committed already, so I'm
not really sure why the change isn't coming through. I did change the file
name to a lowercase m in my name to match, I saved this file, and I then I
went to the advice branch to commit, but it isn't showing any new changes
(and technically this is no longer a new change).

**Comment by learningcoding2022** [comment]
I've gone through this entire exercise again from committing the changes
(to the file name) to the advice branch all the way to merging branches
again, and pushing the changes through. I attached my code to this email.
I'm still not seeing the change to the file name in github though. Could I
possibly meet with someone to work through this after the office opens back
up after the holidays if I can't get figured out soon? I've been stuck on
this step for a good while now.

Thanks!

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Sounds like a great idea! Can you tell us a few times you're available over the next few days? We can try a huddle in Slack or a short Zoom call. 

If you would like us to look over your zipped code, can you send it to questions@skillcrush.com? (Unfortunately, attachments aren't uploaded.) Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Checking in to see if you still want to meet to look over your code. Let us know and we'll set up a time. 👍 

Best,
Lisa

**Comment by learningcoding2022** [comment]
Hi Lisa,

Yes- that would be great! Sorry- I missed the Q and A yesterday evening...I
had a meeting a work go longer than expected and then the interstate was
shut down...by the time I got home I had completely forgotten about it!
Would you be available to meet to look over the code this evening maybe 5,
5:30, 6? I'm pretty flexible with times this evening. If today doesn't
work, I can send you some more times.

Thanks

**Comment by learningcoding2022** [comment]
Hi Lisa,

Something came up for this evening and I'm not longer available. I'll reach
back out with some times!

**Comment by learningcoding2022** [comment]
Hi Lisa,

Do you happen to have any time this Thursday (4:30 or after), friday, 6:45
or after, or saturday morning? I signed up for the dev session at 12:00,
but have to leave for an appointment at 12:40 so I'm not positive I'll get
to go through my question. Sorry for the delay in getting back to you!

Thanks!
Molly

**Comment by twosavoie** [comment]
Hi @learningcoding2022, 

Unfortunately, Thursday and Friday are my off days. I can take your question first thing in the Dev Q&A, so let's give that a try. How does that sound?

Looking forward to seeing you. 🙂

Best,
Lisa

**Comment by learningcoding2022** [comment]
That sounds good- thank you!

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Just checking in to see if you needed any help with this pull request. Let us know if you have any questions! 

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @learningcoding2022,

Based on our conversation today, we're going to go ahead and close this pull request. When you're ready to give this another go, let us know if you have any questions! 

Best,
Lisa

**Pull request closed without merging**
