### PR TITLE
Added Courtney's Advice

### PR DESCRIPTION
**Pull request by Courtney-AA**
I added my advice for newcomers :)

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Courtney-AA !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Courtney-AA** [comment]
Hello,

I think I'm lost and I'm unsure how to complete this. I have tried going back to resolve but may have made a bigger mess than when I started. Any help is greatly appreciated! It appears I have issues with my index file but I try to add and commit it and receive an error.
[git help.pdf](https://github.com/skillcrush/git-practice/files/6216010/git.help.pdf)

**Comment by acodeinprogress** [comment]
Hey @Courtney-AA,

This indicates that you have a merge conflict, which occurs when you and someone else edit the same line(s) in the same file(s) and Git doesn't know which to keep.

If you need help with resolving merge conflicts, you can review this lesson: [https://learn.skillcrush.com/module-8/merging-resolving-conflicts/](https://learn.skillcrush.com/module-8/merging-resolving-conflicts/)

Let us know how it goes!

xoxo,
Sharon

**Comment by Courtney-AA** [comment]
I believe this should now be updated. Please let me know if it's good to go or if anything else is needed. Thank you!

**Comment by redrambles** [comment]
Hey @Courtney-AA,

Thanks so much for making those changes, your code is merged in! 🎉

**Pull request merged**
