### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by SionGH**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @SionGH,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by SionGH** [comment]
Hi Lisa, Thank you so much. Now, I can see my link on the list of names.
Just one thing, when I go to my repo on git hub, where do I see those
changes?
Have a lovely Sunday and thanks again🙂

**Comment by twosavoie** [comment]
Hi @SionGH,

That's great! If you've already added and committed your changes, the next step would be to push your advice branch to GitHub. The push will automatically update your pull request. 🙂

To see the changes on your GitHub repo, you can click on the Branches dropdown and choose the advice branch.

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @SionGH, 

I just wanted to check to see if you had any questions about updating your pull request. Feel free to reach out if you do!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @SionGH,

Happy to help! It looks like the link was added to the index.html file in the main branch. You'll also want to add it to the advice branch (the branch you're issuing a pull request for.)

Once you've added to the link while on the advice branch, you can add and commit your changes. When you push the advice branch to GitHub, the pull request will update. 

Let us know if you have any questions!

xoxo,
Lisa

**Comment by SionGH** [comment]
Hi Lisa! I think I´ve done it :D ! but I´m not sure... Can you check it for me? Thank you!
xoxo
Asunción

**Comment by twosavoie** [comment]
Hi @SionGH, 

Unfortunately, I don't see the link on the advice branch on your GitHub repo: https://github.com/SionGH/git-practice/blob/advice/index.html. 

Could you try merging your main branch (that has the link) into the advice branch? Start by checking out the advice branch and then run **git merge main**. Then you should be able to push the advice branch to GitHub which will update your pull request. 

Let us know if you have any questions!

xoxo,
Lisa

**Comment by SionGH** [comment]
Hi Lisa! Thank you for being so helpful. There was a conflict. I think it is solved now because I can see my link although it isn´t aligned and it´s in green... I don´t know what it means.
:D Asuncion
xoxo

**Comment by twosavoie** [comment]
Hey @SionGH,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

We nudged it in so it aligned with the others. The green means that it's an update to the existing Skillcrush repo. Does that answer your question?

xoxo,
Lisa

**Comment by SionGH** [comment]
Yes! Thank you Lisa!:D

**Pull request merged**
