### PR TITLE
Changed CSS styles and updated HTML

### PR DESCRIPTION
**Pull request by WithAWhy**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @WithAWhy,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by WithAWhy** [comment]
Did this work?

**Comment by acodeinprogress** [comment]
Hi!

This is close! It looks like you changed another student's link rather than adding your own separate link. We want to preserve everyone's work so you'll need to restore the link that you changed. If you need a hint, you can look at the [Files Changed tab](https://github.com/skillcrush/git-practice/pull/6/files) near the top of the page.

Once you fix that up, you can add, commit, and push your work to GitHub and it will join this pull request here.

xoxo,
Sharon

**Comment by WithAWhy** [comment]
Hi! I’m so confused! When I pull it up on my computer, my link is there, as the third one, below the others. And it’s an active link! I truly don’t know what is happening. I edit that on my local brach, add, commit, merge, push and somehow it’s not what I’ve done on my computer!

**Comment by redrambles** [comment]
Hey @WithAWhy !

Ok! So I'm not sure why, but your changes came through as a patch, which I needed to resolve on my end. Do you want to have a look at what is in the git-practice repo at the moment in terms of your styles and advice page and let us know if these are the changes you want?

We'll go from there!

**Pull request closed without merging**
