### PR TITLE
Added a href that directs to my advice html file

### PR DESCRIPTION
**Pull request by PowersNT**

### CODE REVIEW

**Comment by PowersNT** [comment]
I know that I made an error somewhere and I will need some help to resolve the conflict that has occurred. Thank you.

**Comment by PowersNT** [comment]
I know I made an error somewhere and need help resolving the conflict. Thanks in advance for your help.

**Comment by twosavoie** [comment]
Hey @PowersNT,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by PowersNT** [comment]
Dear Lisa,

     I apologize for not getting back to you until now.

     I have my advice HTML and css files ready, but as carefully as I
followed the directions, something went wrong when I tried to commit and
push those files during Steps 5 and 6 in the "Working with Teams" section.

     I really am lost, I don't know how to get the result working
correctly. Any help would be greatly appreciated.

Sincerely,

Tricia

**Comment by twosavoie** [comment]
Hi @PowersNT,

Let's check to make sure all the boxes are checked. You can run `git branch` to make sure you're still on the advice branch. Then add the CSS and HTML files to your project folder if they aren't there. In the command line, run `git add -A` (with a capital A) to add all of the changes, then `git commit`. When you're finished, you can run `git push origin advice` to push to the advice file which will update your pull request. 

Let us know if you have any questions!

🙂
Lisa

**Comment by twosavoie** [comment]
Hey @PowersNT,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by PowersNT** [comment]
Hi Lisa,

     I apologize that I didn’t see the reply that you had sent on Feb. 8th.
I will try the steps you suggested and let you know whether or not I am
successful.

Thank you,

Tricia

**Pull request closed without merging**
