### PR TITLE
Added AW advice

### PR DESCRIPTION
**Pull request by awinslow44**
I'm unsure if this is where and how the pull request is submitted.

Any help is appreciated!! Thank you!

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @awinslow44,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by awinslow44** [comment]
Hi Lisa,

I'm fairly sure I did add my advice link to the index.html file - and
add/commit/pushed it to Github... but it isn't showing up and I'm unsure if
there is something I skipped?

Thank you!
Andrea

**Comment by twosavoie** [comment]
Hi @awinslow44,

You might check your index.html file in your text editor. Do you see the link to your advice page? And are you on the advice branch? 

If so, can you be sure to save the changes and then return to the command line. Run **git status** to be sure that you're on the advice branch and that all changes have been added and committed. Then try pushing the advice branch to GitHub again. 

Let us know if you have any questions!

Best,
Lisa

**Comment by awinslow44** [comment]
Hi @twosavoie,

I've gone thru the steps again - and now there is indication that the index.html update is conflicted with someone else's advice update it looks like. 

I don't want to "resolve" this by deleting the other students work... help!!

Andrea

**Comment by twosavoie** [comment]
Hi @awinslow44,

It sounds like there's a merge conflict. This is perfectly normal when multiple people work on a project. Git wants to be sure that none of the code you want to keep is deleted. 

Check to be sure that you aren't deleting anyone else's links and be sure to remove the conflict markers. Then you'll add and commit the changes and push the advice branch to GitHub. 

If you're unsure, have a look at this lesson where you had some practice with merge conflicts: https://learn.skillcrush.com/module-8/tackling-merge-conflicts/ and let us know if you have any questions! 

xoxo,
Lisa

**Comment by redrambles** [comment]
Hey @awinslow44,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
