### PR TITLE
Added nicole-harris-advice page (html & css files) and added link to index.html

### PR DESCRIPTION
**Pull request by IndyArk**
I think the GitHub site has updated their buttons/tabs/links, so that the skillcrush instructions for the step to create a pull request are now a bit outdated/confusing.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @IndyArk,

It looks like GitHub helpfully changed those links into clickable text. 

Just in case it's helpful, when you add the links back, they should look like the links with the red background:
Screen Shot 2022-01-19 at 11 11 17 AM

Thanks! 
Lisa

**Comment by IndyArk** [comment]
Hi @twosavoie !

Thanks for reviewing! Whoops! I will put those links back into the index.html file and add, commit and push my changes so you can review the pull request again. 

Thank you!

**Comment by IndyArk** [comment]
Ok, I added the 3 links back to the index.html file. Then did the following:
navigated to local git-practice file in command line

`git branch` to check which branch I was on (it was 'advice' branch)

`git checkout main` to switch to main branch

`git branch` to check that I was on main branch

`git add index.html`

`git commit -m "my commit message"`

`git push origin main` to push changes to already-created pull request...

It returned: 'Everything up-to-date" 

Hope this was correct! :)

**Comment by IndyArk** [comment]
@twosavoie 
It feels great for me to use Git, but this is what I imagine is going on for you :-): 
[https://programmerhumor.io/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/01/programmerhumor-io-linux-memes-backend-memes-e9d19e923408ea8-758x1701.png.webp](url)

**Comment by redrambles** [comment]
Haha - we just take it one PR at a time, @IndyArk ! :) 

Ok! So here is what I think is going on. You have opened up this pull request based on your 'main' branch - but you mention in your last comment that you were working on your advice branch. The advice branch is ideally where you would be working for this, AND the branch from which you created your pull request - but that's not quite what is going on here. 

No worries! Given that this PR is built from the main branch, let's pull in your latest changes that you made in the advice branch. So first - make sure you are on your main branch:

`git checkout main`

Then merge in your advice branch:

`git merge advice`

And then finally push up once more:

`git push origin main`

This time you should not be getting the 'everything is up to date message' because you will be pushing up a commit (or more). 

Keep us posted!

Cheers,
Ann :)

**Comment by IndyArk** [comment]
@redrambles ,
Ok, thanks! I'm pretty sure I did it right this time. So, what happened was I didn't merge the advice branch into the main branch first, before I pushed the changes...?

Just so I'm not confused... the original merge conflict was because 3 other students happened to try to merge their changes (links on the same line), at the same time I merged, so that created the merge conflict, and when I tried to resolve the merge conflict, I erased their links and left mine, when I should have just erased the merge conflict symbols and left all the links to resolve and keep everyone's changes?

**Comment by redrambles** [comment]
> Just so I'm not confused... the original merge conflict was because 3 other students happened to try to merge their changes (links on the same line), at the same time I merged, so that created the merge conflict, and when I tried to resolve the merge conflict, I erased their links and left mine, when I should have just erased the merge conflict symbols and left all the links to resolve and keep everyone's changes?

Yes that is 100% correct! 

And the reason you needed to merge in your advice branch into your main branch is because your pull request was made from your main branch, and so in order for these changes to show up on our end, they needed to exist on your main branch. 

Everything is looking good here - thanks for making those changes - your code is merged in!

**Pull request merged**
