### PR TITLE
added a link to advice page on index.html and styled the advice page …

### PR DESCRIPTION
**Pull request by Nix73**
…with new css

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Nix73,

Congrats on making your first pull request!

I see that you added a couple images to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the images inside, and update your image links in your advice page. 

Then you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Nix73** [comment]
Hi Sharon,

Im so baffled, I went back into my local fille git-practise and all my
changes including the img folder are not there. For the life of me I have
no idea how this is possible.  I could re-do the entire exercise but what
would happen then to the pull request and the img file i sent with it? sjoe
I don't even know what to do now..is the file still forked and is the clone
i have up to date or missing anything else? Im a bit puzzled as to how to
proceed..

:) hope Ive made any sense

Thanx a mil
Nix

**Comment by redrambles** [comment]
Hey @Nix73 !

Ok! So first make sure that you are on your `advice` branch, in the root of your git-practice project folder, and then run `ls`.  Do you see the 'img' directory listed there?

If so - you'll just want to remove it. You can do so by moving it over to the trash manually using the FileExplorer / Finder and just dragging it over - or you can use the command line:

`rm -rf img`

And then add the change:

`git add -A`

Commit it:

`git commit -m "Remove img directory"`

And then push up once more:

`git push origin advice`

And then your pull request should be up to date with those latest changes, which would mean that we could merge in your code. 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Nix73** [comment]
Hi Ann,

I think Ive really buggered up now...Im not sure where to go from here.

Screenshot 2021-11-09 at 09 52 54

**Comment by redrambles** [comment]
Hey @Nix73 !

This is totally fine - it's a regular ol' merge conflict. This is particularly common in the index.html file, as all students are editing it by adding in their own links. All that needs to be done here is to make sure to keep everyone's links and just remove those conflict markers. Save the file, then add it back in the Terminal `git add index.html` then go ahead and commit `git commit -m "Your message here"` which will conclude the merge.

Now you are all set to push up `git push origin advice` and we will be good to merge in your code. If you prefer, I can resolve these merge conflicts myself as well - so if you would rather go that route, just let us know. :)

You're doing great!!

Cheers,
Ann :)

**Comment by Nix73** [comment]
Ok now Im just totally confused...lol
Screenshot 2021-11-10 at 12 44 29

**Comment by redrambles** [comment]
Hey @Nix73 !

This is good to go! Did you resolve the conflicts directly on GItHub? If so, that would have created a commit that you won't have locally (until you pull it down) and would explain the message you received in the Terminal. In any case, the conflict is fixed and I will merge in your code right now! Yay! 🎉

If you have any questions, though - feel free to send them in at questions@skillcrush.com

Cheers,
Ann :)

**Pull request merged**
