### PR TITLE
Advice added

### PR DESCRIPTION
**Pull request by Liberty66**
Comparing changes across two branches

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Liberty66 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Liberty66** [comment]
I think the advice link is added now. If not I might need some simplified steps to follow. Thank you Ann^

**Comment by redrambles** [comment]
Hey @Liberty66 !

Ok - we are making progress!! There are two little things left to address:

1) In addition to the `advice/Marika-Kuprava-advice.html` file (which we want to keep) - you also have a `Marika-Kuprava-advice .html` file that is sitting in the root of the project folder, which we don't need. Please delete that `Marika-Kuprava-advice .html` file.

2) Once that is done, in the index.html file - edit the value of the 'href' attribute of the link that you added to point to the `advice/Marika-Kuprava-advice.html` file (which is the link to the correct advice file).

Once those two changes are made, add them with `git add -A` - then commit as per usual and finally push up your advice branch once more, which will automatically update this pull request. Then we should be all set!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Liberty66** [comment]
Hi Ann,
When I am trying to remove Marika-Kuprava-advice .html from git-practice
directory (rm Marika-Kuprava-advice .html) git can't see the file to
remove.. how can I remove/or open a file from git that's in the directory
but git can't see it.
screenshots attached
Thanks
[image: Screenshot 2022-12-23 at 9.36.02 PM.png][image: Screenshot
2022-12-23 at 9.36.13 PM.png]

**Comment by Liberty66** [comment]
[image: scrcat.png]

**Comment by twosavoie** [comment]
Hi @Liberty66,

You could go to the git-practice folder and control-click or right-click on the file and move it to trash. An advantage of deleting files and folders this way (rather than through the command line) is that you can always pull the deleted file or folder out of the trash. If you delete it in the command line, it's gone-gone.

Then, after updating the path in your index.html file (while on the advice branch) you can add the change to staging by running **git add -A** (the capital A is important), commit as you normally would, and then push your advice branch to your GitHub repo. You pull request will update automatically. 

I hope that helps! Let us know if you have any questions!

Best,
Lisa

**Comment by Liberty66** [comment]
Thank you Ann, I believe I was able to follow the requirements and fix the
issues.

**Comment by twosavoie** [comment]
Hey @Liberty66,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Comment by Liberty66** [comment]
Thank you Lisa.

**Pull request merged**
