### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by dihend**
Adding Diahnn' Advice upate

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @dihend !

This is really great!! The only thing we need you to do is remove the conflict markers in the index.html file on lines 623, 625 and 629. These are totally normal and a result of any merge conflict - it is how Git indicates to you where the merge conflict exists. Now that you have resolved the conflict, we need to remove those markers.

Once you do, save the index.html file, add and commit your change and then push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code! 🎉

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by dihend** [comment]
Okay, I will remove. Totally didn't focus on the conflict part

**Comment by dihend** [comment]
Hello,  I have updated the HTML and pushed the changes.

**Comment by twosavoie** [comment]
Hey @dihend,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
