### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Abigail-S-O**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Abigail-S-O,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by Abigail-S-O** [comment]
@twosavoie I have gone ahead and added a link to the index.html page, saved it, added, committed and pushed the changes. Did I do this correctly?

**Comment by twosavoie** [comment]
Hi @Abigail-S-O,

Unfortunately, I don't see the change to the index.html page. Could you send us a screenshot of your command line showing the commands you ran along with a screenshot of the link in the index.html file? You aren't able to send screenshots in response to this message, but you can send them to questions@skillcrush.com.

We'll be able to go from there!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @Abigail-S-O,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
your name

**Pull request closed without merging**
