### PR TITLE
Name changed

### PR DESCRIPTION
**Pull request by Sayako-Y**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Sayako-Y !

This is a great start!!

There are just a few things we need to address before we can merge this in.

1) You have a `your-name-advice.html.zip` file in the root of the project directory, which we need to remove. Please delete it.

2) Your index.html file has a lot of formatting differences with the original file - most likely due to an automatic formatting preference you have set up in your text editor. No worries! Here is what I suggest.

- Checkout the original index.html file from the upstream repo: `git checkout upstream/main index.html`
- Open up the index.html file in your text editor, add your link to your advice file and then - presuming you are using VSCode - open up the command palette (View -> Command Palette) - type 'save without' in the little search bar that appears and choose 'Save Without Formatting'.

3) Perfect - now go ahead and add `git add -A`, commit `git commit -m "Your message here"` and push up your `advice` branch once more `git push origin advice`

This will automatically update your pull request and we should be all set to merge in your code. 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Sayako-Y** [comment]
Hello there!

I am trying to change a setting on VScode, but I cannot find “save without formatting”.
I will attach the screenshot, so please let me know how I can do this.
Thank you.


Sayako


￼

**Comment by Sayako-Y** [comment]
Hi Ann,

I think I could fix the issues along with your advice. Please let me know if there is still something wrong. Thank you.

**Comment by redrambles** [comment]
Hey @Sayako-Y !

We are almost there!

I see that the .zip file is now removed, excellent!! I still need the link to your advice file in the index.html file, though. Please add your link, then make sure to save without formatting, then run `git add -A`, `git commit -m "Your message here"` and finally push up once more `git push origin advice` - and we should be all set!

Nearly there! Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Sayako-Y** [comment]
Hi Ann,

Can you please let me know how I can add the link?

**Comment by Sayako-Y** [comment]
Hi Ann,

Can you please let me know how I can add the link?

**Comment by twosavoie** [comment]
Hi @Sayako-Y,

Sorry for the delay! When you open the index.html file in your text editor, scroll all the way to the bottom. Then you can follow the format of the other links to add a link to your advice file. `<a href="advice/_your-file-name_" target="_blank">Your name</a><br>`

Remember to add a `<br>` tag at the end so that the next student's link wraps to the next line.

How does that sound? If you have any questions, let us know!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @Sayako-Y,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
