### PR TITLE
Added advice from Tanya Eychner

### PR DESCRIPTION
**Pull request by TanyaEychner**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

This is a great start! I noticed you didn't add an advice page to the advice folder. If you could, that would be great! Once you do, you can add, commit, and push your code to GitHub. It will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by TanyaEychner** [comment]
I think I pushed it now? Please let me know if I still didn't get it right - thanks for your help :)

**Comment by redrambles** [comment]
Hey there! 

We still don't have an advice file on our end. If you run `git status` do you see that changes still need to be added or committed? If not - then let's try pushing up again with `git push origin advice`.

Keep us posted and let us know if you have more qs!

Cheers,
Ann :)

**Comment by TanyaEychner** [comment]
Oh man...I hope I got it this time! Lol! See the pic attached to see if I need to do something different;

CommandLine-TanyaEadvice

Thanks so much! T

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

Well done! We can see the advice file now. The next step would be to move it into the advice folder. Then add and commit the change and push your code to GitHub. Your pull request will update and we should be all set to merge in your code!

Let us know if you have any questions!

Best,
Lisa

**Comment by TanyaEychner** [comment]
Hi! Okay, if this didn't work then I have lost track of what to do and I will need help Lol! Thanks for your patience :)

**Comment by redrambles** [comment]
Hey @TanyaEychner !

Ok -you are close! All that needs to be done now is that you move your advice file (which is now in the root of the project folder) into the advice directory, and then in the Terminal / GitBash, add the change with `git add -A`, commit `git commit -m 'Your message here'` and push up your advice branch once more: `git push origin advice`.

If this doesn't work out for whatever reason, please email us at questions@skillcrush.com and we'll work on it together - or hop into one of our Dev Q&As for some live help!

Talk soon!!

Cheers,
Ann :)

**Comment by TanyaEychner** [comment]
Now I've broken something...I sent an email to the address above, but here is a preview of the crash message I'm getting. Yikes! 
image

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

Thanks for the screenshot! I sent a response to the email, but just in case I'm copying it below. If you have any questions, let us know!

Best,
Lisa

It looks like there's an index.lock file. When you start a commit, it creates a file called index.lock and sometimes this stays open when you close the terminal in the middle of a commit (either in the command line or if you're using Git in VS Code.)

In order to fix the issue, run this command:
`rm -f .git/index.lock`

Which will get rid of the index.lock file and you can proceed! 😀

**Comment by TanyaEychner** [comment]
Okay, that worked! I'm able to move around now, but still getting the same thing...aaarrrggghhh...it says it all up to date, but am I in the wrong place? Should I be in main and not it advice?
image

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

Thanks for the screenshot! It looks like the main branch was pushed, instead of the advice branch. Try running `git push origin advice` and see if your GitHub repo updates.

If it doesn't, can you run `ls` to show the files and folders in the root of the git-practice directory? Do you see your advice file in the root? 

Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @TanyaEychner, 

Just in case it helps, here's a screenshot of your repository showing the change to make. 👍 

Let us know if you have any questions! 


Screenshot 2023-10-31 at 5 14 36 PM (2)

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

I sent a message to you about the pull request from the main branch. But this is the branch we want to focus on. So I'm copying the message below. If you have any questions, let us know! 

Best,
Lisa

Message:
It looks like the changes were made on your main branch, instead of the advice branch. And we have two pull requests - one from the main branch and the other from the advice branch.

Can you check out the advice branch by running `git checkout advice`. Then check to be sure your advice branch is in the advice folder. (If you made the change only on the main branch, the change may not also be on the advice branch.)

Once your advice file is inside of the advice folder. Check once again that you're on the advice branch by running `git status`. You should see the branch name and any changes to be added and committed. Add the changes by running `git add -A` and commit them with `git commit -m "Your commit message"`. Then push the advice branch with `git push origin advice`. It will update your other pull request and we should be able to see your changes. 

You don't need to worry about pushing the main branch - we're really only concerned about the advice branch. So we don't need to resolve the conflict you saw in the command line before. 👍 

How does that sound? Let us know if you have any questions! 

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

WooHoo!!! Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
