### PR TITLE
Updated name, links

### PR DESCRIPTION
**Pull request by cnapua**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @cnapua,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by cnapua** [comment]
Thanks Lisa! I think I did it but am unsure...

**Comment by twosavoie** [comment]
Hi @cnapua,

I don't see the change yet. Can you check a few things for us? 

- Run **git branch** to be sure you're on the advice branch. 
- Next, check that the change to the index.html file in your text editor has been saved. 
- Run **git status** in the command line. Do you see changes to be added to staging (in red) or to be committed (in green)? If so, go ahead and add and commit them.
- Push the advice branch to GitHub.

If you're stuck, can you send us a screenshot of the command line to questions@skillcrush.com? We'll be able to go from there. 

Hang in there - you've got this!

Best,
Lisa

**Comment by cnapua** [comment]
Thank you for your patience! Will email...

**Comment by twosavoie** [comment]
Hi @cnapua,

Great job! The link has been added and pushed to GitHub and your pull request has been updated. Well done!

There's one more detail to take care of. Your advice branch now has an extra git-practice folder inside. Can you remove the folder (it can be moved to trash.) And then add the change with **git  add -A**, commit as you normally would, and push your advice branch to GitHub. 

Once that's done, we'll be all set to merge in your code! Let us know if you have any questions. 

Best,
Lisa
Screenshot 2023-07-11 at 12 30 09 AM

**Pull request merged**
