### PR TITLE
Advice update - Anne for Skillcrush

### PR DESCRIPTION
**Pull request by wesiptea**
Hi,

I am hoping this looks correct. I had a bit of trouble with pushing due to an accidental SSH-https address mix-up, so it has taken me a little time to correct that with Lisa's help. :) Let me know if you see anything I need to correct.

Thanks,
Anne

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @wesiptea!

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/anne-sk-advice.html file exists as part of this pull request. Perhaps it still needs to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by wesiptea** [comment]
Hi again,

Thanks for your patience and encouragement! I think I have resolved the issues now, but let me know what you see on your end.

Anne

**Comment by redrambles** [comment]
Hey @wesiptea,

Thanks for making that change, your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by wesiptea** [comment]
Hi Ann,

Thank you so much for this great news! Yahoo!!

Anne



Anne Spitler-Kashuba, M.S., CCC-SLP
Speech-Language Pathologist

**Pull request merged**
