### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Taylor-Monet**
Add my advice page

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Taylor-Monet,

This is a great start! Well done adding your advice file to the advice folder. 👍 

There are a few small changes to make before we can merge your code into the Skillcrush repo. No worries - you've got this!

- The main.css file has been deleted. Could you add it back, please.
- There's a conflict marker to be removed on line 1374.
- The casing in the link to your advice file doesn't match the name of the file. Can you change the link in the index.html file so that it also reads, Taylor-Savary-advice.html (with a capital T and S)

That's it! Once you've made those changes, add them with `git add -A`, commit as you normally would, and push your advice branch to GitHub. Your pull request will be updated automatically. 

Reach out if you have any questions!

Best,
Lisa

**Comment by Taylor-Monet** [comment]
Hi Lisa,

I’m a little turned around. Am I forking the main.css file from GitHub so
that I can add it back?

So Is it that what I would like to add to the upstream is not complete
because I deleted the main.css file? How do I see the original main.css
file on GitHub. I’m struggling to comprehend what I’m reading on GitHub.

**Comment by twosavoie** [comment]
Hi @Taylor-Monet,

No worries! I can see the main.css file on your main branch. If you merge the main branch into the advice branch, it should restore the file. 

You might look back at Step 8 of the lesson. You can follow those same steps to merge the main branch in. If you have any questions, let us know!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Taylor-Monet,

You're doing great, but unfortunately, we aren't seeing the main.css file restored. 

Let's try a more targeted approach.

1. Start by checking out the advice branch (if you aren't already there.)
2. Run `git checkout upstream/main css/main.css`
3. This will pluck the css/main.css file out of the upstream/main branch. 
4. Run `git status`. You should see the css/main.css file listed
5. Add the change with `git add -A` and commit the change with `git commit -m "Add main.css file"` (or something similar)
6. Push the advice file to your GitHub repo to update your pull request: `git push origin advice`

I know this can be frustrating. But hang in there. The silver lining here is that you're getting to see a bit more how Git and GitHub work under the hood. 🙂 

Reach out if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Taylor-Monet,

Or, if you prefer, while on the advice branch you can add the main.css file to the css folder I sent to your over Slack. Then add with `git add -A`, commit, and push the advice branch to GitHub. 👍 

Best,
Lisa

**Comment by Taylor-Monet** [comment]
Hi Lisa,

I'm not sure how to check to see if the main.css file is restored. Would it
show up when I "ls" my directory? Also, I can't re-read the instructions
for this assignment because I lost access to my account this week until I
can pay my subscription this upcoming Monday but thank you for all of your
help. I will reach back out on Monday but I did try again.

Best,

Taylor

**Comment by twosavoie** [comment]
Hi @Taylor-Monet,

Wow! Great job! You stuck with it and your pull request is approved. You should feel very proud of yourself!! 
(https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by Taylor-Monet** [comment]
Omg!! Really!!! Thank you so much!! I’m soooo excited!

**Pull request merged**
