### PR TITLE
Added Tiffany B

### PR DESCRIPTION
**Pull request by tiffy3b**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @tiffy3b,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by tiffy3b** [comment]
Thanks for accepting my pull requests.

I'm certainly missing a step. I never responded the last time cause I
thought after a pull request was accepted it was done. Lol.

So I just kept going and now confused where I left off on this. Looking
through my notes I have nothing written down about what to do after a pull
request.

If you could please give me some direction on how to add a link to my
index.html I would greatly appreciate it.

**Comment by twosavoie** [comment]
Hi @tiffy3b,

Happy to help! While in the advice branch, open the index.html file in your text editor. You can follow the format of the other links to link to `advice/tiffany-b-advice.html`. Save your work, then return to the command line. After adding and committing the changes, you can push the advice branch to your remote GitHub repo. 

Would you like to give that a try? Let us know if you have any questions!

🙂
Lisa

**Comment by tiffy3b** [comment]
Please let me know if it is there now.

**Comment by redrambles** [comment]
Hey @tiffy3b !

Thanks for making that change - everything looks good and your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
