### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Nico-Floriani**
Please let me know if I need any changes!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Nico-Floriani !

Congrats on your first pull request!

There are a couple of changes that you'll need to make here before we can merge this in:

1. It looks like you deleted some other students' links to their advice files. Those will need to be added in to preserve everyone's work.
2. The link to your advice file in the index.html file is outside of the closing </section> tag and instead, should be inside of it with the rest of the links.
3. There also isn't an advice page or any css. 

 If you could fix those things up, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Nico-Floriani** [comment]
Hello Sharon,

Thank you for pointing out where I went wrong!  I have a couple questions
though.

1.  I use Atom as a text editor.  When I see the code conflict markers
there are two fields, red and green, and there are buttons saying "Use
This" (or something like that).  Which one is the right one to include?

2.  Am I able to add a folder in Git, such as git add advice and git add
css, or do I add files individually, such as nico-floriani-advice.html and
nico-floriani.css?

Thank you again,
Nico

**Comment by redrambles** [comment]
Hello @Nico-Floriani !

1 - Editors will often give you the shortcut of choosing one version over another when resolving merge conflicts, but in many cases, we want to blend the two, or use parts of each. What we want to do here is make sure that you keep ALL the links, including your own.  You can reference the original repo to copy the few lines that were removed and pop those back in, and you'll be all set. If you prefer using a 'git' way to do this, you can run:
`git checkout upstream/main index.html`

This will pull in the version of the 'index.html' file as it is on the original repository that we are all contributing to, and then you can pop your link at the bottom of the list, and you're done. :)

2- When you add and commit changes, you can add the files that have changed individually, or you can use shortcuts like `git add -A` which will all _everything_ that has changed in one fell swoop. (My personal favorite) You can add folder names `git add advice` and this will add any files that have been modified  inside that particular folder. Of course you still need to make a commit once you have added your changes to the staging index.

Hope this helps - let us know if you have any questions!


Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @Nico-Floriani,

Everything looks good here, your code is merged in!

Cheers,
Ann :)

**Pull request merged**
