### PR TITLE
Tanya Eychner Advice

### PR DESCRIPTION
**Pull request by TanyaEychner**
I started from the beginning of the lesson and worked through the steps, but I don't know if I was able to push the tanya-eychner-advice into the advice folder...it doesn't look like it...please advise on how to do that...the add-commit-push steps are not making it  go there...I'm sure I'm missing a step but I don't know what it is. Thanks for your help!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @TanyaEychner !

You are very close! You are correct, the thing that remains here is that we need to move your `tanya-eychner-advice.html` file from the root of the project directory where it is now, to inside the `advice` directory. 

You will need to move the file into the advice directory in any way you prefer - using the FileExplorer or Finder, or the command line - and then run `git status`. You should see that Git noticed that the file was moved (typically it will show that a file was 'added' in the new location and that a file was 'deleted' from the previous one). Once you confirm this, add with `git add -A`, and then commit as per usual `git commit -m "Your message here"`. Then push up your branch once more, and the changes should make their way here, and we'll be able to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by TanyaEychner** [comment]
All looked good, but now I'm getting a new error...yikes!

image

**Comment by redrambles** [comment]
Hey @TanyaEychner !

Ok! So this means that your remote and local repo have gotten out of sync - usually because a change was made directly on GitHub. Can you show us the result of `git log --oneline` ? We'll go from there!

Cheers,
Ann :)

**Comment by TanyaEychner** [comment]
Hi! Sure...here is what it says:


Tanya@Tanya-HP MINGW64 ~/git-practice (main)
$ git log --oneline
b7050f6 (HEAD -> main) Advice for tanya eychner added
ca84f58 Deleted duplicate
f646961 Removed conflict
7833ef3 (upstream/main) Merge pull request #1160 from Darryl-J/advice
c9407b2 Merge branch 'main' into advice
c238029 Merge pull request #1163 from avictoriaj/advice
531a7aa Advice Added
10884df Took away test change
80f7939 test change
a6f5f8f added April's advice
b60d58d Merge pull request #1162 from lee77carter/advice
e16780d Merge branch 'main' into advice
f920a71 Merge pull request #1161 from janenag/advice
b29edc0 deleted indepentent HTML file
4233dda Added advice page, linked to index.html, and updated CSS page
9be8280 Janena's Lessons to Grow
bd1c105 (origin/main, origin/HEAD) Added tanya eychner advice
8f1aacb Added tanya eychner advice
4b30bb5 Janena's advice
2e4d8d3 upstream
1e817fd Janena's advice
419791b Merge pull request #1156 from GMHanlon/advice
c274c8b modified index.html
:...skipping...
b7050f6 (HEAD -> main) Advice for tanya eychner added
ca84f58 Deleted duplicate
f646961 Removed conflict
7833ef3 (upstream/main) Merge pull request #1160 from Darryl-J/advice
c9407b2 Merge branch 'main' into advice
c238029 Merge pull request #1163 from avictoriaj/advice
531a7aa Advice Added
10884df Took away test change
80f7939 test change
a6f5f8f added April's advice
b60d58d Merge pull request #1162 from lee77carter/advice
e16780d Merge branch 'main' into advice
f920a71 Merge pull request #1161 from janenag/advice
b29edc0 deleted indepentent HTML file
4233dda Added advice page, linked to index.html, and updated CSS page
9be8280 Janena's Lessons to Grow
bd1c105 (origin/main, origin/HEAD) Added tanya eychner advice
8f1aacb Added tanya eychner advice
4b30bb5 Janena's advice
2e4d8d3 upstream
1e817fd Janena's advice
419791b Merge pull request #1156 from GMHanlon/advice
c274c8b modified index.html
b507bf2 fix file structure
5067659 add advice to main
4eab648 Added my advice page to directory
32e39cc Merge pull request #1158 from AMartindale98/advice
a8227b1 Added advice html
2bc6cb5 Merge pull request #1157 from Yoko-Sc/advice
24826d3 Merge branch 'main' into advice
7d1aa63 eraced extra file
88b600b change name
7fb1707 Added my advice
abf4c5b Merge remote-tracking branch 'upstream/main' into advice
a17a63a Merge pull request #1155 from SChilian/advice
2b7c637 Merge branch 'main' into advice
2654684 Resolved index.html file conflict
57ef3af Merge pull request #1153 from sinclairc43/advice
303e490 Added chris sinclair advice html and css
83e7664 Merge pull request #1152 from shannawalsh/advice
1aea684 Adding link to Shanna's advice on new line
d7eb2dd Shanna advice
bde6dbc Added Sierra C's advice for beginners
e154bf9 Added Sierra C's advice for beginners
dd002ed Updates advice html file to include sierra's advice
48dcf7a added gillian-hanlon-advice.html to index html
3c2e105 added gillian-hanlon-advice.html
0b88217 Merge pull request #1150 from tkant763/advice
6ea0534 Added a link to my advice page to the index page
7c9cc1b Merge pull request #1151 from Victoria-Smith2720/advice
fbe0694 Merge branch 'main' into advice
b77bd6d Added br tag to a href
0fa8147 Created advice page and updated index.html
673e4a1 Added personal advice page
424384d Merge pull request #1149 from crtang/advice
97fd3fb Adding my advice page
4176557 Merge pull request #1147 from EmilyKArden/advice
49a61f6 Merge branch 'main' into advice

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

It looks like the changes were made on your main branch, instead of the advice branch. And we have two pull requests - one from the main branch (this one) and the other from the advice branch.

Can you check out the advice branch by running `git checkout advice`. Then check to be sure your advice branch is in the advice folder. (If you made the change only on the main branch, the change may not also be on the advice branch.)

Once your advice file is inside of the advice folder. Check once again that you're on the advice branch by running `git status`. You should see the branch name and any changes to be added and committed. Add the changes by running `git add -A` and commit them with `git commit -m "Your commit message"`. Then push the advice branch with `git push origin advice`. It will update your other pull request and we should be able to see your changes. 

You don't need to worry about pushing the main branch - we're really only concerned about the advice branch. So we don't need to resolve the conflict you saw in the command line before. 👍 

How does that sound? Let us know if you have any questions! 

Best,
Lisa

**Comment by TanyaEychner** [comment]
Okay, I think that maaayyyyybbbeeee I got it this time? Please advise with next steps - thanks so much!

**Comment by twosavoie** [comment]
Hi @TanyaEychner,

I'm closing this pull request since it was from the main branch. Great job working through the exercise! You showed excellent grit and determination!

Best,
Lisa

**Pull request closed without merging**
