### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Shanae-B**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Shanae-B,

Great work adding your advice and creating a CSS file! There are a couple of things we'd like you to do before we're able to merge your work into the Skillcrush repo.

Could you place your advice file into the advice folder? (You'll need to change the link to the css file when you do.) Then can you add a link to your advice file in the index.html file? 

Once you've made those two changes, add your changes to staging by running a slightly different git command (`git add -A`), commit, and then push your changes to GitHub. The update will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by Shanae-B** [comment]
Hello, Thank you so much for the feedback. Regarding your instruction to move my advice file to the advice folder. Are you referring to moving my advice file to the advice repository? Sent from my iPhoneOn Feb 6, 2023, at 12:34 AM, Lisa Savoie ***@***.***> wrote:﻿
Hi @Shanae-B,
Great work adding your advice and creating a CSS file! There are a couple of things we'd like you to do before we're able to merge your work into the Skillcrush repo.
Could you place your advice file into the advice folder? (You'll need to change the link to the css file when you do.) Then can you add a link to your advice file in the index.html file?
Once you've made those two changes, add your changes to staging by running a slightly different git command (git add -A), commit, and then push your changes to GitHub. The update will join your pull request here.
Let us know if you need any help!
Best,
Lisa

**Comment by redrambles** [comment]
Hello @Shanae-B !

Hope you don't mind if I jump in! Yes - we would like you to move your advice file from the root of the project directory where it is now, into the 'advice' directory, with all the other advice files. Once this is done -  please add the change on the command line with `git add -A` - then commit as per usual, and finally push up your `advice` branch once more , which will automatically update your pull request. 

Then we should be all set! Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Shanae-B** [comment]
Awesome!! I think I did it 😬… Please let me know if I need to keep working on this. Thanks so much for your help! Sent from my iPhoneOn Feb 6, 2023, at 9:38 AM, Ann Cascarano ***@***.***> wrote:﻿
Hello @Shanae-B !
Hope you don't mind if I jump in! Yes - we would like you to move your advice file from the root of the project directory where it is now, into the 'advice' directory, with all the other advice files. Once this is done -  please add the change on the command line with git add -A - then commit as per usual, and finally push up your advice branch once more , which will automatically update your pull request.
Then we should be all set! Let us know if you have any questions!
Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hi @Shanae-B,

Great job! The advice file is just where it should be. 👍 

Next, can you add a link to your advice file to the index.html file? Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by Shanae-B** [comment]
Ok, I think I've pushed the updates through now. Please let me know if any changes are needed. Thank you so much for your help! 



    On Monday, February 6, 2023 at 07:01:55 PM EST, Lisa Savoie ***@***.***> wrote:  
 
 


Hi @Shanae-B,

Great job! The advice file is just where it should be. 👍
 
Next, can you add a link to your advice file to the index.html file? Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Shanae-B, 

You're very close! We'd like you to add a link to your advice file to the index.html file that's in the root of the project folder. Your link will join the others here: [https://github.com/Shanae-B/git-practice/blob/advice/index.html](url)

Once you've added the link, can you remove the extra shanae-brooks-advice.html file that's in the root of your project folder? Then add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa
Screenshot 2023-02-08 at 12 33 04 AM (2)

**Comment by Shanae-B** [comment]
I thought 4th time would be the charm, but doesn't seem like it. Can you please review and tell me what I did wrong here? How should I proceed? 



    On Wednesday, February 8, 2023 at 01:38:26 AM EST, Lisa Savoie ***@***.***> wrote:  
 
 


Hi @Shanae-B,

You're very close! We'd like you to add a link to your advice file to the index.html file that's in the root of the project folder. Your link will join the others here: https://github.com/Shanae-B/git-practice/blob/advice/index.html

Once you've added the link, can you remove the extra shanae-brooks-advice.html file that's in the root of your project folder? Then add the change with git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by redrambles** [comment]
Hello @Shanae-B !

Ok, no worries! Can you send us an email at questions@skillcrush.com with a screenshot of the result of 'git status' ?

We'll go from there! :)

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hi @Shanae-B,

Just in case it's helpful, this is the file to be removed (see attached.) Once it's removed, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa
Screenshot 2023-02-11 at 5 51 46 PM

**Comment by Shanae-B** [comment]
Hi Lisa, 
I thought I already removed this file. Is the screenshot from GitHub? Any chance you are able to provide steps to remove the file? I don't believe the process I am taking is working. Your assistance is appreciated. 
    On Saturday, February 11, 2023 at 06:54:40 PM EST, Lisa Savoie ***@***.***> wrote:  
 
 


Hi @Shanae-B,

Just in case it's helpful, this is the file to be removed (see attached.) Once it's removed, please add the change with git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @Shanae-B,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
