### PR TITLE
added Reem's advice

### PR DESCRIPTION
**Pull request by Reemers**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Reemers,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @Reemers,

I thought I would continue the conversation here. Great job merging the main branch into the advice branch!

It looks like your advice file is missing from the advice folder. If you see it in the advice folder locally, can you run **git status**? It may be that the change hasn't been added to staging or committed yet. (Only changes that have been added and committed are moved to GitHub when you push.)

Once you're ready, go ahead and push the advice branch to GitHub and it will update your pull request automatically. Let us know if you have any questions!

Best,
Lisa

**Comment by Reemers** [comment]
Hi Lisa,

Thanks for taking a look. I just staged and committed the advice branch. then ran git push origin advice. I hope everything looks ok on your end!

**Comment by Reemers** [comment]
Screen Shot 2022-08-29 at 1 32 06 PM

**Comment by Reemers** [comment]
Also, yes, Reem-Skill-advice.html is located locally in the advice folder.

**Comment by twosavoie** [comment]
Hey @Reemers,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
