### PR TITLE
Added personal advice to main index file

### PR DESCRIPTION
**Pull request by WhillV**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @WhillV,

Great job! This is super close!

Take a look at your advice file's name. Can you add a dash between **Hill** and **V** so it matches the link in the index.html file? Also, there's an extra .html extension on your advice file you'll want to remove.

Once you've made those tiny changes, save the file, add it with git add -A or git add index.html, make your commit as usual and finally push up your advice branch once more, automatically updating this pull request.

Then we'll be all set to merge in your code! Let us know if you have any questions!

Best,
Lisa

**Comment by WhillV** [comment]
I believe that I updated the file correctly and pushed it to the advice branch as I did in the previous steps.

**Comment by twosavoie** [comment]
Hi @WhillV,

You're super close! One more step and you'll be finished. Can you remove the advice/Winter-Hill V-advice.html.html (The file without the dash and with the extra extension? You can see it [here](https://github.com/skillcrush/git-practice/pull/1112/files) in the sidebar on the left.)

Once you've made that change, add it with `git add -A`, commit the change, and push up your advice branch once more, automatically updating this pull request.

I hope that helps! Let us know if you have any questions!

Best,
Lisa

**Comment by WhillV** [comment]
Hi Lisa, I apologize for the delayed response. I deleted the file and pushed it back to git. So hopefully I did it correctly. Thanks again for your assistance.

**Comment by twosavoie** [comment]
Hey @WhillV,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by WhillV** [comment]
Thank you for all your help! I truly appreciate it. Lol, I thought I wasn't going to be able to get it correctly, but lo and behold, here we are.

**Pull request merged**
