### PR TITLE
Changed name

### PR DESCRIPTION
**Pull request by Dylanvanoevelen**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Dylanvanoevelen !

This is great - we only need a few things before we can merge this in.

1) Your `dylan-vanoevelen-advice.html` file is sitting in the root of the project at the moment, but we need it to be inside the `advice` directory. Please move it in there.

2) Your link in the index.html file is using curly quotes instead of straight quotes. The difference is hard to see unless you have learned to spot it over time. Compare your quotes with those of the link above. Curly quotes unfortunately aren't well interpreted by computers and tend to break things, so I strongly suggest that you change your curly quotes over to straight quotes.

Once you have made these small changes, please add them with `git add -A`, commit as per usual and finally push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Dylanvanoevelen** [comment]
i think i have corrected those issues if you could check and let me know?

**Comment by Dylanvanoevelen** [comment]
i have pushed the advice page to github so should be sorted now... i think haha

**Comment by acodeinprogress** [comment]
Hi @Dylanvanoevelen,

Thanks for pushing up your latest code.

I see that you moved your advice file to the advice folder but there is still an extra copy in the root folder of your project. If it doesn't show on your computer, you'll need to run `git add -A` to remove it from Git.

I also noticed that you replaced another student's link in the index.html file with your own. You can see it listed in the index.html file by clicking on the [Files Changed tab](https://github.com/skillcrush/git-practice/pull/412/files) near the top of this page.

We want to preserve everyone's work so we'll need for you to add that back in before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by Dylanvanoevelen** [comment]
hello. sorry i seem to be struggling with this bit. i have deleted the advice.html from root folder so it is only in advice folder. i have also changed the index.html so it includes the other users advice page (apologies it must have been a mistake when i took that out). i have added and commit changes to both but wont let me push them to github. are you able to help me with this please?

**Comment by redrambles** [comment]
Hey @Dylanvanoevelen !

Happy to help with this! I'd like to know more about the issue with pushing up to GItHub. Can you send us a screenshot of the result at questions@skillcrush.com? It's easier to share screenshots by email. Then we'll go from there!

Talk soon!
Cheers,
Ann :)

**Comment by Dylanvanoevelen** [comment]
i have sent an email with the issues, thank you.

**Pull request merged**
