### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by bh-codes**
Am I supposed to be doing something else to this or am I waiting for someone to get back to me? I feel so lost with Git!

### CODE REVIEW

**Comment by bh-codes** [comment]
Am I supposed to be doing something else to this or am I waiting for someone to get back to me? I feel so lost with Git!

**Comment by redrambles** [comment]
Hey @bh-codes !

This is a great start - we just a few things to address before we can merge this in.

1) You have two advice files at the moment - one in the the advice directory (good!) and another in the root of the repository (oops!). Please remove the one that is in the root of the project directory.

2) If you have a look at the change set for your pull request here: https://github.com/skillcrush/git-practice/pull/553/files - and you scroll down to the index.html file, you'll notice that though you successfully added your link to your advice file, 3 student links were deleted (they will be highlighted in red on the left hand side). This most likely happened when you were resolving a merge conflict - it happens!! Please add those links back into the index.html file (you can copy/paste them from the change set)

Once you have made those changes, add them with `git add -A`, commit as per usual and push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by bh-codes** [comment]
Got it! I deleted the root index copy and added back the 3 student links and I pushed my advice... Hope I did it right this time!
Thank you so much, Ann!

**Comment by twosavoie** [comment]
Hey @bh-codes,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
