### PR TITLE
Added sound advice from sarah

### PR DESCRIPTION
**Pull request by Sarah-C-Arvin**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Sarah-C-Arvin,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by Sarah-C-Arvin** [comment]
Hi Sharon!
I added my link, added, committed, and pushed the index.html file, and
according to my command line, everything went through fine. However, on
GitHub, it says my commit is conflicting with another index.html file. I
went through the steps from the Resolving Conflicts lesson, however, the
conflict does not show up in my text editor, only on GitHub. So I'm not
sure how to resolve this one. I attached a screenshot of my command line
and the conflict message I'm seeing on GitHub.

**Comment by redrambles** [comment]
Hey @Sarah-C-Arvin !

Everything went through fine, well done! However - unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :)

Please remove the image and update the advice file to point to a hosted one (or remove the image tag altogether if you prefer). Then add your changes with `git add -A` - commit as per usual and push up your `advice` branch once more. 

It's normal that GitHub will  indicate that conflicts exist in the index.html file, because with every new pull request, a student adds another link to that file. We are happy to resolve these things on our end - but if you'd like to have some practice doing it yourself, you can fetch from upstream, merge upstream/main into your main branch and then merge your updated main branch into your advice branch. The conflict will then manifest and you can resolve it (which essentially involves making sure to keep all the students' links and removing the conflict markers). Once you have done so, you can add your changes, commit and push up your advice branch again, and Github won't indicate that there are conflicts remaining (at least for a while, until another student pushes up their code. :) This is the fun of evolving code bases!)

​Keep us posted on your progress and let us know if you have any qs!

Cheers,
Ann :)

**Comment by Sarah-C-Arvin** [comment]
Ahh, that makes sense! I’ll take a look at all that later today. Thanks so much!

**Comment by redrambles** [comment]
Hey @Sarah-C-Arvin !

Thanks so much for making that change, we are all set and your code is merged in! 🎉

**Pull request merged**
