### PR TITLE
Added my name and link to advice page

### PR DESCRIPTION
**Pull request by Aracely-C**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Aracely-C,

Looks great! I only have 1 tiny request for you.

We would like for your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by Aracely-C** [comment]
Hi there,

I’m not sure I understand what advice file needs to go in the advice folder. Is this on the command line?

**Comment by Aracely-C** [comment]
Actually I think I got it. I saw what you were saying. Here’s a screen shot.

**Comment by redrambles** [comment]
Hey @Aracely-C !

Woo - I see your file in the advice folder - amazing!!! We just need to delete the duplicate that is still sitting inside the root of the project folder. Once you delete it, add that change with `git add -A`, commit as per usual `git commit -m "Your message here"` and then push up your advice branch once more `git push origin advice`

And we should be all set! Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Aracely-C** [comment]
A duplicate advice html? I’m not seeing that I don’t think.

**Comment by twosavoie** [comment]
Hi @Aracely-C,

I wonder if you're looking at the main branch? Try checking the advice branch. In the root, there's a file named aracely-cortez-advice.html that can be removed. (You'll leave the file that's in the advice folder.)

Let us know if you have any questions! 

xoxo,
Lisa

**Comment by Aracely-C** [comment]
I’m still not seeing that in the folder, here is a screenshot.

Thank you!

**Comment by twosavoie** [comment]
Hi @Aracely-C,

Unfortunately, we aren't able to see the screenshot. Could you email it to us at questions@skillcrush.com or upload it in the Student Slack channel? We would be happy to take a look!

xoxo,
Lisa

**Comment by redrambles** [comment]
Hey @Aracely-C,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
