### PR TITLE
Added Haruna Bulus Advice html and css files

### PR DESCRIPTION
**Pull request by Harobulus**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Harobulus,

This is a great start! You're super close!

It looks like the advice folder has been renamed. Can you change it back so that it's named **advice**? Next, take a look at the link to your advice file in the index.html file. You'll want to change the name of the advice file in the link to all lowercase.

Once you're finished, run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Harobulus,

It looks like a change was made, but the advice folder is still named **advice/Haruna-Bulus-advice.html/haruna-bulus-advice.html** Can you remove Haruna-Bulus-advice.html so that the folder is named advice? 
Screenshot 2023-02-15 at 12 09 44 AM (2)

Once you've made the change, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by Harobulus** [comment]
Hi Lisa, I have renamed the advice folder. Please confirm if pull request has been updated and if my code can be merged. Thank you. Kind regards, Haruna From: Lisa SavoieSent: Wednesday, February 15, 2023 7:15 AMTo: skillcrush/git-practiceCc: Harobulus; MentionSubject: Re: [skillcrush/git-practice] Added Haruna Bulus Advice html and css files (PR #923) Hi @Harobulus,It looks like a change was made, but the advice folder is still named advice/Haruna-Bulus-advice.html/haruna-bulus-advice.html Can you remove Haruna-Bulus-advice.html so that the folder is named advice?Once you've made the change, please add the change with git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.Then we should be all set to merge in your code. Let us know if you have any questions!Best,Lisa—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by twosavoie** [comment]
Hi @Harobulus,

Well done! You did great!

Since you closed the pull request, updating your GitHub repo didn't update the pull request we receive. Can you issue another? Once we have it, we'll have a look!

Let us know if you have any questions! 

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Harobulus,

I went ahead and opened the pull request for you. 

It looks like the folder was changed from Haruna-Bulus-advice.html. to advice.html. Can you remove your advice file, **haruna-bulus-advice.html**, from the advice.html folder and add it with the other advice files in the advice folder? Then you can delete the advice.html folder. 

Once you've made that change you can run `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Reach out if you have any questions! Keep going - you're almost there! 

Best,
Lisa
Screenshot 2023-02-15 at 10 27 54 AM

**Comment by Harobulus** [comment]
Thanks Lisa, Updates implemented. Still wondering how I closed the pull request. Thanks for again for all the trouble. Kind regards, Haruna From: Lisa SavoieSent: Wednesday, February 15, 2023 5:31 PMTo: skillcrush/git-practiceCc: Harobulus; MentionSubject: Re: [skillcrush/git-practice] Added Haruna Bulus Advice html and css files (PR #923) Hi @Harobulus,I went ahead and opened the pull request for you.It looks like the folder was changed from Haruna-Bulus-advice.html. to advice.html. Can you remove your advice file, haruna-bulus-advice.html, from the advice.html folder and add it with the other advice files in the advice folder? Then you can delete the advice.html folder.Once you've made that change you can run git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.Reach out if you have any questions! Keep going - you're almost there!Best,Lisa—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by twosavoie** [comment]
Hey @Harobulus,

No trouble at all! We're always happy to help. You did a great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by Harobulus** [comment]
Thanks for the support Lisa. Kind regards, Haruna   From: Lisa SavoieSent: Wednesday, February 15, 2023 8:49 PMTo: skillcrush/git-practiceCc: Harobulus; MentionSubject: Re: [skillcrush/git-practice] Added Haruna Bulus Advice html and css files (PR #923) Hey @Harobulus,No trouble at all! We're always happy to help. You did a great job! Your code is all merged in.Best,Lisa—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Pull request merged**
