### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Raahknee**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Raahknee !

This is a great start!! I have a few requests and then we'll be all set to merge this in.

1) Right now your `raanee-black-advice.html` file is sitting in the root of the project folder, but we want it to be inside the `advice` directory, with all the other advice files. Please move it in there.

2) The value of the href property in your link on the advice page is surrounded by curly quotes `””` instead of straight quotes `""` - which isn't recognized by the browser in the same way and will cause the link to break. Please swap those out for straight quotes.

Once you have made those two changes, please add with `git add -A`, commit as per usual and finally push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hi @Raahknee,

Just checking to see if you have any questions or need any help with this pull request. 😄 

Best,
Lisa

**Comment by Raahknee** [comment]
Hello, did I fix it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by twosavoie** [comment]
Hi @Raahknee,

Great job changing the curly quotes to straight quotes. The next step would be to move your advice file **raanee-black-advice.html** into the advice folder where it will join the other students advice files. 

Once you have made that change, please add with **git add -A**, commit as per usual and finally push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Best,
Lisa
Screenshot 2023-08-02 at 1 10 11 AM (2)

**Comment by redrambles** [comment]
Hey @Raahknee !

Thanks for making those changes, your code is merged in! 🎉

Cheers,
Ann :)

**Comment by Raahknee** [comment]
Great, thank you so much!

**Pull request merged**
