### PR TITLE
Added swoulfe page

### PR DESCRIPTION
**Pull request by swoulfe**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @swoulfe!

Congratulations on making your first pull request!

It looks like there are some merge conflict errors in the index.html file. You'll need to remove those before we can get this merged in. You can see where they are by looking at the [Files changed](https://github.com/skillcrush/git-practice/pull/280/files) tab near the top of this page.

Once you make those changes, you can add, commit, and push your work up to GitHub. They will join your pull request here and we can merge in your work to the main codebase.

xoxo,
Sharon

**Comment by swoulfe** [comment]
Hi Sharon,

Thank you for your help! I think I have fixed it as of right now.

Thanks again!

**Comment by redrambles** [comment]
Hey @swoulfe !

Hmm - I'm not seeing the changes on my end - see here: https://github.com/skillcrush/git-practice/pull/280/files

Do you remember saving the file, then adding and committing and then pushing up your branch again? Want to give that one more try? Let us know how it goes!

Cheers,
Ann :)

**Comment by swoulfe** [comment]
I went back through and pushed it again and it looks like it's up to date. Does it look that way on your end?

Thank you!

**Comment by redrambles** [comment]
Hey there!

Ok! so we can see your latest changes here: https://github.com/skillcrush/git-practice/pull/280/files

You'll notice that there are two advice files. You are linking to `advice/swoulfe-advice.html` in the index.html file, so let's get rid of `advice/stephanie-woulfe-advice.html`. 

Once you have delete that file, let's take a closer look at the index.html file. Do you see on lines 224, 226 and 254 there are conflict markers? You will want to delete these and save the file.

Next, run `git status`. You should see two changes: The `advice/stephanie-woulfe-advice.html` file that you deleted and the `index.html` file that you modified in order to remove the conflict markers. Now we want to add those changes with `git add -A` - then commit as per usual `git commit -m 'Your message here'` and finally push up your `advice` branch once more `git push origin advice`

Then we should be all set. Keep us posted - nearly at the finish line!

Cheers,
Ann :)

**Comment by swoulfe** [comment]
You are a life saver! I think it's finally all set. Thank you for all of your help!

**Comment by redrambles** [comment]
Hey @swoulfe !

Thanks for making those changes - all good here! Your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
