### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by otterc1ty**
I added my advice to the page as a contributing Skillcrush student

### CODE REVIEW

**Comment by otterc1ty** [comment]
I accidentally have two of the same commit, how do I delete one? Also I forgot to put a <br> after my advice and I'm trying to fix it in the text editor but it won't let me save my changes.

**Comment by twosavoie** [comment]
Hi @otterc1ty,

Congratulations on making your first pull request!

This is a great start! The second commit is just fine. 👍 

I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great! Once you do, you can add, commit, and push your code to GitHub. It will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by otterc1ty** [comment]
> Hi @otterc1ty,
> 
> Congratulations on making your first pull request!
> 
> This is a great start! The second commit is just fine. 👍
> 
> I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great! Once you do, you can add, commit, and push your code to GitHub. It will join your pull request here.
> 
> Let us know if you need any help!
> 
> Best, Lisa

Hi Lisa, I'm new to GitHub so I sent you an email because I'm not sure you'll be notified of this message if I send it. All my questions are in my email (brsleah27@gmail.com)

**Comment by twosavoie** [comment]
Hi @otterc1ty,

Welcome to GitHub!! Responding here is the best way to ask questions about your project.  I'll be able to see any replies you send. And all of your questions will be in one place, in case someone else reviews your pull request. If you want to add images, etc. you could send an email to questions@skillcrush.com instead. 

I've taken a look at the advice branch on your GitHub repo and I don't see your advice file in the advice folder. And you can see the pull request [here](https://github.com/skillcrush/git-practice/pull/1288/files) that shows any changes to your project that you would like merged into the Skillcrush repo. There could be a couple of reasons you see it in File Explorer but not here. 

- The advice file you see is on the main branch, not the advice branch
- Your advice file hasn't been added and committed. Only committed changes are pushed to GitHub.

The next step is to go to your command line and run `git status`. This will show you any outstanding changes that are ready to be added and committed. If there are any, like your advice file, go ahead and add, commit, and push. (You can add all changes by running `git add -A`)

If there aren't any outstanding changes, take a look at which branch you're on. Be sure that you're on the **advice** branch and have a look again at the project folder. Do you see your advice file? If it isn't there, you can also check out the main branch. If it's there, merging the main branch into the advice branch should make it so that it's on both branches. 

I can see the <br> tag at the end of your link and in the code in your pull request. So you're good to go there! It looks like there are changes to be saved in your index.html file.

You only need to add your own CSS if you want to. It's completely fine to leave this for now. If you do want to and need some help with this, let us know! We're happy to clarify anything you need.

I hope that helps! Reach out if you have any questions!

Best,
Lisa

Screenshot 2024-06-11 at 11 02 28 PM

**Comment by otterc1ty** [comment]
Hi Lisa,

You were right! I checked the git status under the repository in GitBash
and it turns out the advice file wasn't staged and committed.

So far I have staged and committed the file but it won't let me push the
changes to GitHub because I get hit with this error message:
[image: Screenshot (49).png]

What should I do next?

Thank you for helping out,
Leah

**Comment by twosavoie** [comment]
Hi @otterc1ty,

Let's take a look! Unfortunately, you aren't able to upload screenshots here. Can you send it to us at questions@skillcrush.com? We'll be able to go from there. 👍 

Best,
Lisa

**Comment by otterc1ty** [comment]
Sure thing, I sent the email just now!

**Comment by twosavoie** [comment]
Hi @otterc1ty,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @otterc1ty,

You did it!! Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by otterc1ty** [comment]
Thank you so much! Is there a reason I wasn’t able to see it?

**Comment by twosavoie** [comment]
Hi @otterc1ty,

I sent a response to your email. I think it may have been that you're not used to GitHub yet and weren't sure where to look for it. I sent a link to the commit you made so that you can see it. But if you have any questions, let us know! 🙂 

Best,
Lisa

**Pull request merged**
