### PR TITLE
Added link to Maria's advice

### PR DESCRIPTION
**Pull request by mariateresepettersson**
Added a link to maria-pettersson-advice.html

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @mariateresepettersson,

This is a great start! I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great! Once you do, you can add, commit, and push your code to GitHub. It will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by mariateresepettersson** [comment]
Hi Lisa, I'm not really sure what you mean by an advice page because I did
create a maria-pettersson-advice.html and I saved it in the advice folder.
I thought that the CSS was optional.

I'm confused about what I should do now.

Regards,
Maria

**Comment by twosavoie** [comment]
Hi @mariateresepettersson,

Great to hear from you! I don't see the maria-pettersson-advice.html in the advice folder. Do you see it locally while on the advice branch? If so, can you run **git status** in the command line to see if there are any changes to be added and committed and/or changes to be pushed to GitHub. If so, go ahead and then push your code to GitHub. Your pull request will be updated automatically.

You can then look in the advice folder in your GitHub repo. Do you see the advice file? Is so you're good to go!

And you're right - you don't need to add a css file.  👍 

I hope that helps! Let us know if you have any questions.

Best,
Lisa

**Comment by mariateresepettersson** [comment]
I pushed it again but I'm kind of lost in the process tbh.

**Comment by redrambles** [comment]
@mariateresepettersson - what do you see when you run `git status` ?

Do you see that your advice file is listed there? If so - you will need to add it first, and then make a fresh commit, and then push up again.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by mariateresepettersson** [comment]
Hi,

I did this earlier today:
[image: Screenshot 2023-07-24 at 13.08.19.png]

I thought that I had solved it :/ Now when I run git status it says:

*➜  **git-practice* *git:(**main**)* git status

On branch main

Your branch is up to date with 'origin/main'.


nothing to commit, working tree clean

*➜  **git-practice* *git:(**main**)*


Best Regards,

Maria

**Comment by twosavoie** [comment]
Hi @mariateresepettersson,

I wonder if you're on the main branch instead of the advice branch? Can you run **git branch** to check? If you're on the main branch, you can check out the advice branch and run **git status**. 

Best,
Lisa

**Comment by mariateresepettersson** [comment]
Well I changed to the main branch because there wasn't anything to update
on the advice branch. Now that I checked my local directory my
maria-pettersson-advice.html file is gone... how can it disappear just like
that?

**Comment by twosavoie** [comment]
Hi @mariateresepettersson,

Do I understand correctly that you switched to the main branch before looking? If so, can you switch to the advice branch and see if the file is there. If not, you can go back to the previous lesson, download a file, and add it to the advice folder. 

Since you're adding the file to your project while you're on the advice branch, the file only exists in the project folder in the advice branch's version of your code. It wouldn't exist in the main branch's version of your code unless the advice branch is merged into the main branch, which we don't do in this lesson.

Does that help?

Best,
Lisa

**Comment by mariateresepettersson** [comment]
Hi again,

well not really. I don't know how to proceed. I downloaded the file again
and I tried to merge but I keep on getting error messages.
[image: Screenshot 2023-07-28 at 10.50.06.png]

I'm just trying to follow the instructions. It says that I should checkout
to the main branch but when I run that command I get the message that my
advice file would be overwritten.

What should I do? Do I only need to push the advice branch to my repo?

Best Regards,
Maria

**Comment by mariateresepettersson** [comment]
I made some more changes, trying to push the advice branch and also fixing
the errors in the index.html file. But still, I'm doubting that I've done
the correct thing.
[image: Screenshot 2023-07-28 at 11.03.54.png]

Regards,
Maria

**Comment by twosavoie** [comment]
Hi @mariateresepettersson,

Unfortunately, we aren't able to see an attachment here in GitHub. Could you send it to us via email at questions@skillcrush.com? We'll be able to go from there!

You might also consider attending a [Live Q&A](https://learn.skillcrush.com/events/) to meet with an instructor. You can share your screen and we can take a look at what you see in the command line.

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @mariateresepettersson,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
