### PR TITLE
created jody depp advice page updated main index file with my link an…

### PR DESCRIPTION
**Pull request by JoDepp**
…d added my css page

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @JoDepp !

This is fantastic!! The only thing I'd like you to change in is in the index.html file, I see you've added some changes to our name but "Skillcrush" doesn't take a capital 'c'. :) Once you make those quick changes, save the file, add and commit once more, and we will be all set to merge in your code! ✨

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by JoDepp** [comment]
Ok, I added and committed the index.html file that I had to fix. Should I merge and Push just the index file I fixed or the whole git-practice file?

Thanks, Jody

**Comment by twosavoie** [comment]
Hi @JoDepp,

You can push up your advice branch once more, which will automatically update this pull request.
Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @JoDepp,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
