### PR TITLE
Added Suzanne's advice

### PR DESCRIPTION
**Pull request by suzannem-dev**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @suzannem-dev,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by suzannem-dev** [comment]
Uh oh! That's interesting. I thought I added advice to the index.html... I didn't think some css was required, but I'll go ahead and make one.

**Comment by suzannem-dev** [comment]
I think I added the advice page and css now... did I do it right?

**Comment by suzannem-dev** [comment]
I think I added the advice page and css now... I'll go ahead and try another pull request.

**Pull request closed without merging**
