### PR TITLE
My advice page

### PR DESCRIPTION
**Pull request by seannotshawn**
I am trying to merge my 'advice' page into the SkillCrush 'main' branch. Thank you!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @seannotshawn !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by seannotshawn** [comment]
Hi Ann,

I'm kind of confused, when i open it up in VSC or in my browser, I see the
link and it's active. Maybe i'm confused about what you're asking?

Sean

**Comment by twosavoie** [comment]
Hi Sean,

Can you check to be sure that you're on the advice branch when you check the index.html file? Then after adding and committing, push the advice branch to your GitHub repo. 🙂 

Best,
Lisa

**Comment by seannotshawn** [comment]
Hi Lisa,

I believe it's all good now? Do I have to resubmit the pull request? Below
is my command line:

Seans-MacBook-Air:advice seanbonow$ pwd
/Users/seanbonow/documents/skillcrush/git/git-practice/advice
Seans-MacBook-Air:advice seanbonow$ git branch
* advice
  main
Seans-MacBook-Air:advice seanbonow$ git status
On branch advice
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

modified:   ../index.html

no changes added to commit (use "git add" and/or "git commit -a")
Seans-MacBook-Air:advice seanbonow$ git add -A
Seans-MacBook-Air:advice seanbonow$ git commit -m "Committing changes after
verifying index.html is under advice branch"
[advice caa489b] Committing changes after verifying index.html is under
advice branch
 1 file changed, 1 insertion(+)
Seans-MacBook-Air:advice seanbonow$ git push origin advice
Enter passphrase for key '/Users/seanbonow/.ssh/id_rsa':
Enter passphrase for key '/Users/seanbonow/.ssh/id_rsa':
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 363 bytes | 363.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:seannotshawn/git-practice.git
   5cdb035..caa489b  advice -> advice
Seans-MacBook-Air:advice seanbonow$

**Comment by twosavoie** [comment]
Hey @seannotshawn,

Great job! Once your code was pushed to the advice branch, your pull request was updated. Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Comment by seannotshawn** [comment]
Good to hear! Thank you! :)

**Pull request merged**
