### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by nicolekovacs**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @nicolekovacs !

This is amazing - the only thing is that you have curly quotes instead of straight quotes around the link address to your advice file in the index.html. Curly quotes are the bane of every dev's existence - as, of course, they tend to break everything.:)



Once you fix those, add and commit your change and then push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by nicolekovacs** [comment]
Hi Ann,

Thank you for getting back to me!

So I think I did manage to edit, add and commit then finally push it to the
remote repo. I hope that it's all right, I was kind of unsure if I did it
the right way and probably didn't the first try. Can you confirm to me if
all is well or something else needed? Thank you! 😇

Ps.: Can we abolish curly quotes? 🤔😄

Nicole

Ann Cascarano ***@***.***> ezt írta (időpont: 2021. nov. 25.,
Cs, 15:32):

**Comment by redrambles** [comment]
Hey @nicolekovacs !

I hear you - curly quotes are no fun!!

However I'm not seeing any changes here on my end. Are you sure you pushed up your 'advice' branch? `git push origin advice` ?

**Comment by nicolekovacs** [comment]
Hiii,

Okay, so it seems like I don't know what's wrong.
I did go back now and pushed it again with git push origin advice, after
changing to the git-practice directory, but I also can see it from a few
days ago on this link:
https://github.com/skillcrush/git-practice/pull/408/commits/f1d03c449b7b6d131c164fd2709e19adb3b3c086
Or is that now what I should be looking at?
My apologies and thank you for the help!

Nicole

Ann Cascarano ***@***.***> ezt írta (időpont: 2021. nov. 29.,
H, 18:57):

**Comment by acodeinprogress** [comment]
Hi @nicolekovacs!

This looks great! Yes, if you made the changes a few days ago but just pushed to GitHub, it will show the date of your commit rather than the date of the push.

Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Sharon

**Pull request merged**
