### PR TITLE
Added Viet advice html and css file, Added link to index.html

### PR DESCRIPTION
**Pull request by viet-v**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @viet-v !

I LOVE :heart:  your advice - and your pull request is just fine, file wise - but I'd like to ask you to make your link in the index.html file have just something like "Viet's advice" - and instead move that extra (really great) advice into your advice file itself. 

Once you have made that change, save your file and then add and commit the change. Push up your `advice` branch once more and this pull request will automatically be updated. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by viet-v** [comment]
Hi Ann!

I've modified the advice, thanks for your support!

Have a great day!

Viet.

**Comment by redrambles** [comment]
Hey @viet-v !

Thanks for making those changes, your code is merged in! 🎉

**Comment by viet-v** [comment]
Thank you Ann @redrambles !

**Pull request merged**
