### PR TITLE
Added Simon's wise Advice

### PR DESCRIPTION
**Pull request by simonhtz**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @simonhtz,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by simonhtz** [comment]
Hi Lisa

Thanks for the feedback. I'm not sure what to do though.
I thought I added and pushed the link already, it shows in my file anyway.
I tried to do the same again but I'm unsure how. It says it's all up to date. 

Can you help how to proceed? Thank you

Simon

**Comment by twosavoie** [comment]
Hi @simonhtz,

Just to be sure, when on the advice branch and you look at the index.html file, you see a link to this advice file: advice/simon-hasenfratz-advice.html? And your code has been saved in your text editor? 

If so, can you go to the command line and make sure you're in the advice branch and that all changes have been added to staging and committed by running **git status**. If you see any changes that need to be added and committed, go ahead and do so. Then push to GitHub by running **git push origin advice**. 

In case it helps, you can see the changes in your pull request here: https://github.com/skillcrush/git-practice/pull/885/files

If everything looks as it should can you also run **git remote -v** and send us a screenshot of your command line and a zip file of your code to questions@skillcrush.com? We'll be able to go from there. 🙂

Best,
Lisa

**Comment by redrambles** [comment]
Hey @simonhtz !

Thanks for making those changes - your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
