### PR TITLE
added Sherlan Joseph advice folder

### PR DESCRIPTION
**Pull request by sherlluv**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @sherlluv !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/sherlan-joseph-advice.html` file exists as part of this pull request. Perhaps it still needs to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hey @sherlluv,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by sherlluv** [comment]
Didn't i complete it?

**Comment by twosavoie** [comment]
Hi @sherlluv,

Great to hear from you! It looks like you made a change on the main branch, but the advice branch hasn't been updated. Once you make the change on the advice branch also, you can add and commit the changes and then push your code to GitHub. Your Pull Request will automatically be updated.

Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @sherlluv,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
