### PR TITLE
Added Jane Molphy advice.

### PR DESCRIPTION
**Pull request by JMM-Mack**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @JMM-Mack !

This is a great start!! Just a few things:

1) We need your `jane-molphy-advice.html` file to be inside the `advice` directory. Right now it is in the root of the project folder.

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you move your advice file and add your link to the index.html file, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @JMM-Mack !

Great work!!! We are super close! The only thing we need to do now is delete the extra copy of your advice file which is still in the root folder `jane-molphy-advice.html`. Once you remove it, add the change with `git add -A` - then commit as per usual, and then once again push up your advice branch, which will update this pull request with that latest change. Then we should be all set to accept and merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by JMM-Mack** [comment]
Geez, I've made a real mess of this, haven't I????
Hope I've fixed it now. Thanks for your patience and help.

**Comment by redrambles** [comment]
Hey @JMM-Mack !! ✨ 

Thanks so much for making that last change, everything is good now! Your code is merged in! 🥳

Cheers,
Ann :)

**Pull request merged**
