### PR TITLE
Added Emiline Brown's Advice

### PR DESCRIPTION
**Pull request by emiline-b**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @emiline-b,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @emiline-b,

I noticed that you added a commit and pushed your code. It looks like you changed the link in the index.html file from:
 `<a href ="advice/emiline-brown-advice.html">Emiline Brown's Advice</a><br>`
to:
`<a href ="advice/emiline-b-advice.html">Emiline Brown's Advice</a><br>`

The next step would be to add the emiline-b-advice.html file to the advice folder. Once you have you're ready to add and commit the change. Once you push your code to GitHub, your pull request will be updated. 👍 

Let us know if you have any questions!

xoxo,
Lisa

**Comment by emiline-b** [comment]
﻿Hi Lisa,

I tried again and I’m not sure if that worked! Can you check and if not I think I’m missing something and might just start over on the forking process?!
Also, if I wanted to make changes to my CSS without messing with the main.css, would I just make a copy of it and rename or start a new one?!
Thanks for all your help!

Emiline

Sent from my iPhone

On Nov 29, 2022, at 9:07 PM, Lisa Savoie ***@***.***> wrote:

﻿

Hi @emiline-b<https://github.com/emiline-b>,

I noticed that you added a commit and pushed your code. It looks like you changed the link in the index.html file from:
<a href ="advice/emiline-brown-advice.html">Emiline Brown's Advice</a><br>
to:
<a href ="advice/emiline-b-advice.html">Emiline Brown's Advice</a><br>

The next step would be to add the emiline-b-advice.html file to the advice folder. Once you have you're ready to add and commit the change. Once you push your code to GitHub, your pull request will be updated. 👍

Let us know if you have any questions!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @DOdric-B-Sykes!

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

What an excellent way to practice your skills! You're right - you'll create your own css file (something like "emiline-b.css" and then link to it in the <head> of your HTML. After pushing to GitHub, you can create a new pull request. When you do, can you add a note that you've already had your pull request approved, but you also wanted to add a CSS file? (Just in case I'm not the one to see the PR.)

xoxo,
Lisa

**Pull request merged**
