### PR TITLE
Added Aeneas Hemphill advice

### PR DESCRIPTION
**Pull request by saagszn**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @saagszn !

This is great! The only thing we need is to move your `aeneas-hemphill-advice.html` file inside the advice directory. Right now it is in the root of the folder.

Once you move that file, add your changes with `git add -A` - commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by saagszn** [comment]
Thank you @redrambles! Making the change now

**Comment by redrambles** [comment]
Hey @saagszn ! Just want to say that I have read your comment but there still aren't any changes on our end. Do you still need to push up your advice branch?

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by saagszn** [comment]
Oh! That's weird. I must not have pushed it properly. I'll look into that
today, thank you for following up!

*Aeneas Sagar Hemphill*
*Writer & Performer*
(703) 717-2832 : Call/Text
***@***.***
www.aeneas-hemphill.com

**Comment by saagszn** [comment]
I'm having trouble. I've done the commit (it shows up in git log) but it's
not reflected on the github repo...

*Aeneas Sagar Hemphill*
*Writer & Performer*
(703) 717-2832 : Call/Text
***@***.***
www.aeneas-hemphill.com

**Comment by acodeinprogress** [comment]
Hi @saagszn,

Was your push to GitHub successful? Can you send us a screenshot of your push command and the result?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @saagszn,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
