### PR TITLE
replaced skillcrush name with tatiana name

### PR DESCRIPTION
**Pull request by tatianabrouillard**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @tatianabrouillard,

This is an excellent start! Just a couple of small changes to make before we can merge in your code.

- We would like your advice file to be in the advice folder. 
- Then add a link to your advice file to the index.html file.

Once you've made those changes, add them with a slightly different git command (`git add -A`), commit, then push your code to GitHub. Your changes will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by tatianabrouillard** [comment]
Good night, Lisa !

Thank you for the guidance 🌷 submitted the changes , completely missed the
line of instruction in the lesson 😂, sorry about that ..
was trying to create a new pull request but git doesn't let me . I have
updated the link to the repo on the skillcrush site.
Let me know your thoughts .
Good night !

Tatiana the Skillcrusher 🤗

**Comment by twosavoie** [comment]
Hi @tatianabrouillard,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Comment by tatianabrouillard** [comment]
Hooray!!! Thank you , Lisa, you made my night 🌟Sent from my iPhoneOn 10 Sep 2023, at 22:20, Lisa Savoie ***@***.***> wrote:﻿
Hi @tatianabrouillard,
Great job! Your code is all merged in.
Best,
Lisa

**Pull request merged**
