### PR TITLE
Added Elizabeth R's advice and updated index

### PR DESCRIPTION
**Pull request by er1927**
Can I add my advice? Thank you!

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @er1927,

Looks great! I only have 1 tiny request for you.

We would like for your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by er1927** [comment]
Hi, Lisa!
I'm a bit lost.
I tried looking for my file in skillcrush/git-practice to see where it currently is, but didn't find it. My train of thought is I need to know where it is to access it through Git Bash and then move it, am I correct?

**Comment by redrambles** [comment]
Hey @er1927 !

[Here is a quick screencast](https://www.loom.com/share/48905ccdb1574c30b6b6bc9bc832195c) that I hope will help clarify. Keep us posted!

**Comment by er1927** [comment]
Hi, Ann! Thank you for that screencast, it really was very helpful. I somehow managed to fail, though, impressive in and of itself, you ask me.
I moved the file to Advice. On Git Bash I accessed it, ran `git add -A`, then `git commit -m "Moved file etc."`, then `git push origin main`. 
Now I'm thinking that last command might not have been right, it is the command to update the entire repo, correct? 
Attaching screenshot of *everything*. Thanks again!

**Pull request merged**
