### PR TITLE
Completed HTML and CSS Advice Page

### PR DESCRIPTION
**Pull request by KatherineMarlo**
:)

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @KatherineMarlo !

This is a great start! There are just a few things we need to change before we can merge this in.

1) You have two advice files - one in the advice directory (which is where we want it!) and another in the root of the project folder `Katherine-creech-advice.html`, which we don't want. Please remove the `Katherine-creech-advice.html` that is in the root of the project folder.

2) We are missing a link to your advice page from the main index.html file. Please add it in, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

3) Unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :) Please remove the 'img' directory, make any changes you need to to your advice file as a result (like linking to a hosted image online instead, for example).

Once you have addressed these points, it will be time to add your changes with `git add -A`, commit as per usual, and push up your `advice` branch once more, which should automatically update this pull request.

Then we should be all set to merge this in!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by KatherineMarlo** [comment]
Ok, great! How do I find the file in the root of the project folder?

Thank you!!

**Comment by KatherineMarlo** [comment]
Ok, so I used this command "find . -name "Katherine-creech-advice.html" to find the files and these two results came up:
./advice/Katherine-creech-advice.html
./Katherine-creech-advice.html

so I am deleting the ./Katherine-creech-advice.html now and then pushing the changes through?

**Comment by KatherineMarlo** [comment]
Ok, I believe that I have made all the changes! Do I need to make another pull request?

**Pull request closed without merging**
