### PR TITLE
Added advice for other coders

### PR DESCRIPTION
**Pull request by shecodes777**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @shecodes777!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by shecodes777** [comment]
Hiii Ann, I did add my link to the bottom of the page. You may have been
confused because the of name :)
The link is under the name "Mary's Advice".
It should be at the bottom of the page.
My name is Mary Tadesse but my username is shecodes777.
Let me know if you find it :)

**Comment by shecodes777** [comment]
Update: I see what you mean now. The link was available but it wouldn't
open.
I just fixed it tho 🥰☀️
Let me know if it works for you now!

**Comment by redrambles** [comment]
Hey @shecodes777 !

Ok! So if you  have a look at your changes here: https://github.com/skillcrush/git-practice/pull/1127/files - you'll see that there is just the file you added, and not the change to the index.html file that would include your link. That's because on my end, that link was never pushed up. :) 

Sounds like the link is all set on your end, so there are two possibilities here:

1) If you run `git status` and it shows that you still have your index.html file to add and commit - please do that. Then you'll need to push up with `git push origin advice` in order for us to get that change.

2) If `git status` is clean, then it just means it needs to be pushed up - `git push origin advice`.

Once you've done this, if you revisit the same link I shared with you at the top of this reply (your changes) you'll see two files there - your advice file, and the index.html file that will contain one modification: your link. Then you'll know that we're good to go!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hi @shecodes777,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
