### PR TITLE
Personalized html with name

### PR DESCRIPTION
**Pull request by LuLaura-D**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @LuLaura-D,

This is a great start! Just a couple of changes to make.

First, you'll want to add a link in the index.html file to your advice file. 

Next, we would like for your advice file to be in the advice folder. 

Once you've made those changes, run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by LuLaura-D** [comment]
Thank you for the instructions. I made those changes, I hope it is correct
now.
=) LuLaura Day

**Comment by twosavoie** [comment]
Hi @LuLaura-D,

Unfortunately, we don't see a link in the index.html file to your advice file. Can you check to be sure the change has been made on the advice branch? Then be sure to save your code. In the command line, run **git status** to see if any changes need to be added or committed - if so, go ahead. Then push the advice branch by running **git push origin advice**. The pull request should update automatically.

If you get stuck, let us know! You can email us a screenshot of your command line to questions@skillcrush.com. 👍 

You've got this! 

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @LuLaura-D,

Great job adding your advice file to the advice folder! 

The next step would be to add a link in the index.html file to your advice file in the advice folder. You can add it to the bottom of the other links that you see here: https://github.com/LuLaura-D/git-practice/blob/advice/index.html 

When you do, be sure you're on the advice branch. After making and saving the changes, you can add and commit them and push your advice branch to GitHub. Your pull request will be updated automatically. 

Let us know if you have any questions!

xoxo,
Lisa

**Comment by redrambles** [comment]
Hey @LuLaura-D !

How's it going with this? Do you need a hand? You are nearly done! We just need you to pop a link in the index.html file, pointing to your advice file (if you have a look at the index.html file, you'll see what I mean - each student added their own link to their own advice file, so you can add yours to the bottom of that list) - and then save the file, add and commit and push up your advice branch once more, which will automatically update this pull request. 

Once that's done, we'll be good to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by LuLaura-D** [comment]
Thank you, I have switched to the web design course for now. So far with
this course, it is going really well.
Thank you again for checking in.
Warm regards, LuLaura

**Comment by twosavoie** [comment]
Hi @LuLaura-D,

Thanks for getting back to us. I'm going to close this pull request but feel free to revisit it in the future.

Best,
Lisa

**Pull request closed without merging**
