### PR TITLE
Added link to Sophia Kay's advice

### PR DESCRIPTION
**Pull request by sophia-kay**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @sophia-kay !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/sophia-kay-advice.html` file exists as part of this pull request. Perhaps it still needs to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by sophia-kay** [comment]
Hi Ann!

I *think* I've now added + committed the file sophia-kay-advice.html and
pushed the advice branch.

Thanks for your help!

Sophia

**Comment by redrambles** [comment]
Hey @sophia-kay !

Yes! Thanks for making those changes, this is all good. PR accepted! 🎉

Cheers,
Ann :)

**Comment by sophia-kay** [comment]
Awesome, thanks!

**Pull request merged**
