### PR TITLE
Added heather e advice link

### PR DESCRIPTION
**Pull request by heatherguesa**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @heatherguesa,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! When you do, be sure to place it in the advice or css folder and update the link in the index.html file.

Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by heatherguesa** [comment]
Thanks Lisa!

I'm having trouble here:
[image: Screen Shot 2022-06-19 at 4.10.27 PM.png]
When I try to merge, it says it's already up to date.

Here's my commands:
[image: Screen Shot 2022-06-19 at 4.08.03 PM.png]

I'm not sure where I'm going wrong.. I appreciate your help!

**Comment by twosavoie** [comment]
Hi @heatherguesa, 

Unfortunately, I can't see the images you uploaded. Can you send them to questions@skillcrush.com instead? We can go from there. 

xoxo,
Lisa

**Comment by bagewadi-akram** [comment]
What actually this page is

**Comment by redrambles** [comment]
Hey @heatherguesa,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
