### PR TITLE
LH Advice Request

### PR DESCRIPTION
**Pull request by luanhuynh009**
Practice for git.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @luanhuynh009 !

This is great ! We just need you to make a tiny change so that we can merge this in. Right now, your advice file is called `Luan-H-advice.html` and it is in the root of the project folder.

The link that you added to the index.html file is pointing to the file as `luan-h-advice.html` (all lower case) - and inside the advice directory `advice/luan-h-advice.html` - which is where it should be. 

So!

1) Please rename your file to `luan-h-advice.html`
2) Please move it inside the advice directory.

Once this is done, add your changes with `git add -A`, commit as per usual and then push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by luanhuynh009** [comment]
Thank you for the response Ann, all the changes have been made. 

Best,
Luan :)

**Comment by acodeinprogress** [comment]
Hi @luanhuynh009,

Thanks for making that update!

It looks like you have two advice files now - one in the advice folder and one in the root folder of this project. You'll need to delete the extra file in the root folder of the project. Once you do that, you can go through the steps of running `git add -A`, then committing and pushing. :D 

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @luanhuynh009 !

Thanks for making that change, your code is merged in! ⭐

**Pull request merged**
