### PR TITLE
Added my advice to git-practice

### PR DESCRIPTION
**Pull request by 1819367**
Please let me know how I did.  When I got to step 17 of "Finishing the Forking Workflow", I thought I might need to start again.  I looked at my forked copy of the git-practice repo on Github and found what I was looking for to create a pull request.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @1819367!

This is good! There are only a few things that we need you to change in order to merge this in:

1) Can you move the meta tag for the utf-8 charset back to where it was originally in the main idnex.html file - i.e. - right under the opening `head` tag? 

CleanShot 2023-08-24 at 14 02 35

2) The double quotes around your link in the main index.html file are curly quotes instead of straight quotes. I know - such a little thing, but the browser interprets these differently and without straight quotes, your link wont' work:

CleanShot 2023-08-24 at 14 02 50

You can copy the quotes around the link of the student above you and just replace your curly quotes with that, and you'll be all set.

3) Please add a `<br>` tag after your link (now with shiny new straight quotes) so that the next student link will sit on its own line. 

Once these three small changes are taken care of, we'll be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by 1819367** [comment]
Hello;thank you for the feedback.Do I make the updates on my pc and then send it back to github for review?  please lmk if I'm understanding the process.  Thank you.
Elizabeth
    On Thursday, August 24, 2023 at 11:06:04 AM PDT, Ann Cascarano ***@***.***> wrote:  
 
 


Hey @1819367!

This is good! There are only a few things that we need you to change in order to merge this in:
   
   - Can you move the meta tag for the utf-8 charset back to where it was originally in the main idnex.html file - i.e. - right under the opening head tag?


   
   - The double quotes around your link in the main index.html file are curly quotes instead of straight quotes. I know - such a little thing, but the browser interprets these differently and without straight quotes, your link wont' work:



You can copy the quotes around the link of the student above you and just replace your curly quotes with that, and you'll be all set.
   
   - Please add a <br> tag after your link (now with shiny new straight quotes) so that the next student link will sit on its own line.

Once these three small changes are taken care of, we'll be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by 1819367** [comment]
I made the changes that you identified and made a few mistakes along the way.  I think I figured it out.  Let me know.  Thank you for your help.

**Comment by 1819367** [comment]
Oops.  I stand corrected.  I just noticed that I did not correct the footer.  I am going to do that now and resubmit.

**Comment by 1819367** [comment]
Hello, I made the corrections to my footer. I look forward to your feedback.  Ty.

**Comment by redrambles** [comment]
Hey @1819367,

Thanks for making those changes, your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
