### PR TITLE
Added elan austin to advice page

### PR DESCRIPTION
**Pull request by ekara83**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @ekara83,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by ekara83** [comment]
thanks! I have done that!

**Comment by redrambles** [comment]
Hey @ekara83 !

We didn't get the commit over here, so I'm thinking that possibly you pushed up the main branch instead of the advice branch, which is the branch this PR is based on. Want to give it another shot with `git push origin advice`?

We'll go from there!

Cheers,
Ann :)

**Comment by ekara83** [comment]
HI Ann,

I tried it again and it says everything is up to date.

Thanks.

Elan

**Comment by redrambles** [comment]
Hey @ekara83 !

Ok - so we've got a little more digging to do. Can you email us at 'questions@skillcrush.com' so that we can share screenshots and such more easily? Then we can circle back here. :)

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey Hey! 

How's it going with this? Did you have a chance to send in an email so that we can move forward? We're happy to help!

Cheers,
Ann :)

**Comment by ekara83** [comment]
Hi Ann! 

Thanks for emailing I just sent an email. :)

**Comment by redrambles** [comment]
Hey @ekara83 !

Thanks for making that change - your code is merged in!!! 🎉

Cheers,
Ann :)

**Pull request merged**
