### PR TITLE
Camille J's Advice

### PR DESCRIPTION
**Pull request by lafrenchcoder**
My top three pieces of advice for people learning to code.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @lafrenchcoder !

Ok! So we have a few extra files here that we don't need - but other than that, this is great! You have two html files and two css files - one with 'camille-j...' and the other with 'camille-b...' - [see here](https://github.com/skillcrush/git-practice/pull/206/files).

Since in the index.html you are linking to `advice/camille-b-advice.html` -let's keep the 'b' set of files, and delete the 'j' set. 

Once you have removed `css/camille-j.css` and `advice/camille-j-advice.html`, please add your changes with `git add -A`, then commit as per usual and push up your main branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by lafrenchcoder** [comment]
Hi Ann! 

I think I fixed the error. Please let me know if I didn't do it correctly.

**Comment by redrambles** [comment]
Hey @lafrenchcoder !

Ok so now we have a `css/camille-b.css` file, but no advice file! Haha. Oh no!! :) Can you drop that advice file back in? And also if you use the 'b' version of the advice file, you'll need to update the link in the index.html file, that still references the 'j' version.

Once you've done this, add, commit and push up your branch again, and we should be good to go! 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by lafrenchcoder** [comment]
Hello! 

I made the changes but now it seems that I cannot make a new pull request? 

Thank you, 
Camille

**Comment by redrambles** [comment]
Hey @lafrenchcoder !

This is great, thanks for making those changes, your code is merged in! And there was no need to create a new pull request, we were working with the same one. Because this pull request was open and tied to your 'main' branch, whenever you made any changes to your main branch and then pushed them up, this pull request was automatically updated. Now that it has been merged, the pull request is closed.

Keep up the great work and happy coding!

Cheers,
Ann :)

**Pull request merged**
