### PR TITLE
Added advice for Sarah Steele

### PR DESCRIPTION
**Pull request by sarahscottsteele**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @sarahscottsteele,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @sarahscottsteele,

Just checking to see if you have any questions. Let us know if there's anything we can help with. 👍 

Best,
Lisa

**Comment by sarahscottsteele** [comment]
I will give that a try and make sure they were added correctly!

Sarah Steele

**Comment by twosavoie** [comment]
Hey @sarahscottsteele,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
