### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by vonschell**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @vonschell!

You have a great start here! We talked about this PR in an email. Once you've saved your code and added and committed the changes, go ahead and push the **advice** branch to GitHub. Your pull request will update automatically. 👍 

Let us know if you have any questions!

Best,
Lisa

**Comment by vonschell** [comment]
Good day Lisa!

Yes everything has been sorted thank you so much.

Kind regards
Vonschell

**Comment by twosavoie** [comment]
Hi @vonschell!

That's great! Once you've added and committed the changes you've made, push the **advice** branch to GiHub and this pull request will update automatically. 

Happy coding!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @vonschell,

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @vonschell,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Comment by vonschell** [comment]
Hi Lisa, omg I completely forgot about it! I will sort it out soon. Thank
you!

**Pull request closed without merging**
