### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by jolennd**
Please review and add my changes.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @jolennd,

Great job adding your advice to the advice folder. Just a couple of changes to make! 

In the index.html file, the formatting has changed just a bit. Two spaces have been added to the front of each line. Also, it looks like a .vscode json file has been added. If you could change back the formatting and delete the json file, this should be ready to merge. 

Once you fix that up, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by jolennd** [comment]
Hi Lisa,

Thanks so much for your feedback. I was able to remove the .gitignore and .vscode files from my repo. 
I also tried reformatting the file although I am not certain about the original format. If my index.html file is still incorrect, should I do a hard reset to ensure the formatting is correct?

I used the following commands to add my index.html file to my advice branch.
If this is incorrect, please advice. 
##################################
# Add and commit your changes
git add -A
git commit -m "Fix index formatting" 

# Push topic branch to your remote repo
git push origin advice

# See which repos you’re connected to
git remote -v

# View local and remote branches
git branch -a

# Move to your main branch
git checkout main 

# Merge upstream remote branch with your local main branch
git merge upstream/main

# Move to your remote topic branch 
git checkout advice

# Sync your topic branch with the updated main branch
git merge main

# Push changes to the repo
git push origin advice
##################################
Can you also explain the difference between the following:
git pull origin main
git fetch origin main
git merge origin/main


Thanks in advance for your feedback.
Best,
Jolenn

**Comment by twosavoie** [comment]
Hi @jolennd,

You can view the difference in formatting by going to the your History and viewing the index.html file here: https://github.com/jolennd/git-practice/commit/2b90ad29b9dc26ab225b4dc7d3e1ce4360cb3fa6 The version you want to restore to is the Skillcrush original in red. 

Once you've returned the formatting, you'll want to make sure your link to your advice page is still in the index.html file.

I'm sorry, I mistakenly asked you to delete the .gitignore file (I meant to ask you to remove the lines about the .vscode file). If you could add it back and delete the DS_Store file that would be great. 

Once you add the file back, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by redrambles** [comment]
Hey @jolennd !

Ok! I can see there's been a lot of activity on this PR and though we're close, we aren't quite where we want to be. No worries! Let's take a different approach here so that we can get your PR approved. :) 

Here's what I suggest:

1) Make sure that you are on your advice branch. 

2) Take your `sox.html` advice file and place it on the Desktop temporarily. We are going to run a hard reset that will bring your branch in sync with the most recent version of the remote repository - but that will also blow away your advice file in the process, so let's make sure to tuck it away someplace safe first.

3) Once you have moved your file on the Desktop, let's first fetch from the upstream repo:
`git fetch upstream`

4) Now that your local repo has a reference to the most recent commit on the upstream repo, let's hard reset your branch to that same point in the project history:

`git reset --hard upstream/main`

5) Now your local advice branch will be a copy of the main branch on the upstream repo. Excellent. 

6) Pop your `sox.html` file that is chilling on your Desktop back into the /advice directory of your project. Run `git status` - you should notice that Git has picked up on the change and lists the file as untracked. 

7) Open up the main `index.html` file and add a link to your `adivce/sox.html` file somewhere in that long list of links.

8) Run `git status` again -you should see two files listed - your `advice/sox.html` file and the `index.html` file. Add both with `git add -A`, commit `git commit -m "Your message here"` and push up your advice branch with a **force push**:
`git push -f origin advice`

The force push is necessary here because we changed the history of your advice branch when we ran the reset. To clarify, this is a viable approach only because you are working alone on this branch, and so changing history won't affect any other developers. You would not want to use this approach if you were working with other developers on the same branch.

That should get us to where we want to be. Keep us posted!!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hey @jolennd,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Comment by jolennd** [comment]
awesome, thanks Lisa.

**Pull request merged**
