### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by iamtenille314**

### CODE REVIEW

**Comment by iamtenille314** [comment]
Added Tenile advice page and link to index #1

**Comment by redrambles** [comment]
Hey there @iamtenille314 !

This is great!! The only little thing we need to change is to wrap the `href` attribute value in straight quotes `"` instead of curly quotes `“`.  These are tricky things to spot but you learn to see them quickly over time - as curly quotes tend to break links (and a lot of other programming things). 

Once you have made that change, save your file, add and commit and then push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code! Let us know if you have any qs!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @iamtenille314 !

Ok! Are you on your `advice` branch? I'm seeing the file right here as part of your change set:

CleanShot 2023-04-12 at 09 23 42

It's really just the quotes in the index.html file that need updating, and then we're good to go.

CleanShot 2023-04-12 at 09 24 50

Let me know if this isn't clear or you have more qs!! :)

Cheers,
Ann

**Comment by iamtenille314** [comment]
This has been updated. Thank you for being patient and walking me through it. I was in the wrong part.

**Pull request merged**
