### PR TITLE
added my link to advice page

### PR DESCRIPTION
**Pull request by CodingMonsterMommy**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @CodingMonsterMommy,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @CodingMonsterMommy,

Unfortunately, I don't see your new advice file in the advice folder. Can you check to be sure you're on the advice branch and that the file is there? If it is, in the command line, run **git add -A** (the capital A is important), then commit as you normally would. Once you push to GitHub, your pull request will be updated.

I hope this helps! Hang in there - Git definitely takes a bit of time to get used to. You've got this!!!

Best,
Lisa

**Comment by CodingMonsterMommy** [comment]
Hi Lisa,

Is the crystal-riddle-advice.html what I have to commit and push? I wasnt sure if it was that one or the index. Yes it definitely does haha. I wanted to give up but I'm no quitter, I'll figure this out one way or another.

Thank you so much for helping me!!

**Comment by twosavoie** [comment]
Hi @CodingMonsterMommy,

That's great to hear! That kind of perseverance will serve you well as a developer!

You're right - we're looking for the crystal-riddle-advice.html  file which should be in the advice folder (on the advice branch.) When you're on the advice branch, do you see your html file in the advice folder? If so, be sure to add and commit the change as mentioned above (be sure to use **git add -A** to add to staging.) Then pushing your code to GitHub should update this pull request. 

Let us know if you need any help with this!

Best,
Lisa

**Comment by CodingMonsterMommy** [comment]
Happy Thursday!

I have definitely learned in this process that you cannot just rush through anything and if need be, redo steps, and eventually you'll get it. I still love everything about becoming a developer, it's fun and challenging. 

Ok, I think I got it for sure this time. I'm hoping the third time is a charm haha.

Have a great day!!

Crystal

**Comment by Deel-Khan** [comment]
Same here, I'm just trying to connect the dots here as well. lol

**Comment by CodingMonsterMommy** [comment]
@Deel-Khan, At least I know I'm not the only one haha. Sometimes connecting those dots feels like geometry lol but when you finally get it, it is the best feeling ever!!

**Comment by twosavoie** [comment]
Hi @CodingMonsterMommy,

Well done adding your advice file! The next step would be to move the advice file into the advice folder so that it joins the all of the other student's advice files (it will have friends! 🙂)

If you have any questions, let us know!

Best,
Lisa

**Comment by CodingMonsterMommy** [comment]
Hello Lisa,

Would this be when I merge to the main? Do I have to do another pull request? Sorry, still trying to get it right lol.

Thank you so much for all the help!
Crystal

**Comment by redrambles** [comment]
Hello there @CodingMonsterMommy - hope you don't mind if I jump in!

So all that needs to happen now is that you move your advice file into the advice directory, like this:

CleanShot 2023-06-01 at 16 30 35

Once that is done, if you run `git status`, you'll see that Git has picked up on that change. Then you'll want to add the changes (you can use `git add -A`), commit them as per usual and finally push up your `advice` branch once more, which will automatically update this pull request. No need to create another one!

That should do it. Keep us posted!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hey @CodingMonsterMommy,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Pull request closed without merging**
