### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by cailynb**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @cailynb,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Also, "Skillcrush" has been removed from the h1 on line 14. Once you do those two things, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by cailynb** [comment]
I think I fixed it? I hope lol, let me know. Although, I read on the instructions that editing the css was more an option and not a requirement, is this no longer the case?

Thank you,
Cailyn

**Comment by redrambles** [comment]
Hey @cailynb !

You are correct - the CSS is optional, so no worries there! 

Ok! So let's have a look at what we need to wrap this up.

First - make sure that you are in your `advice` branch (`git checkout advice`). 

If you [look here](https://github.com/skillcrush/git-practice/pull/699/files) at your changes, you can see that you added a link to your advice file in the main index.html file, but in so doing removed another student's link (highlighted in pinkish-red, on the left-hand side). Oops! No problem, you can copy the student link from the change set, add it back into your local index.html file, and then save those changes.

You'll also want to ensure that you have added your 'cailyn-buck-advice.html' file to the advice directory and that it is saved.

Once you have made those changes, if you run `git status`, you should see both files (your advice file and the main index.html file) listed in the Terminal. You'll then want to add them both `git add -A`, commit as per usual `git commit -m "Your message here"` and then push up your advice branch once more `git push origin advice`.

Then we should have everything we need on our end and will be able to merge in your code. 🎉

Let us know if you have any questions!

**Comment by cailynb** [comment]
Terminal was saying that it failed to push some refs to my git-practice repo but everything is saved and there's nothing to commit in the advice branch... So let me know if it worked or not. I don't think so but hopefully

**Comment by redrambles** [comment]
Hey @cailynb !

You're correct, we don't see anything here. If you run `git status` while in your advice branch, you don't see anything to commit, correct? Do you remember creating your advice file (`cailyn-buck-advice.html`)?

If you like, you can reach out at questions@skillcrush.com where it is easier to share screenshots and such, or we can keep conversing here. :) We'll work through it together!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @cailynb !

How is it going with this? Did you have a chance to email in so that we can make progress? We're happy to help!

Cheers,
Ann :)

**Comment by cailynb** [comment]
Sorry work got kind of hectic. I'm going to send an email now. Hopefully we can figure out what I'm doing wrong so I can continue the lessons 😭

**Comment by cailynb** [comment]
The GitHub website lets me resolve conflicts on there supposedly, but I'm not sure if that reflects on everyone else's end or if that is even the issue as I have resolved the conflict through terminal as well and still run into the same weird issue. So I just sent the email. Looking forward to a response! I'll be patiently waiting. ☺️

**Comment by cailynb** [comment]
Okay I believe I've finally done it! Let me know~

**Comment by twosavoie** [comment]
Hey @cailynb,

Awesome!!! You did a great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
