### PR TITLE
Add torres-ml advice page and its style sheet

### PR DESCRIPTION
**Pull request by torres-ml**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @torres-ml,

Awesome start! Well done!

There are some conflict markers in the index.html file. And there may be some duplication of the code. Instead of searching through all of the lines to see if there are you can:

- Checkout the original index.html file from the upstream repo: `git checkout upstream/main index.html`
- Open up the index.html file in your text editor and add your link to your advice file

Now go ahead and add `git add -A`, commit `git commit -m "Your message here"` and push up your advice branch once more by running `git push origin advice`.

This will automatically update your pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by torres-ml** [comment]
| 
| 
|  |

 |
| 
|  Hi Lisa, Updated my pull request. Do I need to update my local repo or does it automatically happen when the pull request is updated?Thanks
  Via  
  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Wednesday, September 6, 2023 at 09:11:40 PM EDT, Lisa Savoie ***@***.***> wrote:  
 
 


Hi @torres-ml,

Awesome start! Well done!

There are some conflict markers in the index.html file. And there may be some duplication of the code. Instead of searching through all of the lines to see if there are you can:
   
   - Checkout the original index.html file from the upstream repo: git checkout upstream/main index.html
   - Open up the index.html file in your text editor and add your link to your advice file

Now go ahead and add git add -A, commit git commit -m "Your message here" and push up your advice branch once more by running git push origin advice.

This will automatically update your pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by redrambles** [comment]
Hey @torres-ml !

Once you make your changes locally - and that you have added and committed them - all you need to do is push up your `advice` branch - which is what this pull request is connected to - and your pull request will be automatically updated. :)

Cheers,
Ann :)

**Comment by torres-ml** [comment]
| 
| 
|  |

 |
| 
|  That's what I thought, thanks.
  |

 |
| 
|  |

 |

 |
| 
|  | Yahoo Mail Stationery |

 |

    On Friday, September 8, 2023 at 11:04:13 AM EDT, Ann Cascarano ***@***.***> wrote:  
 
 


Hey @torres-ml !

Once you make your changes locally - and that you have added and committed them - all you need to do is push up your advice branch - which is what this pull request is connected to - and your pull request will be automatically updated. :)

Cheers,
Ann :)

**Comment by torres-ml** [comment]
Is it OK now?

**Comment by redrambles** [comment]
Hey @torres-ml !

We are still seeing conflict markers and such in the index.html file. Here is what I suggest.

1) Make sure you are still in your `advice` branch
2) Fetch from upstream `git fetch upstream`
2) Copy the link to your advice page that you added to the `index.html` file - just so you can easily pop it back in in a moment
3) Run `git checkout upstream/main index.html` - this will overwrite your version of the `index.html` file with the version from the upstream repo, which doesn't have any conflict markers
4) Open up the index.html file in VSCode and paste in your copied link somewhere in the list of links, save the file
5) Add your changes with `git add -A` - commit `git commit -m 'Your message here'` and push up your advice branch once more `git push origin advice`

This will automatically update this pull request, and we should now have a beautiful, clean, up to date index.html file here in your pull request, that also contains the link to your advice file, in addition to your advice file and advice css that we already have. We should then be good to go!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @torres-ml !

We're good to go!! 🎉 Your code is merged in.

Cheers,
Ann :)

**Pull request merged**
