### PR TITLE
Emma Dash's advice for newbies

### PR DESCRIPTION
**Pull request by Emma-Dash**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Emma-Dash,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by Emma-Dash** [comment]
Hi Lisa,

Thanks for your feedback!

I think I had already added the link in the index.html file: I had added a line of code beginning with “a href”:

<a href="advice/emma-dash-advice.html">Emma D's Advice</a>

Is that what you are referring to?
I added it when I noticed that “Emma D’s advice” wasn’t linking to anything.

Thanks again!

Camila 
@Emma-Dash

**Comment by redrambles** [comment]
Hello @Emma-Dash ! 

Yes that is exactly what we are referring to! 🎉 However - if you have a look at the changeset that is attached to your pull request over here: https://github.com/skillcrush/git-practice/pull/825/files - you'll see that the only file we have on our end is your advice file. 

This would lead me to conclude that the link that you see on your end either hasn't been added and committed (and then pushed up) - OR - it was added and committed, but not pushed up yet. 

If you run `git status` - you will see whether the index.html file (where your link exists) is in a modified state, and still need to be added and committed. Then you can do this, and push up. If you don't see your index.html file listed as a result of running `git status` - then let's try pushing up (it could be that this commit is still waiting to join it's friends in the pull request :)) - `git push origin advice`

Keep us posted on your progress and let us know if you have questions!

Cheers,
Ann :)

**Comment by Emma-Dash** [comment]
Hi Ann!

Thanks so much for your feedback. 

I went back to see what the issue was on my end, and like you said, the index.html file had not been added, committed and pushed up (oops!). 
Could you let me know if I did this correctly? 

Thanks again :-)

Camila 
@Emma-Dash

**Comment by twosavoie** [comment]
Hey @Emma-Dash,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
