### PR TITLE
Added Shayla P's advice

### PR DESCRIPTION
**Pull request by shaylapierrard**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @shaylapierrard,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by shaylapierrard** [comment]
Hello, 
I have committed these, but I can not figure out how to push them here. When I do the git push it's saying everything is up to date. I don't understand it enough to know what I'm missing, if you could please let me know.

Thank you

**Comment by twosavoie** [comment]
Hi @shaylapierrard,

Let's take a look at your command line. Can you try running a slightly different command, **git add -A** (the capital A is important.) And then commit and push your code. Can you also run **git status**? Then send us a screenshot to questions@skillcrush.com. We'll be able to go from there.

Best,
Lisa

**Comment by redrambles** [comment]
Hey @shaylapierrard ,

Well done! Your code is all merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
