### PR TITLE
Added warren whitehurst advice html css

### PR DESCRIPTION
**Pull request by Whitehurst87**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @Whitehurst87,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by Whitehurst87** [comment]
Hey there, I’m glad most of it looks great. I had a question on  the correct placement of the link. Does the link go into my index file or to another student’s? I was confused by the quote. “Add a link to your advice html below the other students’ link.”  Thank you for your feedback, I appreciate you taking the time to help. Sent from Mail for Windows From: Lisa SavoieSent: Saturday, February 12, 2022 3:20 PMTo: skillcrush/git-practiceCc: Warren Whitehurst; MentionSubject: Re: [skillcrush/git-practice] Added warren whitehurst advice html css (PR #502) Hey @Whitehurst87,Great job adding your advice file to the advice folder!The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.Let us know if you need any help! You've got this!xoxo,Lisa—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by twosavoie** [comment]
Hi @Whitehurst87,

You'll add the link in the index.html file. You can follow the same format as the other student's links. I hope that helps!

Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hey @Whitehurst87,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
