### PR TITLE
Added amara advice

### PR DESCRIPTION
**Pull request by amara411**
Hello! This is my first pull request.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @amara411,

This is a great start! I noticed you didn't add an advice page to the advice folder (or any css.) If you could, that would be great! Once you do, you can add, commit, and push your code to GitHub. It will join your pull request here.

Let us know if you need any help!

Best,
Lisa

**Comment by amara411** [comment]
Hello @twosavoie,

I was able to add an advice page and css. Please search "amara-bay" and the html page and css should pop up. Please let me know if you see it!

Best,

Amara

**Comment by twosavoie** [comment]
Hi @amara411,

Thanks for reaching out! Unfortunately, it doesn't look like your changes have been pushed to your GitHub repo's advice branch. Can you check the command line to be sure your code was added, committed, and pushed? 

If you're unsure, we would be happy to take a look! Can you run `git status` and `git log --oneline` (there are two dashes before **oneline**) and send a screenshot of the result along with the commands you ran to add, commit, and push to GitHub? Send it to us at questions@skillcrush.com (You aren't able to upload a screenshot in response to this message.)

We'll be able to go from there!

Best,
Lisa

**Comment by amara411** [comment]
Hi @twosavoie,

I must have made a mistake earlier on that I can't find because I keep getting error messages on my command line. I'll just start over and submit another pull request. Thank you. 

Best,

Amara

**Pull request closed without merging**
