### PR TITLE
Added my advice

### PR DESCRIPTION
**Pull request by caseyhur**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @caseyhur !

This is great!! The only thing we need before we can merge this in, is for you to move your advice file `casey-hurlburt-advice.html` into the `advice` folder - right now it's in the root of the project directory.

Once you move that file, add the change with `git add -A`, commit as per usual and then push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by caseyhur** [comment]
Hi Ann,

Thanks so much for the feedback! I actually did realize that my file wasn't in the advice folder, but I must've forgotten to update it once I moved it. I followed your instructions so I hope it's showing in the right folder now in the pull request. Let me know if I still got it wrong!

-Casey

**Comment by redrambles** [comment]
Hey @caseyhur !

Ok! Hmm - I don't have a new commit on my end, with the change that would include the move of the file to the correct folder. Do you remember running `git push origin advice` ? If so - have a look at `git status` - is there anything that still needs to be added and committed? 

Talk soon!

Cheers,
Ann :)

**Comment by caseyhur** [comment]
Hi Ann,

Thank you so much for sticking with me. I don't know what I was doing yesterday! I did need to do another add and commit. Hopefully it worked now!

Thanks again,
Casey

**Comment by redrambles** [comment]
Hey @caseyhur !

Haha - no worries - we've all been there! Everything looks great now, your code has been merged in! 🎉 

Cheers,
Ann :)

**Pull request merged**
