### PR TITLE
David Nieto Advice

### PR DESCRIPTION
**Pull request by dnietoh**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @dnietoh,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by dnietoh** [comment]
I have what I believe to add, commit, and push: the added link in the index.html file.

thank you

Please provide your feedback

**Comment by redrambles** [comment]
Hello @dnietoh !

Hmm - we still don't have that link in the index.html file on our end. If you look at the change set related to your pull request here: https://github.com/skillcrush/git-practice/pull/734/files - you'll see that your advice file made it across to us, but there is no change to the index.html file.

Let's check a few things. Locally, are you on your advice branch? If not, make sure to move over with `git checkout advice`. Then if you run `git status` - do you see anything there that still needs to be added and committed? 

If nothing turns up from running `git status`, it's possible that you had previously pushed up the main branch rather than the advice branch - so let's try doing that again: `git push origin advice`

Let us know how this goes!

Cheers,
Ann :)

**Comment by twosavoie** [comment]
Hey @dnietoh,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
