### PR TITLE
Added heather's advice

### PR DESCRIPTION
**Pull request by hbrien232**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @hbrien232 !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/heather-brien-advice.html` file exists as part of this pull request. Perhaps it still need to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by hbrien232** [comment]
Thanks for letting me know. I went through the steps in the command line to
add and commit this file. Let me know if there anything else that I need to
do.

-Heather

**Comment by redrambles** [comment]
Hey @hbrien232 !

We are nearly there! I do indeed now have your `heather-brien-advice.html` file - but it is in the root of the project folder rather than inside the `advice` directory, where it belongs. Please move your file over inside the advice folder and then add that change with `git add -A` - then commit as per usual and finally push up your branch once more `git push origin advice`. Then we should be all set.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by hbrien232** [comment]
Ah ok. I went through these steps so it should be in the right place now. 🤞

-Heather

**Comment by redrambles** [comment]
Hey @hbrien232 ,

Thanks for making those changes - your code is merged in! :) 🥳

Cheers,
Ann :)

**Pull request merged**
