### PR TITLE
Added Rhea's advice branch

### PR DESCRIPTION
**Pull request by rlrussell95**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @rlrussell95,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by rlrussell95** [comment]
Hi @twosavoie,

I'm not sure I understand what you mean by adding a link in the index.html file to my advice file. As far as I can tell they are both already linked. Could you elaborate a bit on what it is that I need to complete?

**Comment by twosavoie** [comment]
Hi @rlrussell95,

Happy to help! Currently, we show the rhea-russell-advice.html file in the advice folder - which is perfect! And it has a link to a css file to add your styles. 👍 

The next step would be to add your css file to the css folder. Also, you'll want to add a link to your advice file to the index.html file that's in the root of the project folder. In case you're curious, you can see what was included in your pull request here: https://github.com/skillcrush/git-practice/pull/869/files

If it looks like this is already completed in your local directory, can you check to be sure you're on the **advice** branch and that your code is saved? Then run **git status** to be sure that all changes have been added and committed. 

Once those changes have been made, you can add, commit, and push and your changes will join your pull request here.

If you're unsure, feel free to send us a screenshot of your command line to questions@skillcrush.com. You can also send us a zip file of your code. And let us know if you need any help!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @rlrussell95,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
