### PR TITLE
Added Colleen Tully advice

### PR DESCRIPTION
**Pull request by cetully12**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @cetully12,

Great job adding your advice file to the advice folder!

The next step would be to add a link in the index.html file to your advice file. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let us know if you need any help! You've got this!

xoxo,
Lisa

**Comment by cetully12** [comment]
Hi Lisa,

Thanks for the encouragement! I might need a bit of direction on this one.
There were times when I used GitHub and didn't know if I used it correctly
🥴

**Comment by twosavoie** [comment]
Hi @cetully12,

Happy to help! The next step would be to add a link to your advice file, advice/colleen-tully-advice.html, to the index.html file in the root of your project folder (while on the advice branch.) You can follow the example of the other links in the file.👍 

I hope that helps! If you have any questions, let us know!

xoxo,
Lisa

**Comment by cetully12** [comment]
Hi Lisa,

I think I added a link to my advice file and merged everything accordingly
😅 I'm always a bit nervous I messed something up when merging so hopefully
that wasn't the case.

Also, do I need to do anything more with my pull request? Or does it
automatically update when I commit changes? Thanks!

**Comment by twosavoie** [comment]
Hey @cetully12,

Great job! When you pushed your updated code, the pull request was updated. And now your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
