### PR TITLE
Add advice page from Jeanette

### PR DESCRIPTION
**Pull request by jeanette-f**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jeanette-f,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by jeanette-f** [comment]
Maybe you can help me figure out where I missed a step, because I'm looking at my project file and the index.html file that was already saved in there had my link to the advice page in it, but the index.html file that is listed in this upload doesn't have my link in it. Whereas, my advice.html page which I saved in my project folder 15min after I saved my index.html files, looks exactly the same in my project folder as it does in my upload. 
There weren't any changes to the source code when I performed the merge of the upstream and main branches (I don't know if that's relevant). Is there anything that normally causes this issue, or did I run into a glitch?

**Comment by redrambles** [comment]
Hey @jeanette-f !

Ok! Can you have a look at the result of `git status` ? Is it possible that there is still a change to be added and committed? If so, once you do that and push up your `advice` branch another time, we'll get that change over here - and presuming that the change involves a link in the index.html file, we should be good to go. 

If that isn't the case - can you run `git log -5` (while still on your advice branch) and let us know what you see? We'll go from there!

Cheers,
Ann :)

**Comment by jeanette-f** [comment]
Ok yes, it looks like I just added the single file instead of using the "add -A" command. I had a heck of a time updating my branches with the upstream, since so much activity happened since my first push attempt, but I think I got it to fall in line with the current activity (I hope). I can actually see my index file on the file changes tab in here, so that seems promising. Though it looks like I accidentally added a space on another line I didn't mean to touch, hopefully that's not a problem. Thank you for your help!

**Comment by redrambles** [comment]
Very well done, @jeanette-f !

Your code is all merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
