### PR TITLE
adding ashley hayes advice to remote repo

### PR DESCRIPTION
**Pull request by ashleyvnhayes**
Hello! 

I got confused while trying to complete the forking workflow lessons, and probably messed something up. Please let me know if I need to make any changes!

Thanks,

Ashley

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ashleyvnhayes,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by ashleyvnhayes** [comment]
Thanks for the feedback, Sharon!  I see what happened. I did not merge the edits that I made on the advice branch into the main branch. Hopefully it's fixed now?

Thanks,

Ashley

**Comment by redrambles** [comment]
Hey @ashleyvnhayes !

Thanks for making those changes - this is looking fantastic! The only thing is that we have an additional CSS file in your pull request, called `css/ashleyhayes.css`. You have another one `css/ashley-hayes.css` which you are referencing in your advice HTML file, and which we want to keep - but the second `css/ashleyhayes.css` file we want to remove.

Once you have deleted the `css/ashleyhayes.css` file, you'll need to add that change with `git add -A`. Then you can commit as per usual and push up once more, which will automatically update this pull request. 

Then we should be all set to merge in your code! 🎉

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by ashleyvnhayes** [comment]
Hi Ann!

Good to hear from you. I've managed to keep plugging along since our mentorship session and am excited to be (almost) done with the Git module :) 

I followed your instructions from above, but it looks like I generated a merge conflict in the source HTML file. Would you like me to address the conflict or will you all fix it?

Thanks,

Ashley

**Comment by redrambles** [comment]
Hey @ashleyvnhayes,

We got it! :) Thanks for making that change, your code is merged in! 🎉

Happy coding and keep up the great work!

Cheers,
Ann :)

**Comment by ashleyvnhayes** [comment]
Awesome, thank you!

**Pull request merged**
