### PR TITLE
Added Jamie's advice

### PR DESCRIPTION
**Pull request by jamiehov**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @jamiehov,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by jamiehov** [comment]
Hi Lisa,Shoot, I did add an advice page in my local files but I must not have pushed to GitHub correctly? I’m not sure where I might have gone wrong. Do you have any ideas for troubleshooting?JamieOn Nov 21, 2022, at 12:22 AM, Lisa Savoie ***@***.***> wrote:﻿
Hey @jamiehov,
I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.
Let us know if you need any help!
xoxo,
Lisa

**Comment by jamiehov** [comment]
Thanks! I completed those steps and it looks clean on my command line. Do I
need to create another pull request?

Jamie

**Comment by twosavoie** [comment]
Hi @jamiehov,

Well done adding the advice file! Next, could you move the advice file from the root of your project into the advice folder? If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by jamiehov** [comment]
Great, thanks! Just did that. Did it show up on your end? How can I see it
on github from my end?

Jamie

**Comment by twosavoie** [comment]
Hey @jamiehov,

Great job! This is perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Lisa

**Pull request merged**
