### PR TITLE
Added my advice file and linked it to the index.html file

### PR DESCRIPTION
**Pull request by ela-lisondra**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @ela-lisondra,

This is great! The only thing we need is for you to add a <br> at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add and commit and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by ela-lisondra** [comment]
Thanks Lisa!

I think I maybe missing some info from your note. What should I add at the
end of my link, please? Did you mean <br>?

Ela x

**Comment by redrambles** [comment]
Hello @ela-lisondra !

Yes you're correct!! Looks like the `<br>` bit didn't come through in Lisa's note. Once you add that in and push up, we'll be good to go!

Cheers,
Ann :)

**Comment by ela-lisondra** [comment]
Hi Anne!

It’s done now. Thank you!

Ela x

**Comment by twosavoie** [comment]
Hey @ela-lisondra,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
