### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Aimara-Qvo**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Aimara-Qvo !

Everything is good here except that unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :)

Please remove the 'img' directory and then add that change with `git add -A` - commit as per usual and finally push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Aimara-Qvo** [comment]
Ok, got it. Thanks, Ann. I'm working on it right now.

**Comment by acodeinprogress** [comment]
Hey @Aimara-Qvo,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by Aimara-Qvo** [comment]
Thank you, Sharon! 
xo,
Aimara

**Pull request merged**
