### PR TITLE
Added paragraph and link

### PR DESCRIPTION
**Pull request by mjlemus6045**

### CODE REVIEW

**Comment by mjlemus6045** [comment]
Is the conflict in my advice.html or someone else's? I opened mine in Visual Studio and saw no conflict markers. What is the next step for me?? Do I need to re add and commit and merge, or wait?

**Comment by mjlemus6045** [comment]
What do you mean? Add more commits by pushing to the [advice](https://github.com/mjlemus6045/git-practice/tree/advice) branch on [mjlemus6045/git-practice](https://github.com/mjlemus6045/git-practice).

**Comment by twosavoie** [comment]
Hey @mjlemus6045,

This is great!! The only thing is that you accidentally deleted another student's file from the advice folder called 
<a href="advice/bryson-vindas-advice.html">Bryson Vindas advice</a><br>
and we are going to want that back. (You can see the diff of your pull request [here](https://github.com/skillcrush/git-practice/pull/811/files) if you are curious.)

Once you add the file back, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

**Comment by mjlemus6045** [comment]
twosavoie, How do I go about restoring what I deleted? I don't have those files as far as I know. What were the names of the advice.html's? Where do I find them?

**Comment by mjlemus6045** [comment]
I didn't know what was needed to resolve the conflict. Better directions on GitHub's resolving conflicts might be helpful. Are you talking about the link to the index.html? How do I get it back into the repo? I deleted in the resolve conflict button.                         <a href="advice/bryson-vindas-advice.html">Bryson Vindas advice</a><br> Do I add it into my advice.html and commit, then push and merge?

**Comment by mjlemus6045** [comment]
So how do I do that? I have been running into issues all afternoon to this evening. I keep running into issues with fast forwards, non- fast forwards. With my limited experience, I thought maybe I could include his link in with my advice.html. However, when I tried to add and commit, I got an error for fast-forward. Tried to do a git pull, but did not work. ???? I am lost.

On November 1, 2022, at 7:46 PM, Lisa Savoie ***@***.***> wrote:

Hey @mjlemus6045,

This is great!! The only thing is that you accidentally deleted another student's file from the advice folder called
Bryson Vindas advice

and we are going to want that back. (You can see the diff of your pull request here if you are curious.)

Once you add the file back, please add the change with git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Lisa

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/skillcrush/git-practice/pull/811#issuecomment-1299364467">https://github.com/skillcrush/git-practice/pull/811#issuecomment-1299364467</a>", "url": "<a href="https://github.com/skillcrush/git-practice/pull/811#issuecomment-1299364467">https://github.com/skillcrush/git-practice/pull/811#issuecomment-1299364467</a>", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by redrambles** [comment]
Hey there @mjlemus6045 !

[Here's a link to a quick screencast](https://www.loom.com/share/21ba487f993547968719ab7d37b361e6) where I explain what is left to do here (it's not much!!) - and then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by mjlemus6045** [comment]
Thanks. I work till 3:30 PM. I will get on it then. I may need GitHub for dummies. LOL

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 2, 2022 at 9:33 AM, Ann ***@***.***> wrote:   


Hey there @mjlemus6045 !

Here's a link to a quick screencast where I explain what is left to do here (it's not much!!) - and then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @mjlemus6045 !

Thanks for making that change, your code is merged in!!! 🎉 ✨ 😎

Cheers,
Ann :)

**Comment by mjlemus6045** [comment]
Thanks. I won't forget that lesson.

Sent from Yahoo Mail on Android 
 
  On Thu, Nov 3, 2022 at 9:29 AM, Ann ***@***.***> wrote:   


Hey @mjlemus6045 !

Thanks for making that change, your code is merged in!!! 🎉 ✨ 😎
 
Cheers,
Ann :)

**Pull request merged**
