### PR TITLE
Marisa clayburn's advice edit

### PR DESCRIPTION
**Pull request by Mdclayburn**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Mdclayburn,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

I also see that you are linking to a CSS file that doesn't exist. Want to add that in?

xoxo,
Sharon

**Comment by Mdclayburn** [comment]
Sure thing I will definitely add both of those changes and commit/push them as well. Please let me know if there is still anything I will need to add/change/commit as I'm still getting used to using git/Github.

**Comment by Mdclayburn** [comment]
I'm not sure where I messed up. I must have misunderstood the assignment. I deleted sharon's files because I thought we only needed our index.html/your-name.html/your-name.css files. Please let me know if there is anything I need to fix here. Sorry for the misunderstanding.

**Comment by acodeinprogress** [comment]
Hi @Mdclayburn,

Yes, we would need for you to restore those deleted files and the link that you changed in the index.html file. If you need some help reviewing what was deleted, you can view the [Files Changed](https://github.com/skillcrush/git-practice/pull/2/files) tab near the top of the page.

Once you make those changes, you'll need to run `git add -A`, commit, and push your work. It will join your pull request here and then we can get it merged in!

xoxo,
Sharon

**Comment by Mdclayburn** [comment]
I hope the above change is what was needed. I would like to ask for your patience with me, this is all so new to me. 

If there is anything else I need to fix please let me know. As I see there is a conflict with the index.html file. Do I need to change/push anything to do with the index.html file? 

I look forward to hearing from you

**Comment by acodeinprogress** [comment]
Hey @Mdclayburn,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
