### PR TITLE
Added my advice page link

### PR DESCRIPTION
**Pull request by jerry-weber**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @jerry-weber,

This is great!! We just need a quick change before we can merge this in. Please add a <br> tag right after your link, so that the next person's link will sit on its own line.

That's it!! Once you've made that tiny change, save the file, add it with git add -A or git add index.html, make your commit as per usual and finally push up your advice branch once more, which will automatically update this pull request.

Then we'll be all set to merge in your code! Let us know if you have any questions!

Best,
Lisa

**Comment by jerry-weber** [comment]
Ok I hope I did it right, please let me know if there is anything else I need to do. :)

Thanks!

**Comment by twosavoie** [comment]
Hi @jerry-weber, 

Unfortunately, the change didn't come through. Can you check a few things? 

- When you added the <br> tag, were you on the advice branch? 
- Has your code been saved?
- Run **git status** in the command line. Are there changes to be added (in red) or committed (in green)?

Once all of your code has been saved, added, and committed you can push the advice branch to GitHub and your pull request will be updated.

Let us know if you have any questions! You've got this!

Best,
Lisa

**Comment by jerry-weber** [comment]
Ok so I'm a little confused and not sure I'm doing this right.

I did add the link including the tag and saved the code, this was on the index.html file. Everything went through in terms of saving and then pushing after that on git bash.

I notice my index.html file is not inside the advice folder, it's just inside the git-practice folder. Is this possibly the problem?

**Comment by redrambles** [comment]
Hey @jerry-weber !

Everything looks good now! Looks like sometime between Lisa's reply and mine, the changes you made were pushed up, so I was able to see the result. Your code is merged in!! 🎉

Cheers,
Ann :)

**Pull request merged**
