### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Wily-Kit**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Wily-Kit !

This is a great start! We just need two more things before we can merge this in.

1)  We have a link to your advice page in the main index.html file (yay!) but no such `advice/kit-lappalainen-advice.html` file exists as part of this pull request. Perhaps it still needs to be added and committed? Checking `git status` will help you confirm.

2) There is a conflict marker that still needs to be removed in the index.html file - [see here](https://github.com/skillcrush/git-practice/pull/1070/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R1253).

Once you have added your advice file and made the change in the index.html file, add your changes with `git add -A`, commit as per usual, and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Wily-Kit** [comment]
Hey, Ann!
Okay, I made some adjustments, added and committed my file, corrected the
conflict marker, pushed it back to the repo. I don't know if I did it
correctly, so please let me know if I still have work to do!
Thank you.

**Comment by redrambles** [comment]
Hey @Wily-Kit !

I see the change in the index.html file, thank you!

I don't see your advice file, though. If you run `git status`, do you see it listed? 

Cheers,
Ann :)

**Comment by Wily-Kit** [comment]
Hey Ann!

I ran git status. It just said the branch is clean and there's nothing to
commit.  I tried repeating some of the steps to see if I missed anything,
but it keeps saying everything is committed and pushed. What should I do?

**Comment by twosavoie** [comment]
Hi @Wily-Kit,

It looks like the file added to the advice folder is the index.html file that holds the links to the advice files. You can see what's in the file here: https://github.com/Wily-Kit/git-practice/commit/f24eb0b0f677275fee83cd55702e793640b4bcfd. (You'll need to click on the git diff to see it.)

Instead, we would like the advice.html file you would have downloaded [in this lesson](https://learn.skillcrush.com/module-10/start-the-forking-workflow/) to be added to the advice folder. 

Once you add the file, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions! 

Best,
Lisa

**Comment by Wily-Kit** [comment]
Welp, I tried going back and figuring out what I did wrong. I tried
re-committing things, pushing things, etc. and I'm willing to bet it's
still not working. I'm so lost that the light from lost would take 93
million years to reach me. Some of the instructions are very vague, and I
think that's half of why I trip up. (The other half is my computer not
being able to locate anything thanks to my stupid Google Drive)

Did I change the pull request at ALL?

**Comment by twosavoie** [comment]
Hi @Wily-Kit,

Great job removing the index.html file from the advice folder! 

The next step would be to go back [to this lesson](https://learn.skillcrush.com/module-10/start-the-forking-workflow/) where the advice.html file was downloaded. Start at Step 6 where you checkout the advice branch and continue to downloading the advice file. 

You can drag the downloaded advice.html file into the advice folder within the git-practice directory. You'll change the name of the file to **kit-lappalainen-advice.html** and add your advice to the file. 

Next, add the changes to staging by running **git add -A** and commit the changes by running **git commit -m "Your commit message**. Then push the advice branch to GitHub. 

How does that sound? Hang in there! It can take a bit to get used to Git and GitHub. But you're super close! If you feel stuck, you might try attending a [Live Q&A](https://learn.skillcrush.com/events/) where you can share your screen with an instructor over Zoom. 

If you have any questions, let us know!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Wily-Kit!

Nice work adding your advice file to the advice folder! You're super close to completing this pull request. 🏁 

The next step would be to move the index.html file (the one with every student's link to their own advice file) to the root of the project folder. And then delete the desktop.ini file. 

Once you've moved the file, please add the change with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Keep going - you're almost there!!

Best,
Lisa

**Comment by Wily-Kit** [comment]
Okay, I think I figured out what to do, but then you told me to delete the
desktop version, and when I did that, it deleted the file completely, so I
couldn't git add -A it in the command line. However, I re-downloaded it,
re-cloned it, and suddenly it appeared with all of my previous updates,
so...? I git add -A and committed it. I don't know if any of that worked,
but I'm trying.

**Comment by twosavoie** [comment]
Hi @Wily-Kit,

Sometimes a fresh start can be a great idea! You really are doing great. You're definitely not alone feeling like Git can be confusing. It really takes a bit before it starts clicking. 

I wonder, did you delete both the GitHub repo and the local copy of the project? Or did you clone your current GitHub repo? If you cloned the current GitHub repo (not a newly forked one), you would have the same code you previously pushed to GitHub.

Let us know and we can walk you through the next steps. Hang in there! It can be frustrating but I'm sure you're closer than you think! 

Best,
Lisa

**Comment by Wily-Kit** [comment]
Hello!
I'm not sure if I deleted the GitHub repo, because I've honestly forgotten
which repo we're talking about! (I'm switching back and forth from my two
Git blunders AND my current assignments, so I get confused sometimes) If
it's the git-practice repo, it's still in GitHub. I thought I deleted just
the local Desktop copy, but when I downloaded it again and cloned it, all
of my most recent updates had applied, so I have no idea what happened
there.

So, yes, I'm going to need a step-by-step guide to go forward. Explain it
to me like I'm five, because that's how intellectually mature I'm feeling
right about now!
Thank you!

**Comment by twosavoie** [comment]
Hi @Wily-Kit,

I totally get it! Working with git can be confusing at times. It's worth the effort though and you're doing a fantastic job sticking with it.

To start fresh:

- Delete the remote GitHub repo. On the repo's page go to Settings and scroll to the bottom of the page. (You can't fork a new repo if you already have a forked GitHub repo. So you need to trash it first.)
- Delete the local repository. You can send it to trash

Now you're ready to start fresh. 👍 

- Go to [this lesson](https://learn.skillcrush.com/module-10/start-the-forking-workflow/) where you originally forked the git-practice repo. 
- Work through the lesson steps. Be sure to add the advice file you download to the advice folder. Leave all the other files and folders where they are.

How does that sound? I know it can feel frustrating to start again sometimes. But we've all been there - so you're definitely not alone! 😄 

Let us know if you have any questions!

Best,
Lisa

**Comment by Wily-Kit** [comment]
Hey, Lisa!

PERMISSION DENIED. I deleted the git-practice repo from GitHub and started
over. When I tried to commit my changes, it gave me an access denied
response.
I think I'm getting tripped up by the wording:

- 8. Download the your-name-advice.html
<https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2021/03/your-name-advice.html.zip>
file. Unzip and extract the file. (I did this a while back)
-
- 9. Rename the your-name-advice.html file to replace “your” with your
first name and “name” to your last name or some unique combination. For
example, if your name is Jane Hopper, you’ll rename the file as
jane-hopper-advice.html. (Make sure the name of your file doesn’t match an
existing file in the advice folder) (I have a folder in my File Explorer
called kit-advice.html. Is that it??)
-
- 10. Move your advice HTML file to the advice directory inside the
git-practice directory. (This is the one where I truly get confused. Is the
html file a folder? Like, the folder icon in the File Explorer? What is the
advice directory? How is that different from the git-practice directory? Am
I doing all of this in the File Explorer? This is where the wording super
confuses me, because everything sounds the same and I'm not sure HOW to do
these things and where.)
-
- 11. Open the advice HTML file with your text editor. Replace the three
mentions of “Skillcrush” with your first name. Add your own advice to this
page for future Skillcrushers to see! Save your changes when complete. (Already
did this a while ago)
-
- 12. Preview your advice HTML file in your browser to see what it looks
like. There are minimal styles applied to your page right now, which are
coming from the main.css file in the css folder. Please do not edit this
file. If you would like to change the style of your page, feel free to
create your own CSS file in the css directory! Name your CSS file with your
first name and last name. In the advice HTML page, don’t forget to change
the stylesheet link to the link to your custom style sheet so that your
styles take effect. (Screenshot of this html file in the browser. Did I do
that right?)
-
- 13. Open the index.html file, which is located in the main directory, in
your text editor. (The main directory of what? git-practice? or kit-advice?)

14. Add a link to your advice HTML page below the other students’ links.
For example, Jane Hopper would write: <a
href=”advice/jane-h-advice.html”>Jane H’s Advice</a>. Save the file when
finished.
(Did this, but didn't seem to work, for some reason)

I'm including a screenshot of my File Explorer, because it's confusing. I
have a kit-advice folder, but not a git-practice folder. I can only open
git-practice from the command line by using explorer .
So why is it not showing up in my File Explorer? It just pops up in a
separate window. And why is my kit-advice folder such a mess??  Maybe a
combination of wording tripping me up AND my files somehow being a mess (I
hate Windows 11) is what's causing the problems. I don't know. What do you
think?

Happy Fourth, btw! Lol

**Comment by Wily-Kit** [comment]
P.S. A few extra screenshots. When the lesson keeps talking about html
files, I never know to which one they're referring: This one or this one!

**Pull request closed without merging**
