### PR TITLE
Added Caroline's advice

### PR DESCRIPTION
**Pull request by CarolineSQ**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @CarolineSQ !

This is a great start! We just need a few more things before we can merge this in.

1) You are linking to a stylesheet called `../css/CSQ.css` in your advice page - but no such stylesheet exists as part of your pull request. Perhaps it still needs to be added and committed? Checking git status will help you confirm.

2) An unnecessary file `advice/Desktop - Shortcut.lnk`sneaked into the pul request, so please delete it. :)

3) We still need a link to your advice file in the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you have made these changes, add them with `git add -A`, and commit as per usual and then push your advice branch up once more (`git push origin advice`) which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by CarolineSQ** [comment]
Hello Ann

On your points 1 and 3 I had already done the CSS file CSQ.css and added
the link to my advice page on the main index page but maybe I didn't add
and commit but I think I have done it now. I have enclosed a screenshot of
Git so you can see.

On your point 2 : I have just noticed that the Desktop shortcut in my
advice folder is being created automatically as soon as I run the the cmd:
git checkout advice

Please see attached screenshot of Git

When I try to git push origin advice, I get an error message:
error: failed to push some refs to 'origin'

I am not sure if it's because I do not have any branch advice any longer?
I am so unsure of what I am supposed to do.  Maybe a step by step (every
single step) would be very beneficial as I am not sure I have grasped the
forking workflow entirely!

Many thanks and sorry to be a pain

Caroline

**Comment by redrambles** [comment]
Hey @CarolineSQ !

no worries - we can work through this! The screenshots aren't coming through in our thread over here, so please send them to us (with your message, so that we gather the necessary context) at 'questions@skillcrush.com' and we'll go from there!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @CarolineSQ !

Nice work - your code is merged in!


Cheers,
Ann :)

**Comment by CarolineSQ** [comment]
great thanks for the feedback!

Caroline

**Pull request merged**
