### PR TITLE
Created advice page and updated index.html

### PR DESCRIPTION
**Pull request by Victoria-Smith2720**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Victoria-Smith2720,

This is great! The only thing we need is for you to add a `<br>` tag at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add, commit, and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by Victoria-Smith2720** [comment]
I saw that! I wasn't quite sure what to do and where (i.e. on GitHub or VSC) Thanks very much! It'll be fixed soon.

**Comment by Victoria-Smith2720** [comment]
Is it correct now?

**Comment by twosavoie** [comment]
Hi @Victoria-Smith2720,

Perfect!!! Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

Best,
Lisa

**Pull request merged**
