### PR TITLE
Changed name to Kelly in html file and added css styling to webpage

### PR DESCRIPTION
**Pull request by Kelly-Campbell**
Finishing the Forking Workflow - Advice for Newbies Webpage - Changed name to Kelly in html file and added css styling to webpage.

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Kelly-Campbell,

This is great! The only thing we need is for you to add a `<br>` tag at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add and commit and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by Kelly-Campbell** [comment]
Hi @twosavoie!  Ok, I followed your instructions so I think we're good to go on the merge.  :-)

**Comment by twosavoie** [comment]
Hi @Kelly-Campbell,

Great job!! Congrats!! 🎉 

Best,
Lisa

**Comment by Kelly-Campbell** [comment]
Yaaaaay!!  Thanks @twosavoie!  :-)

**Pull request merged**
