### PR TITLE
Added AMO's advice page

### PR DESCRIPTION
**Pull request by AMOC0409**

### CODE REVIEW

**Comment by twosavoie** [comment]
Hey @AMOC0409,

Looks great! I only have 1 tiny request for you.

We would like for your advice file to be in the advice folder. If you could move it over there, then run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @AMOC0409,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by AMOC0409** [comment]
Hi Lisa,

I did not see this. When going to create a request, it doesn’t submit. It tells me the comparison is identical and on that it was uploaded correctly. But I can’t see my name that I added my files.

[Text  Description automatically generated]

---
CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.


From: Lisa Savoie ***@***.***>
Date: Wednesday, June 1, 2022 at 7:32 PM
To: skillcrush/git-practice ***@***.***>
Cc: Ana'jah McKnight-Odoms ***@***.***>, Mention ***@***.***>
Subject: Re: [skillcrush/git-practice] Added AMO's advice page (PR #616)

Hey @AMOC0409<https://github.com/AMOC0409>,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hi @AMOC0409!

Can you check to be sure that you're on the advice branch. Then check that the anajah-mcknightodoms-advice.html file is inside of the advice folder (not in the root of the project.) If so, you can run `git status` to be sure that the changes have been added and committed. If changes need to be added, run `git add -A`, then commit and try pushing the advice branch by running `git push origin advice`. Your pull request should update automatically. 

If it seems like everything is correct. Can you zip up your project folder (while on the advice branch) and send it to us at questions@skillcrush.com? It would be helpful to include a screenshot of the command line where you ran the commands. We would be happy to take a look!

xoxo,
Lisa

**Comment by twosavoie** [comment]
Hey @AMOC0409,

We haven't heard from you in a while so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Lisa

**Pull request closed without merging**
