### PR TITLE
Deleted repo starting lesson over again resubmitting new advice page …

### PR DESCRIPTION
**Pull request by Anjie-MF**
…after pull request need to add personalized css

### CODE REVIEW

**Comment by twosavoie** [comment]
Hi @Anjie-MF,

This is an awesome start! You did a fantastic job with the lesson. Just a couple of small changes to make.

It looks like there's an extra advice.html file in the root of the project folder. If you could go ahead and remove it, that would leave the advice.html file that's in the advice folder. Next, add a link to your css stylesheet in the <head> of your advice.html. 

Once you've removed the file and added the link, please add the change with `git add -A` (the capital A is important), commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions! 

Best,
Lisa
Screenshot 2023-06-19 at 11 43 11 PM (2)

**Comment by Anjie-MF** [comment]
Sorry for the multiple pull requests, I am used to always saving my documents. The last one is the most current and final. Let me know if I need to do anything!

**Comment by redrambles** [comment]
Hey @Anjie-MF !

This is amazing - we are nearly there! One last little thing is that we need to fix the closing link tag for your link in the index.html file (you're missing the **<** in `</a>`) and we need to add a `<br>` tag at the end of the line. 

Once those changes are made, save, add and commit and push up once more, and we should be good to go!!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Anjie-MF** [comment]
Don't know how you catch those itty bitty mistakes but thank you. Let me know if there is anything else I can do!

**Comment by twosavoie** [comment]
Hey @Anjie-MF,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

You showed a lot of determination in this lesson - which will serve you well as a developer! You should feel very proud of yourself!

Best,
Lisa

**Pull request merged**
