### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Jodunn1**

### CODE REVIEW

**Comment by Jodunn1** [comment]
This pull-request should be the updated version of my last attempt without the errors.

**Comment by twosavoie** [comment]
Hi @Jodunn1,

This is fantastic! The only thing we need is for you to add a `<br>` tag at the end of your link in the index.html file, so that the next person's link can sit on its own line.

Once you have made that change and saved the file, add and commit and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Best,
Lisa

**Comment by twosavoie** [comment]
Hi @Jodunn1,

Just checking to see if you need any help with this pull request. Let us know if you have any questions!

Best,
Lisa

**Comment by Jodunn1** [comment]
Hi Lisa,
Everything is good with the pull request. Thank you so much!
Thank you,
Jordan

**Comment by twosavoie** [comment]
Hi @Jodunn1,

We haven't heard from you in a while, so we're going to go ahead and close this pull request. Feel free to submit a new one when you're ready!

Best,
Lisa

**Comment by Jodunn1** [comment]
Hi Lisa,
I ended up actually submitting a new pull request for the project.
Thank you,
Jordan

**Comment by twosavoie** [comment]
That's great @Jodunn1!

**Pull request closed without merging**
