### PR TITLE
Jessica Peters advice

### PR DESCRIPTION
**Pull request by Jessica-Peters24**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Jessica-Peters24!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Jessica-Peters24** [comment]
Thanks for letting me know. I had inserted my link but then I had errors. I think I just fixed it but I’m really not sure. I updated the index.html file committed it and then used git push (git bash told me to). Let me know if I did it right. 
Thanks,

Jessica Peters

**Comment by redrambles** [comment]
Hey there!

I'm not seeing any changes on my end - can you try running that git push command again?

`git push origin advice`

We'll go from there!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Jessica-Peters24,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
