### PR TITLE
Added Nancy's advice

### PR DESCRIPTION
**Pull request by NancyStGelais**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @NancyStGelais,

Congrats on making your first pull request!

It looks like your advice file is in the root folder of this project. Instead, it should be located in the advice folder. Go ahead and move the file to the right place and then run `git add -A` in your terminal and then commit and push. Your updates will join your pull request here and then we can get that merged in.

xoxo,
Sharon

**Comment by NancyStGelais** [comment]
I have moved my advice file into advice folder, added the folder via git add -A, commited the change but now it will not let me push, just keeps asking for my passphrase.What have I missed? Thought I was finally getting this... Ugh


Nancy

**Comment by redrambles** [comment]
Hey @NancyStGelais !

So your passphrase is the one you chose when you first created your SSH key pair. Do you remember saving it in a password manager somewhere? If you did not, we might be able to recover it if it was saved to your keychain (and you are using a mac) - otherwise we'll need to regenerate your SSH keys (which isn't so bad, promise!). I see we are meeting up today in a Q&A session, so we can go over this then. :)

**Comment by redrambles** [comment]
Yay!!!!!!

**Pull request merged**
